update camposxsubformulario set ClasesLinea=ClasesLinea+' CWVariables', ClasesValor=ClasesValor + ' CWVariables' where nombrecampo in (
'Acreditado'
,'AcreditadoFin'
,'VerificarDatos'
,'VerificarDatosFin'
,'DatosCorrectos'
,'DatosCorrectosFin'
,'ActitudHostil'
,'ActitudHostilFin'
,'AplicaFPP'
,'AplicaFPPFin'
,'AceptaFPP1'
,'AceptaFPP1Fin'
,'AceptaFPP2'
,'AceptaFPP2Fin'
,'AceptaFPP3'
,'AceptaFPP3Fin'
,'AceptaFPP4'
,'AceptaFPP4Fin'
,'AceptaFPP5'
,'AceptaFPP5Fin'
,'AceptaFPP6'
,'AceptaFPP6Fin'
,'AceptaFPP'
,'AceptaFPPFin'
,'TotalizaA'
,'TotalizaC'
,'TotalizaB'
) and idtipocampo=2
and idsubformulario in (select  idsubformulario from subformulario  where idFormulario =(select idformulario from formulario where estatus=1 and captura=2 and Ruta='RDST'))


update camposxsubformulario set idtipocampo=1,ClasesTexto='CWAncho500',Texto='Sr o Sra. (nombre del titular del crédito)  le pedimos que por favor verifique que el importe que le están descontando corresponda al que marca su Aviso de Retención, el cual podrá obtener en www.infonavit.org.mx  en la ruta “Trabajadores”, ”Ya termine de pagar” “Avisos de Suspensión y Retención” ahí solo deberá ingresar su número de crédito y se desplegará su aviso.' where nombrecampo='TextoROASi' 
update camposxsubformulario set idtipocampo=1,ClasesTexto='CWAncho500',Texto='Sr o Sra. (nombre del titular del crédito) le recuerdo que al no realizar de manera oportuna el pago de la mensualidad de su crédito, se generarán intereses moratorios y por consiguiente su saldo sufrirá un incremento, por mi parte sería todo, gracias por su tiempo.' where nombrecampo='TextoROANo' 