//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubliPayments.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoOrdenes
    {
        public int idHistorico { get; set; }
        public string num_cred { get; set; }
        public int Estatus { get; set; }
        public string Dictamen { get; set; }
        public int idDominio { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> PromesaPago { get; set; }
        public string FechaPromesa { get; set; }
        public decimal Saldo { get; set; }
    }
}
