using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PubliPayments.Entidades
{
   public class SiraComerciosModel
    {
        public int ID_ARCHIVO { get; set; }
        public string TX_NOMBRE_DESPACHO { get; set; }
        public string Fecha { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string PersonalidadJuridica { get; set; }
        public string CV_CREDITO { get; set; }
        public string FechaPago { get; set; }
        public string Folio { get; set; }
        public string PuntoDeVenta { get; set; }
        public string Calle { get; set; }
        public string NumExt { get; set; }
        public string NumInt { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Municipio { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Telefono { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public string NumExtencion { get; set; }
        public string EmailContacto { get; set; }
        public string HorariosAtencion { get; set; }
        public string PaginaWeb { get; set; }
        public string NombreRepresentanteLegal { get; set; }
        public string EmailRepresentanteLegal { get; set; }
        public string TelefonoRepresentanteLegal { get; set; }
        public string NumExtencionRepresentanteLegal { get; set; }
        public string AireAcondicionado { get; set; }
        public string CarpinteriaMadera { get; set; }
        public string Cocinas { get; set; }
        public string Jardineria { get; set; }
        public string Electricidad { get; set; }
        public string Ferreteria { get; set; }
        public string MaterialesConstruccion { get; set; }
        public string Persianas { get; set; }
        public string PapelTapizCenefas { get; set; }
        public string PinturaInteriorExterior { get; set; }
        public string Pisos { get; set; }
        public string Plomeria { get; set; }
        public string CarceleriaHerreriaVentaneria { get; set; }
        public string LineaBlanca { get; set; }
        public string InstalacionManoObra { get; set; }
        public string Otros { get; set; }
        public string NumActa { get; set; }
        public string NumEscritura { get; set; }
        public string NumVolumen { get; set; }
        public string NumForja { get; set; }
        public string ObjetoSociedad { get; set; }
        public string TipoSociedad { get; set; }
        public string FechaConstitucion { get; set; }
        public string LugarConstitucion { get; set; }
        public string Notaria { get; set; }
        public string Notario { get; set; }
        public string CalleNotaria { get; set; }
        public string NumExtNotaria { get; set; }
        public string NumIntNotaria { get; set; }
        public string ColoniaNotaria { get; set; }
        public string MunicipioNotaria { get; set; }
        public string CiudadNotaria { get; set; }
        public string EstadoNotaria { get; set; }
        public string CodigoPostalNotaria { get; set; }
        public string NombreSocios { get; set; }
        public string MontoCapitalCreoSociedad { get; set; }
        public string CargaInformacion { get; set; }
        public string DomicilioFiscal { get; set; }
        public string ActividadRegistrada { get; set; }
        public string FechaInicioOperaciones { get; set; }
        public string FechaCambioGiroSat { get; set; }
        public string NombreOficinaEmitePermisoFuncionamiento { get; set; }
        public string Banco { get; set; }
        public string Activo1 { get; set; }
        public string Pasivo1 { get; set; }
        public string Capital1 { get; set; }
        public string Activo2 { get; set; }
        public string Pasivo2 { get; set; }
        public string Capital2 { get; set; }
        public string Activo3 { get; set; }
        public string Pasivo3 { get; set; }
        public string Capital3 { get; set; }
        public string NombreComercial2 { get; set; }
        public string DireccionCompleta2 { get; set; }
        public string GiroProductos2 { get; set; }
        public string NombreContacto2 { get; set; }
        public string EmailContacto2 { get; set; }
        public string TelefonoContacto2 { get; set; }
        public string CompraPromAnual2 { get; set; }
        public string NombreComercial3 { get; set; }
        public string DireccionCompleta3 { get; set; }
        public string GiroProductos3 { get; set; }
        public string NombreContacto3 { get; set; }
        public string EmailContacto3 { get; set; }
        public string TelefonoContacto3 { get; set; }
        public string CompraPromAnual3 { get; set; }
        public string NombreComercial4 { get; set; }
        public string DireccionCompleta4 { get; set; }
        public string GiroProductos4 { get; set; }
        public string NombreContacto4 { get; set; }
        public string EmailContacto4 { get; set; }
        public string TelefonoContacto4 { get; set; }
        public string CompraPromAnual4 { get; set; }
        public string NombreComercial5 { get; set; }
        public string DireccionCompleta5 { get; set; }
        public string GiroProductos5 { get; set; }
        public string NombreContacto5 { get; set; }
        public string EmailContacto5 { get; set; }
        public string TelefonoContacto5 { get; set; }
        public string CompraPromAnual5 { get; set; }
        public string NombreComercial6 { get; set; }
        public string DireccionCompleta6 { get; set; }
        public string GiroProductos6 { get; set; }
        public string NombreContacto6 { get; set; }
        public string EmailContacto6 { get; set; }
        public string TelefonoContacto6 { get; set; }
        public string CompraPromAnual6 { get; set; }
        public string PromVentaMensualPublico { get; set; }
        public string NombreComercial7 { get; set; }
        public string DireccionCompleta7 { get; set; }
        public string GiroProduccion7 { get; set; }
        public string NombreContacto7 { get; set; }
        public string EmailContacto7 { get; set; }
        public string TelefonoContacto7 { get; set; }
        public string VentaPromAnual7 { get; set; }
        public string NombreComercial8 { get; set; }
        public string DireccionCompleta8 { get; set; }
        public string GiroProduccion8 { get; set; }
        public string NombreContacto8 { get; set; }
        public string EmailContacto8 { get; set; }
        public string TelefonoContacto8 { get; set; }
        public string VentaPromAnual8 { get; set; }
        public string NombreComercial9 { get; set; }
        public string DireccionCompleta9 { get; set; }
        public string GiroProduccion9 { get; set; }
        public string NombreContacto9 { get; set; }
        public string EmailContacto9 { get; set; }
        public string TelefonoContacto9 { get; set; }
        public string VentaPromAnual9 { get; set; }
        public string NombreComercial10 { get; set; }
        public string DireccionCompleta10 { get; set; }
        public string GiroProduccion10 { get; set; }
        public string NombreContacto10 { get; set; }
        public string EmailContacto10 { get; set; }
        public string TelefonoContacto10 { get; set; }
        public string VentaPromAnual10 { get; set; }
        public string NombreComercial11 { get; set; }
        public string DireccionCompleta11 { get; set; }
        public string GiroProduccion11 { get; set; }
        public string NombreContacto11 { get; set; }
        public string EmailContacto11 { get; set; }
        public string TelefonoContacto11 { get; set; }
        public string VentaPromAnual11 { get; set; }
        public string NumEmpleadosTotal { get; set; }
        public string NumEmpleadosCadaSucursal { get; set; }
        public string ReciboTelefonico { get; set; }
        public string CartaProveedor { get; set; }
        public string ActaConstitutiva { get; set; }
        public string IdentificacionOficialRepLegal { get; set; }
        public string PoderNotarialRepLegal { get; set; }
        public string FormatoInscripcionSAT { get; set; }
        public string ComDomFiscal { get; set; }
        public string DeclaracionFiscal2013 { get; set; }
        public string DeclaracionFiscal2014 { get; set; }
        public string CompPagosImpParcial2015 { get; set; }
        public string PermisosOperacion { get; set; }
        public string CompDomTodasSucursal { get; set; }
        public string CaratulaEstadoCuentaMesAnt { get; set; }
        public string CaratulaEstadoCuenta2doMesAnt { get; set; }
        public string CaratulaEstadoCuenta3erMesAnt { get; set; }
        public string EstadoFinanciero2012 { get; set; }
        public string EstadoFinanciero2013 { get; set; }
        public string EstadoFinanciero2014 { get; set; }
        public string TresCopiasFacturaCompraProv1 { get; set; }
        public string TresCopiasFacturaCompraProv2 { get; set; }
        public string TresCopiasFacturaCompraProv3 { get; set; }
        public string TresCopiasFacturaCompraProv4 { get; set; }
        public string TresCopiasFacturaCompraProv5 { get; set; }
        public string TrescopiasFacturaVentaCliente1 { get; set; }
        public string TrescopiasFacturaVentaCliente2 { get; set; }
        public string TrescopiasFacturaVentaCliente3 { get; set; }
        public string TrescopiasFacturaVentaCliente4 { get; set; }
        public string TrescopiasFacturaVentaCliente5 { get; set; }
        public string UltimoCompPagoObligacionObreroPatronal { get; set; }
        public string CompPagoServicioCertificacion { get; set; }
        public string CargaDocCapturadoFirmado { get; set; }
        public string AvisoPrivacidad { get; set; }
        public string QuizScore { get; set; }
        public string ReferenceID { get; set; }
        public string IP { get; set; }
        public string Country { get; set; }
        public string PaymentAmount { get; set; }
        public string PaymentCurrency { get; set; }
        public string PaymentCompleted { get; set; }
        public string CouponCodes { get; set; }
        public string Browser { get; set; }
        public string EntryID { get; set; }
        public string ApprovalStatus { get; set; }
        public string Status { get; set; }
        public string NumReporte { get; set; }
        public Nullable<int> NumSucursal { get; set; }
        public string FechaPayments { get; set; }
        public string CV_RUTA { get; set; }
    }
}
