-- =============================================
-- AUTHOR:		LAURA DOTOR
-- CREATE DATE: 2016-10-04
-- DESCRIPTION:	OBTIENE INDICADORES PARA RANKING POR MODULO, 
-- SE AGREGA RUTA, SE CREA PARA QUITAR EL SELECT DEL CÓDIGO
-- =============================================
CREATE PROCEDURE [dbo].[ObtenerIndicadoresRanking]
@PermisoModulo VARCHAR(15),
@NombreRuta VARCHAR(10)
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT 
		FC_CLAVE AS Clave,
		UD.FC_DESCRIPCION AS Descripcion 
	FROM DBO.UTILS_DESCRIPCIONES UD WITH(NOLOCK)
	LEFT JOIN DBO.UTILS_PERMISOS UP WITH(NOLOCK) ON UD.FI_IDPERMISOS = UP.IDPERMISO 
	WHERE UD.FC_MODULO = 'DASHBOARD' 
	AND UD.FI_ACTIVO = 1 
	AND UP.PERMISOMODULO = @PermisoModulo 
	AND (RUTA = @NombreRuta OR RUTA = '*')
	AND FC_CLAVE NOT IN('DASH_TOTALMES','DASH_DIASREST', 'RDST_GESTPROMDIA', 'RDST_GESTPROMASESOR') ORDER BY UD.FI_PARTE,UD.FI_ORDEN

END

