//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionFragancias.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_PRODUCTOS_PEDIDOS
    {
        public COM_PRODUCTOS_PEDIDOS()
        {
            this.COM_ENTREGAS_PRODUCTO = new HashSet<COM_ENTREGAS_PRODUCTO>();
        }
    
        public int IDPRODUCTOSPEDIDOS { get; set; }
        public string NOORDENCOMPRA { get; set; }
        public Nullable<short> IDUNIDADESMEDIDA { get; set; }
        public Nullable<short> IDPRESENTACION { get; set; }
        public Nullable<short> IDESTAUSPRODUCTO { get; set; }
        public Nullable<short> IDALAMACENES { get; set; }
        public string CVEPRODUCTO { get; set; }
        public int PARTIDA { get; set; }
        public decimal CANTIDAD { get; set; }
        public System.DateTime FECHAENTREGA { get; set; }
        public decimal PRECIOUNITARIO { get; set; }
        public bool ENTREGADO { get; set; }
        public bool BORRADO { get; set; }
    
        public virtual ALM_ALMECENES ALM_ALMECENES { get; set; }
        public virtual COM_CAT_ESTATUS_PRODUCTO COM_CAT_ESTATUS_PRODUCTO { get; set; }
        public virtual COM_CAT_PRESENTACION COM_CAT_PRESENTACION { get; set; }
        public virtual COM_CAT_UNIDADES_MEDIDA COM_CAT_UNIDADES_MEDIDA { get; set; }
        public virtual ICollection<COM_ENTREGAS_PRODUCTO> COM_ENTREGAS_PRODUCTO { get; set; }
        public virtual COM_ORDENCOMPRA COM_ORDENCOMPRA { get; set; }
    }
}
