//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionFragancias.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CON_CONTACTO
    {
        public CON_CONTACTO()
        {
            this.PER_PERSONA = new HashSet<PER_PERSONA>();
        }
    
        public int IDCONTACTOS { get; set; }
        public string CORREOELECTRONICOPERSONAL { get; set; }
        public string CORREOELECTRONICOTRABAJO { get; set; }
        public string ALTERNATIVO1 { get; set; }
        public string ALTERNATIVO2 { get; set; }
        public bool BORRADO { get; set; }
    
        public virtual ICollection<PER_PERSONA> PER_PERSONA { get; set; }
    }
}
