//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionFragancias.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIR_DIRECCIONES
    {
        public DIR_DIRECCIONES()
        {
            this.PER_PERSONA = new HashSet<PER_PERSONA>();
        }
    
        public int IDDIRECCION { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> IDMUNICIPIO { get; set; }
        public Nullable<int> IDCOLONIA { get; set; }
        public string CALLE { get; set; }
        public string NOEXT { get; set; }
        public string NOINT { get; set; }
        public string REFERENCIAS { get; set; }
    
        public virtual DIR_CAT_COLONIAS DIR_CAT_COLONIAS { get; set; }
        public virtual DIR_CAT_ESTADO DIR_CAT_ESTADO { get; set; }
        public virtual ICollection<PER_PERSONA> PER_PERSONA { get; set; }
    }
}
