DELETE DIR_DIRECCIONES
DELETE PER_CAT_TELEFONOS
DELETE PER_CAT_NACIONALIDAD
DELETE PER_CAT_TIPO_PERSONA
DELETE PER_FOTOGRAFIA
DELETE PER_MEDIOS_ELECTRONICOS
DELETE US_CAT_ESTATUS_USUARIO
DELETE US_CAT_NIVEL_USUARIO
DELETE US_CAT_TIPO_USUARIO
DELETE US_HISTORIAL
DELETE SIS_CAT_TABPAGES
DELETE SIS_AADM_ARBOLMENUS

DELETE PER_PERSONAS
DELETE US_USUARIOS
DELETE SIS_AADM_APLICACIONES

DBCC CHECKIDENT('PER_PERSONAS', RESEED, 0)
DBCC CHECKIDENT('SIS_AADM_APLICACIONES', RESEED, 0)
DBCC CHECKIDENT('DIR_DIRECCIONES', RESEED, 0)
DBCC CHECKIDENT('PER_FOTOGRAFIA', RESEED, 0)
DBCC CHECKIDENT('US_HISTORIAL', RESEED, 0)
DBCC CHECKIDENT('US_USUARIOS', RESEED, 0)