SELECT * FROM PER_PERSONAS AS PP
LEFT OUTER JOIN DIR_DIRECCIONES AS DD ON PP.IDDIRECCION = DD.IDDIRECCION
LEFT OUTER JOIN DIR_CAT_COLONIAS AS DCC ON DD.IDCOLONIA = DCC.IDCOLONIA
LEFT OUTER JOIN DIR_CAT_DELG_MUNICIPIO AS DCDM ON DD.IDMUNICIPIO = DCDM.IDMUNICIPIO AND DD.IDESTADO = DCDM.IDESTADO
--LEFT OUTER JOIN DIR_CAT_ESTADO AS DCE ON DD.IDESTADO = DCE.IDESTADO
--LEFT OUTER JOIN PER_CAT_NACIONALIDAD AS PCN ON PP.CVE_NACIONALIDAD = PCN.CVE_NACIONALIDAD
--LEFT OUTER JOIN PER_CAT_TELEFONOS AS PCT ON PP.ID_TELEFONOS = PCT.ID_TELEFONOS
WHERE pp.ID_PERSONA = 1009