SELECT * FROM US_CAT_ESTATUS_USUARIO
SELECT * FROM US_CAT_NIVEL_USUARIO
SELECT * FROM US_CAT_TIPO_USUARIO
SELECT * FROM SIS_CAT_TABPAGES
SELECT * FROM SIS_AADM_ARBOLMENUS

SELECT * FROM US_USUARIOS
SELECT * FROM SIS_AADM_APLICACIONES
SELECT * FROM PER_PERSONAS