//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAEEEM.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCIONES_ROL
    {
        public byte ID { get; set; }
        public byte ID_Acciones { get; set; }
        public int Id_Rol { get; set; }
        public string Adicionado_Por { get; set; }
        public System.DateTime Fecha_Adicion { get; set; }
        public string Modificado_Por { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public bool Estatus { get; set; }
    
        public virtual CAT_ACCIONES CAT_ACCIONES { get; set; }
        public virtual US_ROL US_ROL { get; set; }
    }
}
