//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAEEEM.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_Cliente
    {
        public CLI_Cliente()
        {
            this.CLI_Negocio = new HashSet<CLI_Negocio>();
        }
    
        public int Id_Proveedor { get; set; }
        public int Id_Branch { get; set; }
        public int IdCliente { get; set; }
        public Nullable<byte> Cve_Tipo_Sociedad { get; set; }
        public Nullable<byte> IdRegimenConyugal { get; set; }
        public Nullable<byte> Cve_Estado_Civil { get; set; }
        public string Razon_Social { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string Nombre { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public Nullable<System.DateTime> Fec_Nacimiento { get; set; }
        public string email { get; set; }
        public string Telefono_Local { get; set; }
        public string Telefono_Oficina { get; set; }
        public string Celular { get; set; }
        public Nullable<byte> Genero { get; set; }
        public System.DateTime Fecha_Adicion { get; set; }
        public string AdicionadoPor { get; set; }
        public byte Estatus { get; set; }
    
        public virtual CAT_CLI_REGIMEN_CONYUGAL CAT_CLI_REGIMEN_CONYUGAL { get; set; }
        public virtual CAT_ESTADO_CIVIL CAT_ESTADO_CIVIL { get; set; }
        public virtual CAT_TIPO_SOCIEDAD CAT_TIPO_SOCIEDAD { get; set; }
        public virtual ICollection<CLI_Negocio> CLI_Negocio { get; set; }
    }
}
