//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAEEEM.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAS_OPERACION
    {
        public DIAS_OPERACION()
        {
            this.CLI_HORARIOS_OPERACION = new HashSet<CLI_HORARIOS_OPERACION>();
            this.MRV_HORARIOS_OPERACION = new HashSet<MRV_HORARIOS_OPERACION>();
        }
    
        public byte ID_DIA_OPERACION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<CLI_HORARIOS_OPERACION> CLI_HORARIOS_OPERACION { get; set; }
        public virtual ICollection<MRV_HORARIOS_OPERACION> MRV_HORARIOS_OPERACION { get; set; }
    }
}
