//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
// 
namespace eClock.localhost1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_ServicioRDatosSoap", Namespace="http://tempuri.org/")]
    public class WS_ServicioRDatos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WS_ServicioRDatos() {
            this.Url = "http://localhost/eClock/WS_ServicioRDatos.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecepcionDatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecepcionDatos(string Dato) {
            object[] results = this.Invoke("RecepcionDatos", new object[] {
                        Dato});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRecepcionDatos(string Dato, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RecepcionDatos", new object[] {
                        Dato}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRecepcionDatos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObtenerID() {
            object[] results = this.Invoke("ObtenerID", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerID(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerID", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndObtenerID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarRegistros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardarRegistros(string Datos) {
            object[] results = this.Invoke("GuardarRegistros", new object[] {
                        Datos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGuardarRegistros(string Datos, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GuardarRegistros", new object[] {
                        Datos}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGuardarRegistros(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
