CREATE TABLE ECLOCK_INCIDENCIAS_EMPL
	(
	CLAVE_EMPL decimal(18, 0) NULL,
	ELEMENTO varchar(50) NULL,
	UNIDAD decimal(18, 2) NULL,
	FECHA_APLICACION datetime NULL,
	FOLIO_INCAPACIDAD varchar(30) NULL,
	CONTROL_INC varchar(10) NULL,
	IMPORTE decimal(18, 2) NULL,
	FECHA_INICO_REAL datetime NULL,
	FECHA_FIN_REAL datetime NULL,
	STATUS decimal(18, 0) NULL,
	FECHA_INSERCION datetime NULL,
	PERIODO decimal(18, 0) NULL,
	ID_INCAPACIDAD_ORACLE decimal(18, 0) NULL
	);