//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefaultResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nodo.
        /// </summary>
        internal static string btnAddnode {
            get {
                return ResourceManager.GetString("btnAddnode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Nodo.
        /// </summary>
        internal static string btnDeletenode {
            get {
                return ResourceManager.GetString("btnDeletenode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Nodo.
        /// </summary>
        internal static string btnEditnode {
            get {
                return ResourceManager.GetString("btnEditnode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Árbol.
        /// </summary>
        internal static string btnRefreshTree {
            get {
                return ResourceManager.GetString("btnRefreshTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar Código.
        /// </summary>
        internal static string CaptchaCheck {
            get {
                return ResourceManager.GetString("CaptchaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado:.
        /// </summary>
        internal static string CaptchaCheckResult {
            get {
                return ResourceManager.GetString("CaptchaCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CaptchaClear {
            get {
                return ResourceManager.GetString("CaptchaClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error del Sistema, Intente más Tarde..
        /// </summary>
        internal static string CaptchaFatal {
            get {
                return ResourceManager.GetString("CaptchaFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escriba el Texto de Arriba.
        /// </summary>
        internal static string CaptchaMsj {
            get {
                return ResourceManager.GetString("CaptchaMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Código de Servicio No es Válido: {0}.&lt;br /&gt;Razón: {1}.
        /// </summary>
        internal static string CaptchaResultRPUInvalid {
            get {
                return ResourceManager.GetString("CaptchaResultRPUInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Código de Servicio es Válido para el Programa: {0}.
        /// </summary>
        internal static string CaptchaResultRPUValid {
            get {
                return ResourceManager.GetString("CaptchaResultRPUValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo Sentimos, el Texto Escrito es Incorrecto.
        /// </summary>
        internal static string CaptchaResultTextInvalid {
            get {
                return ResourceManager.GetString("CaptchaResultTextInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Servicio.
        /// </summary>
        internal static string CaptchaRPU {
            get {
                return ResourceManager.GetString("CaptchaRPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas para Leer el Texto?, Pruebe otra Palabra.
        /// </summary>
        internal static string CaptchaTryNewWords {
            get {
                return ResourceManager.GetString("CaptchaTryNewWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible editar el crédito, se requiere que esté en estatus Pendiente y no haber realizado la consulta crediticia.
        /// </summary>
        internal static string CreditEditionInvalid {
            get {
                return ResourceManager.GetString("CreditEditionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Número de Unidades es Incorrecto.
        /// </summary>
        internal static string DataFormatIncorrect {
            get {
                return ResourceManager.GetString("DataFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de los Gastos de Instalación y Mano de Obra no deben superar el 30% de la suma del Costo de los equipos mas los Gastos de Instalación y Mano de Obra..
        /// </summary>
        internal static string DataGastosIncorrect {
            get {
                return ResourceManager.GetString("DataGastosIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Precio Unitario es incorrecto, capture una cantidad entre 1 y {0}.
        /// </summary>
        internal static string DataPrecioIncorrect {
            get {
                return ResourceManager.GetString("DataPrecioIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen créditos con 25 días o más en estatus &apos;Pendiente&apos; que no han sido atendidos por el proveedor correspondiente.  Se tienen 5 días para que sean atendidos o serán Cancelados automáticamente..
        /// </summary>
        internal static string Email25DaysPendingBody {
            get {
                return ResourceManager.GetString("Email25DaysPendingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia del Sistema PAEEEM.
        /// </summary>
        internal static string Email25DaysPendingTitle {
            get {
                return ResourceManager.GetString("Email25DaysPendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estatus del crédito no es válido para esta operación.
        /// </summary>
        internal static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento.
        /// </summary>
        internal static string LabelBirthDateInmoral {
            get {
                return ResourceManager.GetString("LabelBirthDateInmoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Constitución.
        /// </summary>
        internal static string LabelBirthDateMoral {
            get {
                return ResourceManager.GetString("LabelBirthDateMoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string LabelPersonaNombre {
            get {
                return ResourceManager.GetString("LabelPersonaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        internal static string LabelPersonaRazon {
            get {
                return ResourceManager.GetString("LabelPersonaRazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Nodo.
        /// </summary>
        internal static string lblNodeInfo {
            get {
                return ResourceManager.GetString("lblNodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la Página.
        /// </summary>
        internal static string lblNodeInfoPage {
            get {
                return ResourceManager.GetString("lblNodeInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Nodo.
        /// </summary>
        internal static string lblNodeName {
            get {
                return ResourceManager.GetString("lblNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Nodo.
        /// </summary>
        internal static string lblNodeNo {
            get {
                return ResourceManager.GetString("lblNodeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia del Nodo.
        /// </summary>
        internal static string lblNodeSequence {
            get {
                return ResourceManager.GetString("lblNodeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Nodo.
        /// </summary>
        internal static string lblNodeType {
            get {
                return ResourceManager.GetString("lblNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodo Padre.
        /// </summary>
        internal static string lblParentNode {
            get {
                return ResourceManager.GetString("lblParentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página Principal.
        /// </summary>
        internal static string lblParentNodePage {
            get {
                return ResourceManager.GetString("lblParentNodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbol de Permisos.
        /// </summary>
        internal static string lblPermissionTree {
            get {
                return ResourceManager.GetString("lblPermissionTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Permiso.
        /// </summary>
        internal static string lblPermissionType {
            get {
                return ResourceManager.GetString("lblPermissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Rol.
        /// </summary>
        internal static string lblRoleName {
            get {
                return ResourceManager.GetString("lblRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Todo.
        /// </summary>
        internal static string lblSelectAll {
            get {
                return ResourceManager.GetString("lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbol de Información del Nodo.
        /// </summary>
        internal static string lblTreeNodeInformation {
            get {
                return ResourceManager.GetString("lblTreeNodeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Tarifas y Costos.
        /// </summary>
        internal static string menu_AddRateandCost {
            get {
                return ResourceManager.GetString("menu_AddRateandCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo Oficina Central.
        /// </summary>
        internal static string menu_CentralModel {
            get {
                return ResourceManager.GetString("menu_CentralModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Permisos.
        /// </summary>
        internal static string menu_PermissionAssignment {
            get {
                return ResourceManager.GetString("menu_PermissionAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Permisos.
        /// </summary>
        internal static string menu_PermissionManager {
            get {
                return ResourceManager.GetString("menu_PermissionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor de Tarifas y Costos.
        /// </summary>
        internal static string menu_RateAndCostMonitor {
            get {
                return ResourceManager.GetString("menu_RateAndCostMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Funciones.
        /// </summary>
        internal static string menu_RoleAssignment {
            get {
                return ResourceManager.GetString("menu_RoleAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Roles.
        /// </summary>
        internal static string menu_RoleManager {
            get {
                return ResourceManager.GetString("menu_RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Roles.
        /// </summary>
        internal static string menu_RolePermissionManager {
            get {
                return ResourceManager.GetString("menu_RolePermissionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación entre Roles.
        /// </summary>
        internal static string menu_RoleToRole {
            get {
                return ResourceManager.GetString("menu_RoleToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Usuarios.
        /// </summary>
        internal static string menu_UserManagement {
            get {
                return ResourceManager.GetString("menu_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo de Usuario.
        /// </summary>
        internal static string menu_UserModel {
            get {
                return ResourceManager.GetString("menu_UserModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición del Nodo Exitoso!.
        /// </summary>
        internal static string mgEditNodeSuccess {
            get {
                return ResourceManager.GetString("mgEditNodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Carga de Datos.
        /// </summary>
        internal static string mgLoadDataError {
            get {
                return ResourceManager.GetString("mgLoadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Agregó el Nodo Correctamente!.
        /// </summary>
        internal static string mgNodeSuccess {
            get {
                return ResourceManager.GetString("mgNodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nodo tiene Elementos Dependientes, no será Borrado!.
        /// </summary>
        internal static string mgNotDeleteNode {
            get {
                return ResourceManager.GetString("mgNotDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Favor, Compruebe los Nodos raíz!.
        /// </summary>
        internal static string mgPleasecheckrootnodes {
            get {
                return ResourceManager.GetString("mgPleasecheckrootnodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Favor, Compruebe los Nodos de Segundo Nivel!.
        /// </summary>
        internal static string mgPleasecheckSecondrootnodes {
            get {
                return ResourceManager.GetString("mgPleasecheckSecondrootnodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione un estado.
        /// </summary>
        internal static string mgPleasechooseaestado {
            get {
                return ResourceManager.GetString("mgPleasechooseaestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Favor seleccione una Tarifa!.
        /// </summary>
        internal static string mgPleasechooseatarifa {
            get {
                return ResourceManager.GetString("mgPleasechooseatarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Favor, Seleccione un Nodo!.
        /// </summary>
        internal static string mgPleaseSelectNode {
            get {
                return ResourceManager.GetString("mgPleaseSelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación de Roles Guardados con Éxito!.
        /// </summary>
        internal static string mgSaveRoleRelationSuccess {
            get {
                return ResourceManager.GetString("mgSaveRoleRelationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOP NO válido.
        /// </summary>
        internal static string MOPError96 {
            get {
                return ResourceManager.GetString("MOPError96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOP NO válido.
        /// </summary>
        internal static string MOPError99 {
            get {
                return ResourceManager.GetString("MOPError99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin conexión a Circulo de Crédito, intente mas tarde..
        /// </summary>
        internal static string MOPErrorConnection {
            get {
                return ResourceManager.GetString("MOPErrorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOP NO válido.
        /// </summary>
        internal static string MOPErrorInvalid {
            get {
                return ResourceManager.GetString("MOPErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valido: El MOP obtenido es &gt;=0 y &lt;= {0}.
        /// </summary>
        internal static string MOPOK {
            get {
                return ResourceManager.GetString("MOPOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Inválido..
        /// </summary>
        internal static string msgAccountInvalid {
            get {
                return ResourceManager.GetString("msgAccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación exitosa..
        /// </summary>
        internal static string msgActivateUserSuccess {
            get {
                return ResourceManager.GetString("msgActivateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Contraseña Fallida..
        /// </summary>
        internal static string msgChangePasswordFailure {
            get {
                return ResourceManager.GetString("msgChangePasswordFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su Contraseña ha sido Cambiada..
        /// </summary>
        internal static string msgChangePasswordSuccess {
            get {
                return ResourceManager.GetString("msgChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de rol exitosa..
        /// </summary>
        internal static string msgChooseUser {
            get {
                return ResourceManager.GetString("msgChooseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro borrado exitosamente..
        /// </summary>
        internal static string msgDeleteUserSuccess {
            get {
                return ResourceManager.GetString("msgDeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Password Exitoso..
        /// </summary>
        internal static string msgForgetPassword {
            get {
                return ResourceManager.GetString("msgForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o Password Inválido..
        /// </summary>
        internal static string msgInvalidUserAccount {
            get {
                return ResourceManager.GetString("msgInvalidUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un Corporativo o Sucursal.
        /// </summary>
        internal static string msgMissingSelection {
            get {
                return ResourceManager.GetString("msgMissingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de crédito con Éxito..
        /// </summary>
        internal static string msgPendienteCreditSuccess {
            get {
                return ResourceManager.GetString("msgPendienteCreditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de Crédito No..
        /// </summary>
        internal static string msgPendienteFailed {
            get {
                return ResourceManager.GetString("msgPendienteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Favor, Seleccione un Registro.
        /// </summary>
        internal static string msgPleaseSelectOne {
            get {
                return ResourceManager.GetString("msgPleaseSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se encuentra Firmado..
        /// </summary>
        internal static string msgRepeatLogin {
            get {
                return ResourceManager.GetString("msgRepeatLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al Guardar!.
        /// </summary>
        internal static string msgSaveError {
            get {
                return ResourceManager.GetString("msgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló el Guardado del Crédito.
        /// </summary>
        internal static string msgSaveFailReview {
            get {
                return ResourceManager.GetString("msgSaveFailReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado con Éxito!.
        /// </summary>
        internal static string msgSavesuccessfully {
            get {
                return ResourceManager.GetString("msgSavesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización del Crédito Exitosa.
        /// </summary>
        internal static string msgSaveSucessReview {
            get {
                return ResourceManager.GetString("msgSaveSucessReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se Guardó Correctamente!.
        /// </summary>
        internal static string msgSaveUserSuccess {
            get {
                return ResourceManager.GetString("msgSaveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su Contraseña ha sido Enviada a su Correo Asociado.
        /// </summary>
        internal static string msgSendsuccess {
            get {
                return ResourceManager.GetString("msgSendsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Tarifa ya Existe.
        /// </summary>
        internal static string msgTarifaExists {
            get {
                return ResourceManager.GetString("msgTarifaExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la actualización.
        /// </summary>
        internal static string msgUpdateUserRoleFail {
            get {
                return ResourceManager.GetString("msgUpdateUserRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización exitosa..
        /// </summary>
        internal static string msgUpdateUserRoleSuccess {
            get {
                return ResourceManager.GetString("msgUpdateUserRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se Actualizó Correctamente!.
        /// </summary>
        internal static string msgUpdateUserSuccess {
            get {
                return ResourceManager.GetString("msgUpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario está Inactivo o Cancelado..
        /// </summary>
        internal static string msgUserIsInactiveOrCanceled {
            get {
                return ResourceManager.GetString("msgUserIsInactiveOrCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario se encuentra Pendiente..
        /// </summary>
        internal static string msgUserIsPending {
            get {
                return ResourceManager.GetString("msgUserIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario ya Existe!.
        /// </summary>
        internal static string msgUserNameExist {
            get {
                return ResourceManager.GetString("msgUserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario No Existe..
        /// </summary>
        internal static string msgUserNameInvalid {
            get {
                return ResourceManager.GetString("msgUserNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en la Autorización.
        /// </summary>
        internal static string msgUSFailToAutorizado {
            get {
                return ResourceManager.GetString("msgUSFailToAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en la Cancelación.
        /// </summary>
        internal static string msgUSFailToCancel {
            get {
                return ResourceManager.GetString("msgUSFailToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en el Rechazo.
        /// </summary>
        internal static string msgUSFailToRechazado {
            get {
                return ResourceManager.GetString("msgUSFailToRechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo en la Revisión.
        /// </summary>
        internal static string msgUSFailToRevision {
            get {
                return ResourceManager.GetString("msgUSFailToRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Crédito(s) ya no son válidos y fueron cancelados!!.
        /// </summary>
        internal static string msgUSInvalidToAutorizado {
            get {
                return ResourceManager.GetString("msgUSInvalidToAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Autorizó Exitosamente.
        /// </summary>
        internal static string msgUSSuccessToAutorizado {
            get {
                return ResourceManager.GetString("msgUSSuccessToAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Canceló Exitosamente.
        /// </summary>
        internal static string msgUSSuccessToCancel {
            get {
                return ResourceManager.GetString("msgUSSuccessToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha Realizado el Rechazo.
        /// </summary>
        internal static string msgUSSuccessToRechazado {
            get {
                return ResourceManager.GetString("msgUSSuccessToRechazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha Realizado la Revisión.
        /// </summary>
        internal static string msgUSSuccessToRevision {
            get {
                return ResourceManager.GetString("msgUSSuccessToRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto del descuento es erróneo, verifique sus precios..
        /// </summary>
        internal static string NegativeDiscount {
            get {
                return ResourceManager.GetString("NegativeDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de pago por concepto de financiamiento no puede ser mayor a el 20% del importe promedio de su facturación eléctrica de los últimos 12 meses.
        /// </summary>
        internal static string PaymentGraterThan20PctCurrentRate {
            get {
                return ResourceManager.GetString("PaymentGraterThan20PctCurrentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbol de Permisos.
        /// </summary>
        internal static string PermissionTree {
            get {
                return ResourceManager.GetString("PermissionTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha realizado la captura completa de al menos un producto..
        /// </summary>
        internal static string PleaseSelectProduct {
            get {
                return ResourceManager.GetString("PleaseSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, el periodo de recuperación es mayor a 4 años.
        /// </summary>
        internal static string QuoteGreaterPSR {
            get {
                return ResourceManager.GetString("QuoteGreaterPSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Capacidad de Pago es Menor al Monto de la Cotización.
        /// </summary>
        internal static string QuoteGreaterThanPaymentCapacity {
            get {
                return ResourceManager.GetString("QuoteGreaterThanPaymentCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Capacidad de Pago del Obligado Solidario es Menor al Monto Requerido.
        /// </summary>
        internal static string QuoteGreaterThanPaymentCapacityAval {
            get {
                return ResourceManager.GetString("QuoteGreaterThanPaymentCapacityAval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto rebasa el límite del programa para este RFC.
        /// </summary>
        internal static string QuoteGreaterThanRFCLimit {
            get {
                return ResourceManager.GetString("QuoteGreaterThanRFCLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C02: Lo sentimos, el periodo de recuperación es mayor a 4 años.
        /// </summary>
        internal static string QuoteNegativeBilling {
            get {
                return ResourceManager.GetString("QuoteNegativeBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo por debajo del requerido.
        /// </summary>
        internal static string QuoteNegativeSaving {
            get {
                return ResourceManager.GetString("QuoteNegativeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Rol.
        /// </summary>
        internal static string RoleAssignment {
            get {
                return ResourceManager.GetString("RoleAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha Guardado con Éxito la Solicitud. Crédito Número: .
        /// </summary>
        internal static string Savesuccessfull {
            get {
                return ResourceManager.GetString("Savesuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al validar código de servicio: {0}.
        /// </summary>
        internal static string SICOMValidation {
            get {
                return ResourceManager.GetString("SICOMValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0101: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA.
        /// </summary>
        internal static string SICOM_Communication_Status_66 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0209: DATOS NO ACTUALIZADOS.
        /// </summary>
        internal static string SICOM_Communication_Status_A4 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0309: DATOS NO ACTUALIZADOS
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_A5 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0409: DATOS NO ACTUALIZADOS
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_ES {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0501: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_RD {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_RD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0601: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S0 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0702: NÚMERO DE SERVICIO NO VÁLIDO.
        /// </summary>
        internal static string SICOM_Communication_Status_S1 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0801: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S2 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0901: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S3 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1001: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S4 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1111: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S5 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1203: SIN CONSUMO DE ENERGÍA ELÉCTRICA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S6 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1309: DATOS NO ACTUALIZADOS
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S7 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1410: DATOS NO ACTUALIZADOS
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S8 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1509: DATOS NO ACTUALIZADOS
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_S9 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_S9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1601: SIN CONEXIÓN CON EL SERVIDOR DE CONSULTA
        ///.
        /// </summary>
        internal static string SICOM_Communication_Status_W1 {
            get {
                return ResourceManager.GetString("SICOM_Communication_Status_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Número de Servicio ya tiene un Crédito.
        /// </summary>
        internal static string TheServiceCodehaveUsed {
            get {
                return ResourceManager.GetString("TheServiceCodehaveUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Número de Servicio ???? Pyme .
        /// </summary>
        internal static string TheServiceCodeNotPyME {
            get {
                return ResourceManager.GetString("TheServiceCodeNotPyME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol guardado exitosamente.
        /// </summary>
        internal static string UpdateRoleSuccess {
            get {
                return ResourceManager.GetString("UpdateRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2602: NÚMERO  DE SERVICIO NO VÁLIDO
        ///.
        /// </summary>
        internal static string UserStatusInvalid {
            get {
                return ResourceManager.GetString("UserStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2711: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid00 {
            get {
                return ResourceManager.GetString("UserStatusInvalid00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2812: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid02 {
            get {
                return ResourceManager.GetString("UserStatusInvalid02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2913: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid03 {
            get {
                return ResourceManager.GetString("UserStatusInvalid03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3014: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid04 {
            get {
                return ResourceManager.GetString("UserStatusInvalid04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3115: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid05 {
            get {
                return ResourceManager.GetString("UserStatusInvalid05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3216: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid06 {
            get {
                return ResourceManager.GetString("UserStatusInvalid06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3417: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid07 {
            get {
                return ResourceManager.GetString("UserStatusInvalid07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3518: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///.
        /// </summary>
        internal static string UserStatusInvalid08 {
            get {
                return ResourceManager.GetString("UserStatusInvalid08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3619: INCONVENIENTE CON SU NÚMERO DE SERVICIO.
        /// </summary>
        internal static string UserStatusInvalid09 {
            get {
                return ResourceManager.GetString("UserStatusInvalid09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario está Cancelado o Inactivo.
        /// </summary>
        internal static string UserStatusInvalidate {
            get {
                return ResourceManager.GetString("UserStatusInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La edad del Solicitante del crédito No cumple con los requisitos del Programa.
        /// </summary>
        internal static string ValidateAge {
            get {
                return ResourceManager.GetString("ValidateAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La edad del Aval del crédito No cumple con los requisitos del Programa.
        /// </summary>
        internal static string ValidateAgeAval {
            get {
                return ResourceManager.GetString("ValidateAgeAval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CURP del aval no concuerda con los datos capturados.
        /// </summary>
        internal static string ValidateCURPAval {
            get {
                return ResourceManager.GetString("ValidateCURPAval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CURP de la persona no concuerda con los datos capturados.
        /// </summary>
        internal static string ValidateCURPPersona {
            get {
                return ResourceManager.GetString("ValidateCURPPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El RFC del aval no concuerda con los datos capturados.
        /// </summary>
        internal static string ValidateRFCAval {
            get {
                return ResourceManager.GetString("ValidateRFCAval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El RFC de la persona no concuerda con los datos capturados.
        /// </summary>
        internal static string ValidateRFCPersona {
            get {
                return ResourceManager.GetString("ValidateRFCPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C4400: INCONVENIENTE CON SU NÚMERO DE SERVICIO
        ///Su número de servicio presenta algún inconveniente, el número de servicio se reportará para corregirlo..
        /// </summary>
        internal static string WithOutState {
            get {
                return ResourceManager.GetString("WithOutState", resourceCulture);
            }
        }
    }
}
