/****** Object:  Table [dbo].[ArchivoXUsuario]    Script Date: 13/09/2016 11:35:34 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ArchivoXUsuario](
	[ID] [int] NOT NULL IDENTITY(1,1),
	[ID_ARCHIVO] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	CONSTRAINT PK_ArchivoXUsuario PRIMARY KEY([ID_ARCHIVO], [ID_USUARIO]),
	CONSTRAINT FK_ARCHIVO FOREIGN KEY ([ID_ARCHIVO]) REFERENCES Archivos(id),
	CONSTRAINT FK_USUARIO FOREIGN KEY ([ID_USUARIO]) REFERENCES Usuario(idUsuario)
) 


GO

SET ANSI_PADDING OFF
GO

