 CREATE TABLE dbo.SSISTABLEFAMILIAS
(
    ID_FAMILIAS int primary key, 
    TITULO Varchar(MAX), 
    CREADOR Varchar(MAX), 
    FECHA_CREACION DatetIme, 
    FA_NOMBRE Varchar(max),
    TITULODETALLE Varchar(max)
)

CREATE TABLE dbo.SSISTABLEMARCAS
(
    ID_MARCAS int primary key, 
    TITULO Varchar(MAX), 
    CREADOR Varchar(MAX), 
    FECHA_CREACION DatetIme, 
    MA_NOMBRE Varchar(max),
    TITULODETALLE Varchar(max)
)

CREATE TABLE dbo.SSISTABLEDIVICIONES
(
    ID_DIVICIONES int primary key, 
    TITULO Varchar(MAX), 
    CREADOR Varchar(MAX), 
    FECHA_CREACION DatetIme, 
    DIV_NOMBRE Varchar(max),
    TITULODETALLE Varchar(max)
)

CREATE TABLE dbo.SSISTABLEPRODUCTOS
(
	ID_PRODUCTOS INT PRIMARY KEY,
	TITULO VARCHAR(MAX),
	CREADOR VARCHAR(MAX),
	FECHA_CREACION DATETIME,
	PR_CODBAR VARCHAR(MAX),
	PR_NOMBRE VARCHAR(MAX),
	PR_MODELO VARCHAR(MAX),
	PR_OBSERVACIONES VARCHAR(MAX),
	PR_HAYSERIES BIT,
	PR_REPARABLE BIT,
	ID_MARCAS INT,
	ID_DIVISIONES INT,
	ID_FAMILIAS INT,
	TITULODETALLE VARCHAR(MAX),
	PR_VALSERIE VARCHAR (MAX),
	PR_FECVENTA DATETIME
)

--DROP TABLE SSISTABLEFAMILIAS
--DROP TABLE SSISTABLEMARCAS
--DROP TABLE SSISTABLEDIVICIONES

--SELECT * FROM SSISTABLEFAMILIAS
--SELECT * FROM SSISTABLEMARCAS
--SELECT * FROM SSISTABLEDIVICIONES