SELECT P.PR_MODELO, M.MA_NOMBRE, D.DIV_NOMBRE, F.FA_NOMBRE 
FROM PRODUCTOS AS P 
INNER JOIN MARCAS AS M ON P.ID_MARCAS = M.ID_MARCAS
INNER JOIN DIVISIONES AS D ON P.ID_DIVISIONES = D.ID_DIVISIONES
INNER JOIN FAMILIAS AS F ON P.ID_FAMILIAS= F.ID_FAMILIAS 
GROUP BY PR_MODELO, M.MA_NOMBRE, D.DIV_NOMBRE,F.FA_NOMBRE 
ORDER BY M.MA_NOMBRE ,D.DIV_NOMBRE, F.FA_NOMBRE

SELECT * FROM PRODUCTOS

SELECT P.*,VP.*,IVP.* FROM ID_VTPRODS AS IVP
INNER JOIN VTPRODUCTOS AS VP ON IVP.ID_VTPRODUCTOS = VP.ID_VTPRODUCTOS
INNER JOIN PRODUCTOS AS P ON IVP.ID_PRODUCTOS = P.ID_PRODUCTOS

SELECT
 V.VE_NOMBRE,
 T.TI_NOMBRE,
 P.PR_NOMBRE,
 P.PR_MODELO,
 M.MA_NOMBRE,
 F.FA_NOMBRE
 FROM VTPRODUCTOS AS VP
INNER JOIN VENDEDORES AS V ON V.ID_VENDEDORES = VP.ID_VENDEDORES
INNER JOIN TIENDAS AS T ON T.ID_TIENDAS = VP.ID_TIENDAS
INNER JOIN ID_VTPRODS AS IVTP ON IVTP.ID_PRODUCTOS = vp.ID_VTPRODUCTOS
INNER JOIN PRODUCTOS AS P ON IVTP.ID_PRODUCTOS = P.ID_PRODUCTOS
INNER JOIN MARCAS AS M ON P.ID_MARCAS = M.ID_MARCAS
INNER JOIN FAMILIAS AS F ON P.ID_FAMILIAS = F.ID_FAMILIAS
WHERE
--V.ID_VENDEDORES = 1
M.MA_NOMBRE = 'AIWA' 
ORDER BY 
--V.VE_NOMBRE
M.MA_NOMBRE

SELECT * FROM MON_SUCS
SELECT * FROM TIENDAS
SELECT * FROM SUCURSALES
SELECT * FROM SUCS_USUARIOS