USE [Suncorp]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create PROCEDURE [dbo].[ETLInsertCatalogsMarcas]
	@ID_MARCAS int
    ,@TITULO Varchar(MAX)
	,@CREADOR Varchar(MAX)
	,@FECHA_CREACION Varchar(MAX)
	,@MA_NOMBRE Varchar(MAX)
	,@TITULODETALLE Varchar(MAX)
AS
BEGIN
  SET NOCOUNT ON;


INSERT INTO SSISTABLEMARCAS (ID_MARCAS, TITULO, CREADOR, FECHA_CREACION, MA_NOMBRE,TITULODETALLE)
VALUES (@ID_MARCAS, @TITULO, @CREADOR, @FECHA_CREACION, @MA_NOMBRE, @TITULODETALLE)


END