USE [Suncorp]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ETLInsertCatalogsProductos]
	@ID_PRODUCTOS INT,
	@TITULO VARCHAR(MAX),
	@CREADOR VARCHAR(MAX),
	@FECHA_CREACION VARCHAR(MAX),
	@PR_CODBAR VARCHAR(MAX),
	@PR_NOMBRE VARCHAR(MAX),
	@PR_MODELO VARCHAR(MAX),
	@PR_OBSERVACIONES VARCHAR(MAX),
	@PR_HAYSERIES VARCHAR(MAX),
	@PR_REPARABLE VARCHAR(MAX),
	@ID_MARCAS INT,
	@ID_DIVISIONES INT,
	@ID_FAMILIAS INT,
	@TITULODETALLE VARCHAR(MAX),
	@PR_VALSERIE VARCHAR (MAX),
	@PR_FECVENTA VARCHAR(MAX)
AS
BEGIN
  SET NOCOUNT ON;

INSERT INTO SSISTABLEPRODUCTOS (ID_PRODUCTOS, TITULO, CREADOR,FECHA_CREACION, PR_CODBAR, PR_NOMBRE, PR_MODELO, PR_OBSERVACIONES, PR_HAYSERIES, PR_REPARABLE, ID_MARCAS, ID_DIVISIONES, ID_FAMILIAS, TITULODETALLE, PR_VALSERIE, PR_FECVENTA)
VALUES (@ID_PRODUCTOS, @TITULO,	@CREADOR, @FECHA_CREACION, @PR_CODBAR, @PR_NOMBRE, @PR_MODELO, @PR_OBSERVACIONES, @PR_HAYSERIES, @PR_REPARABLE, @ID_MARCAS, @ID_DIVISIONES,	@ID_FAMILIAS, @TITULODETALLE, @PR_VALSERIE,	@PR_FECVENTA)

END
