USE [Suncorp]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create PROCEDURE [dbo].[ETLInsertCatalogsDiviciones]
	@ID_DIVICIONES int
    ,@TITULO Varchar(MAX)
	,@CREADOR Varchar(MAX)
	,@FECHA_CREACION Varchar(MAX)
	,@DIV_NOMBRE Varchar(MAX)
	,@TITULODETALLE Varchar(MAX)
AS
BEGIN
  SET NOCOUNT ON;


INSERT INTO SSISTABLEDIVICIONES (ID_DIVICIONES, TITULO, CREADOR, FECHA_CREACION, DIV_NOMBRE,TITULODETALLE)
VALUES (@ID_DIVICIONES, @TITULO, @CREADOR, @FECHA_CREACION, @DIV_NOMBRE, @TITULODETALLE)


END