//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Entidades
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    
    [DataContract]
    public partial class CAL_ALUMNO_KARDEX
    
    {
    
    	[DataMember]
        public int IDKARDEX { get; set; }
    
    
    	[DataMember]
        public Nullable<int> IDALUMNOS { get; set; }
    
    
    	[DataMember]
        public Nullable<int> IDCALIFICACION { get; set; }
    
    
    	[DataMember]
        public Nullable<short> IDCARRERA { get; set; }
    
    
        public virtual ALU_ALUMNOS ALU_ALUMNOS { get; set; }
        public virtual CAL_CALIFICACIONES CAL_CALIFICACIONES { get; set; }
        public virtual CAR_CAT_CARRERAS CAR_CAT_CARRERAS { get; set; }
    }
}
