//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


[DataContract]
public partial class PER_MEDIOS_ELECTRONICOS

{
    public PER_MEDIOS_ELECTRONICOS()
    {
        this.PER_PERSONAS = new HashSet<PER_PERSONAS>();
    }


	[DataMember]
    public int ID_MEDIOS_ELECTRONICOS { get; set; }


	[DataMember]
    public string CORREO_ELECTRONICO_UNIVERSIDAD { get; set; }


	[DataMember]
    public string CORREO_ELECTRONICO_PERSONAL { get; set; }


	[DataMember]
    public string FACEBOOK { get; set; }


	[DataMember]
    public string TWITTER { get; set; }


    public virtual ICollection<PER_PERSONAS> PER_PERSONAS { get; set; }
}
