/****** Object:  Table [dbo].[atEstatusPagos]    Script Date: 10/11/2016 11:00:00 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CatEstatusPagos](
	[ID_ESTATUS] [INT] IDENTITY(1,1) NOT NULL,
	[CV_ESTATUS_PAGO] [VARCHAR](15) NOT NULL
 CONSTRAINT [PK_CatEstatusPagos] PRIMARY KEY CLUSTERED 
(
	[ID_ESTATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


