//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsRespuestaRegSol", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WsRespuestaRegSol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSidMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSFolioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WSidMensaje {
            get {
                return this.WSidMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSidMensajeField, value) != true)) {
                    this.WSidMensajeField = value;
                    this.RaisePropertyChanged("WSidMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WSMensaje {
            get {
                return this.WSMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSMensajeField, value) != true)) {
                    this.WSMensajeField = value;
                    this.RaisePropertyChanged("WSMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WSCredito {
            get {
                return this.WSCreditoField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCreditoField, value) != true)) {
                    this.WSCreditoField = value;
                    this.RaisePropertyChanged("WSCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WSFolio {
            get {
                return this.WSFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.WSFolioField, value) != true)) {
                    this.WSFolioField = value;
                    this.RaisePropertyChanged("WSFolio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsRespuestaRegTarjeta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WsRespuestaRegTarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSidMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSEntidadFinancieraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WSidMensaje {
            get {
                return this.WSidMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSidMensajeField, value) != true)) {
                    this.WSidMensajeField = value;
                    this.RaisePropertyChanged("WSidMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string WSMensaje {
            get {
                return this.WSMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSMensajeField, value) != true)) {
                    this.WSMensajeField = value;
                    this.RaisePropertyChanged("WSMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WSEntidadFinanciera {
            get {
                return this.WSEntidadFinancieraField;
            }
            set {
                if ((object.ReferenceEquals(this.WSEntidadFinancieraField, value) != true)) {
                    this.WSEntidadFinancieraField = value;
                    this.RaisePropertyChanged("WSEntidadFinanciera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSo" +
        "ap")]
    public interface WSRegistraSolicitudCreditoMejoravitAppSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NSS del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraSolicitud", ReplyAction="*")]
        PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudResponse RegistraSolicitud(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NSS del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraSolicitudTarjeta", ReplyAction="*")]
        PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaResponse RegistraSolicitudTarjeta(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraSolicitudRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraSolicitud", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequestBody Body;
        
        public RegistraSolicitudRequest() {
        }
        
        public RegistraSolicitudRequest(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistraSolicitudRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NSS;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreTitular;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Plazo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Contarias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MontoCredito;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PagoMensual;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MontoManoObra;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PensionAlimenticia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string GastosApertura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NumRegistroPatronal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PuntMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PuntTotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Curp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string RFC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string NombreEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string TipoIdentificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string NumeroIdentificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string FechaValidez;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CveCentralObrera;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string DescCentralObrera;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string LadaEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string TelEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ExtEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Calle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string NumInt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string NumeExt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string cveEdo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string EdoDesc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string cveMun;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string MunDesc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string Colonia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string CP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string Sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string EstadoCivil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string RegCNY;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string Lada;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string LadaCelular;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string Celular;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string CorreoElectronico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string ApellidoPaternoR1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string ApellidoMaternoR1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string NombreR1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string CelularR1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string LadaR1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string TelefonoR1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string ApellidoPaternoR2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string ApellidoMaternoR2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string NombreR2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string CelularR2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string LadaR2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string TelefonoR2;
        
        public RegistraSolicitudRequestBody() {
        }
        
        public RegistraSolicitudRequestBody(
                    string NSS, 
                    string usuario, 
                    string NombreTitular, 
                    string Plazo, 
                    string Contarias, 
                    string MontoCredito, 
                    string PagoMensual, 
                    string MontoManoObra, 
                    string PensionAlimenticia, 
                    string GastosApertura, 
                    string NumRegistroPatronal, 
                    string PuntMin, 
                    string PuntTotal, 
                    string Curp, 
                    string RFC, 
                    string NombreEmpresa, 
                    string TipoIdentificacion, 
                    string NumeroIdentificacion, 
                    string FechaValidez, 
                    string CveCentralObrera, 
                    string DescCentralObrera, 
                    string LadaEmpresa, 
                    string TelEmpresa, 
                    string ExtEmpresa, 
                    string Calle, 
                    string NumInt, 
                    string NumeExt, 
                    string cveEdo, 
                    string EdoDesc, 
                    string cveMun, 
                    string MunDesc, 
                    string Colonia, 
                    string CP, 
                    string Sexo, 
                    string EstadoCivil, 
                    string RegCNY, 
                    string Lada, 
                    string Telefono, 
                    string LadaCelular, 
                    string Celular, 
                    string CorreoElectronico, 
                    string ApellidoPaternoR1, 
                    string ApellidoMaternoR1, 
                    string NombreR1, 
                    string CelularR1, 
                    string LadaR1, 
                    string TelefonoR1, 
                    string ApellidoPaternoR2, 
                    string ApellidoMaternoR2, 
                    string NombreR2, 
                    string CelularR2, 
                    string LadaR2, 
                    string TelefonoR2) {
            this.NSS = NSS;
            this.usuario = usuario;
            this.NombreTitular = NombreTitular;
            this.Plazo = Plazo;
            this.Contarias = Contarias;
            this.MontoCredito = MontoCredito;
            this.PagoMensual = PagoMensual;
            this.MontoManoObra = MontoManoObra;
            this.PensionAlimenticia = PensionAlimenticia;
            this.GastosApertura = GastosApertura;
            this.NumRegistroPatronal = NumRegistroPatronal;
            this.PuntMin = PuntMin;
            this.PuntTotal = PuntTotal;
            this.Curp = Curp;
            this.RFC = RFC;
            this.NombreEmpresa = NombreEmpresa;
            this.TipoIdentificacion = TipoIdentificacion;
            this.NumeroIdentificacion = NumeroIdentificacion;
            this.FechaValidez = FechaValidez;
            this.CveCentralObrera = CveCentralObrera;
            this.DescCentralObrera = DescCentralObrera;
            this.LadaEmpresa = LadaEmpresa;
            this.TelEmpresa = TelEmpresa;
            this.ExtEmpresa = ExtEmpresa;
            this.Calle = Calle;
            this.NumInt = NumInt;
            this.NumeExt = NumeExt;
            this.cveEdo = cveEdo;
            this.EdoDesc = EdoDesc;
            this.cveMun = cveMun;
            this.MunDesc = MunDesc;
            this.Colonia = Colonia;
            this.CP = CP;
            this.Sexo = Sexo;
            this.EstadoCivil = EstadoCivil;
            this.RegCNY = RegCNY;
            this.Lada = Lada;
            this.Telefono = Telefono;
            this.LadaCelular = LadaCelular;
            this.Celular = Celular;
            this.CorreoElectronico = CorreoElectronico;
            this.ApellidoPaternoR1 = ApellidoPaternoR1;
            this.ApellidoMaternoR1 = ApellidoMaternoR1;
            this.NombreR1 = NombreR1;
            this.CelularR1 = CelularR1;
            this.LadaR1 = LadaR1;
            this.TelefonoR1 = TelefonoR1;
            this.ApellidoPaternoR2 = ApellidoPaternoR2;
            this.ApellidoMaternoR2 = ApellidoMaternoR2;
            this.NombreR2 = NombreR2;
            this.CelularR2 = CelularR2;
            this.LadaR2 = LadaR2;
            this.TelefonoR2 = TelefonoR2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraSolicitudResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraSolicitudResponse", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudResponseBody Body;
        
        public RegistraSolicitudResponse() {
        }
        
        public RegistraSolicitudResponse(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistraSolicitudResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WsRespuestaRegSol RegistraSolicitudResult;
        
        public RegistraSolicitudResponseBody() {
        }
        
        public RegistraSolicitudResponseBody(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WsRespuestaRegSol RegistraSolicitudResult) {
            this.RegistraSolicitudResult = RegistraSolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraSolicitudTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraSolicitudTarjeta", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequestBody Body;
        
        public RegistraSolicitudTarjetaRequest() {
        }
        
        public RegistraSolicitudTarjetaRequest(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistraSolicitudTarjetaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NSS;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroTarjeta;
        
        public RegistraSolicitudTarjetaRequestBody() {
        }
        
        public RegistraSolicitudTarjetaRequestBody(string NSS, string usuario, string NumeroTarjeta) {
            this.NSS = NSS;
            this.usuario = usuario;
            this.NumeroTarjeta = NumeroTarjeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraSolicitudTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraSolicitudTarjetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaResponseBody Body;
        
        public RegistraSolicitudTarjetaResponse() {
        }
        
        public RegistraSolicitudTarjetaResponse(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistraSolicitudTarjetaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WsRespuestaRegTarjeta RegistraSolicitudTarjetaResult;
        
        public RegistraSolicitudTarjetaResponseBody() {
        }
        
        public RegistraSolicitudTarjetaResponseBody(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WsRespuestaRegTarjeta RegistraSolicitudTarjetaResult) {
            this.RegistraSolicitudTarjetaResult = RegistraSolicitudTarjetaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSRegistraSolicitudCreditoMejoravitAppSoapChannel : PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRegistraSolicitudCreditoMejoravitAppSoapClient : System.ServiceModel.ClientBase<PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap>, PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap {
        
        public WSRegistraSolicitudCreditoMejoravitAppSoapClient() {
        }
        
        public WSRegistraSolicitudCreditoMejoravitAppSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRegistraSolicitudCreditoMejoravitAppSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRegistraSolicitudCreditoMejoravitAppSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRegistraSolicitudCreditoMejoravitAppSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudResponse PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap.RegistraSolicitud(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequest request) {
            return base.Channel.RegistraSolicitud(request);
        }
        
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WsRespuestaRegSol RegistraSolicitud(
                    string NSS, 
                    string usuario, 
                    string NombreTitular, 
                    string Plazo, 
                    string Contarias, 
                    string MontoCredito, 
                    string PagoMensual, 
                    string MontoManoObra, 
                    string PensionAlimenticia, 
                    string GastosApertura, 
                    string NumRegistroPatronal, 
                    string PuntMin, 
                    string PuntTotal, 
                    string Curp, 
                    string RFC, 
                    string NombreEmpresa, 
                    string TipoIdentificacion, 
                    string NumeroIdentificacion, 
                    string FechaValidez, 
                    string CveCentralObrera, 
                    string DescCentralObrera, 
                    string LadaEmpresa, 
                    string TelEmpresa, 
                    string ExtEmpresa, 
                    string Calle, 
                    string NumInt, 
                    string NumeExt, 
                    string cveEdo, 
                    string EdoDesc, 
                    string cveMun, 
                    string MunDesc, 
                    string Colonia, 
                    string CP, 
                    string Sexo, 
                    string EstadoCivil, 
                    string RegCNY, 
                    string Lada, 
                    string Telefono, 
                    string LadaCelular, 
                    string Celular, 
                    string CorreoElectronico, 
                    string ApellidoPaternoR1, 
                    string ApellidoMaternoR1, 
                    string NombreR1, 
                    string CelularR1, 
                    string LadaR1, 
                    string TelefonoR1, 
                    string ApellidoPaternoR2, 
                    string ApellidoMaternoR2, 
                    string NombreR2, 
                    string CelularR2, 
                    string LadaR2, 
                    string TelefonoR2) {
            PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequest inValue = new PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequest();
            inValue.Body = new PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudRequestBody();
            inValue.Body.NSS = NSS;
            inValue.Body.usuario = usuario;
            inValue.Body.NombreTitular = NombreTitular;
            inValue.Body.Plazo = Plazo;
            inValue.Body.Contarias = Contarias;
            inValue.Body.MontoCredito = MontoCredito;
            inValue.Body.PagoMensual = PagoMensual;
            inValue.Body.MontoManoObra = MontoManoObra;
            inValue.Body.PensionAlimenticia = PensionAlimenticia;
            inValue.Body.GastosApertura = GastosApertura;
            inValue.Body.NumRegistroPatronal = NumRegistroPatronal;
            inValue.Body.PuntMin = PuntMin;
            inValue.Body.PuntTotal = PuntTotal;
            inValue.Body.Curp = Curp;
            inValue.Body.RFC = RFC;
            inValue.Body.NombreEmpresa = NombreEmpresa;
            inValue.Body.TipoIdentificacion = TipoIdentificacion;
            inValue.Body.NumeroIdentificacion = NumeroIdentificacion;
            inValue.Body.FechaValidez = FechaValidez;
            inValue.Body.CveCentralObrera = CveCentralObrera;
            inValue.Body.DescCentralObrera = DescCentralObrera;
            inValue.Body.LadaEmpresa = LadaEmpresa;
            inValue.Body.TelEmpresa = TelEmpresa;
            inValue.Body.ExtEmpresa = ExtEmpresa;
            inValue.Body.Calle = Calle;
            inValue.Body.NumInt = NumInt;
            inValue.Body.NumeExt = NumeExt;
            inValue.Body.cveEdo = cveEdo;
            inValue.Body.EdoDesc = EdoDesc;
            inValue.Body.cveMun = cveMun;
            inValue.Body.MunDesc = MunDesc;
            inValue.Body.Colonia = Colonia;
            inValue.Body.CP = CP;
            inValue.Body.Sexo = Sexo;
            inValue.Body.EstadoCivil = EstadoCivil;
            inValue.Body.RegCNY = RegCNY;
            inValue.Body.Lada = Lada;
            inValue.Body.Telefono = Telefono;
            inValue.Body.LadaCelular = LadaCelular;
            inValue.Body.Celular = Celular;
            inValue.Body.CorreoElectronico = CorreoElectronico;
            inValue.Body.ApellidoPaternoR1 = ApellidoPaternoR1;
            inValue.Body.ApellidoMaternoR1 = ApellidoMaternoR1;
            inValue.Body.NombreR1 = NombreR1;
            inValue.Body.CelularR1 = CelularR1;
            inValue.Body.LadaR1 = LadaR1;
            inValue.Body.TelefonoR1 = TelefonoR1;
            inValue.Body.ApellidoPaternoR2 = ApellidoPaternoR2;
            inValue.Body.ApellidoMaternoR2 = ApellidoMaternoR2;
            inValue.Body.NombreR2 = NombreR2;
            inValue.Body.CelularR2 = CelularR2;
            inValue.Body.LadaR2 = LadaR2;
            inValue.Body.TelefonoR2 = TelefonoR2;
            PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudResponse retVal = ((PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap)(this)).RegistraSolicitud(inValue);
            return retVal.Body.RegistraSolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaResponse PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap.RegistraSolicitudTarjeta(PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequest request) {
            return base.Channel.RegistraSolicitudTarjeta(request);
        }
        
        public PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WsRespuestaRegTarjeta RegistraSolicitudTarjeta(string NSS, string usuario, string NumeroTarjeta) {
            PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequest inValue = new PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequest();
            inValue.Body = new PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaRequestBody();
            inValue.Body.NSS = NSS;
            inValue.Body.usuario = usuario;
            inValue.Body.NumeroTarjeta = NumeroTarjeta;
            PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.RegistraSolicitudTarjetaResponse retVal = ((PubliPayments.Negocios.Originacion.WSRegistraSolicitudCreditoMejoravitApp11.WSRegistraSolicitudCreditoMejoravitAppSoap)(this)).RegistraSolicitudTarjeta(inValue);
            return retVal.Body.RegistraSolicitudTarjetaResult;
        }
    }
}
