/****************************************************************************
* Proyecto:				portal.publipayments.com
* Autor:				Laura Anayeli Dotor Mejia
* Fecha de creación:	14/10/2016
* Descripción:			Inserta/Actualiza los registros procesdos en el WS
*						Opcion 0: Error al procesar registro
*						Opcion 1: Respuesta correcta del ws
*****************************************************************************/
CREATE PROCEDURE [dbo].[InsUpdWSEnvio] (
@OPCION INT,
@ID_ORDEN INT,
@ID_VISITA INT,
@CV_CREDITO VARCHAR (15),
@FECHA_CAPTURA DATE,
@CV_RUTA VARCHAR (10),
@CV_DESPACHO VARCHAR (10),
@CV_USER NVARCHAR (100),
@CV_ALTER_USER VARCHAR (50),
@CV_ORIGEN VARCHAR (3),
@CV_MOVIL VARCHAR (50),
@NUM_MOV INT, 
@CV_REGISTRO VARCHAR (8000),
@ERROR VARCHAR(1000)
)
AS
BEGIN
	DECLARE 
		@NO_REGISTROS_CORRECTOS INT = 0,
		@NO_REGISTROS_INCORRECTOS INT = 0,
		@NO_MOVIMIENTOS INT = 0,
		@DIFERENCIA_DIA INT = 0,
		@FECHA_ULTIMO_REG DATE

	BEGIN TRY
		BEGIN TRAN RegistroEnvioWS

			IF(@OPCION = 0)
			BEGIN
				INSERT INTO WSErroresEnvio ( [ID_ORDEN], [ID_VISITA], [EDO_GESTION], [ERROR], [ENVIADO], [FECHA_ENVIADO], [FECHA_ALTA])
				VALUES(@ID_ORDEN, @ID_VISITA, @CV_ORIGEN, @ERROR, 0, NULL, GETDATE())

				IF NOT EXISTS(SELECT 1 FROM WSDatosErroresEnvio WITH (NOLOCK) WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND CV_ORIGEN = @CV_ORIGEN)
				BEGIN
			
					INSERT WSDatosErroresEnvio ([ID_ORDEN],	[ID_VISITA], [CV_CREDITO], [FECHA_CAPTURA], [CV_RUTA], [CV_DESPACHO], [CV_USER], [CV_ALTER_USER], [CV_ORIGEN], [CV_MOVIL], [NUM_MOV], [CV_REGISTRO]	) 
					VALUES (@ID_ORDEN, @ID_VISITA, @CV_CREDITO, @FECHA_CAPTURA, @CV_RUTA, @CV_DESPACHO, @CV_USER, @CV_ALTER_USER, @CV_ORIGEN, @CV_MOVIL, @NUM_MOV, @CV_REGISTRO	)

					SELECT @NO_REGISTROS_INCORRECTOS = TOTAL_ERROR FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA

					SET @NO_REGISTROS_INCORRECTOS = @NO_REGISTROS_INCORRECTOS + 1
				
					UPDATE WSTotalesEnvio SET TOTAL_ERROR = @NO_REGISTROS_INCORRECTOS WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
				END

				IF NOT EXISTS (SELECT 1 FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA)
				BEGIN
					INSERT INTO WSTotalesEnvio ([CV_RUTA], [TOTAL_ENVIADO],	[TOTAL_ERROR], [TOTAL_MOVIMIENTOS], [EDO_GESTION], [FECHA]) VALUES (@CV_RUTA, 0, 1, 0, @CV_ORIGEN, @FECHA_CAPTURA)
				END
				ELSE
				BEGIN				
					IF NOT EXISTS (SELECT 1 FROM WSErroresEnvio WITH (NOLOCK) WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND EDO_GESTION = @CV_ORIGEN)
					BEGIN
						SELECT @NO_REGISTROS_INCORRECTOS = TOTAL_ERROR FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA

						SET @NO_REGISTROS_INCORRECTOS = @NO_REGISTROS_INCORRECTOS + 1

						UPDATE WSTotalesEnvio SET TOTAL_ERROR = @NO_REGISTROS_INCORRECTOS WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
					END
				END
			END
			IF(@OPCION = 1)
			BEGIN
				IF NOT EXISTS (SELECT 1 FROM WSErroresEnvio WITH (NOLOCK) WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND EDO_GESTION = @CV_ORIGEN)
				BEGIN
					IF EXISTS (SELECT 1 FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA)
					BEGIN	
						SELECT @NO_REGISTROS_CORRECTOS = TOTAL_ENVIADO, @NO_MOVIMIENTOS = TOTAL_MOVIMIENTOS FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA

						SET @NO_REGISTROS_CORRECTOS = @NO_REGISTROS_CORRECTOS + 1
						SET @NO_MOVIMIENTOS = @NO_MOVIMIENTOS + @NUM_MOV
				
						UPDATE WSTotalesEnvio SET TOTAL_ENVIADO = @NO_REGISTROS_CORRECTOS, TOTAL_MOVIMIENTOS = @NO_MOVIMIENTOS WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
					END
					ELSE
					BEGIN
						INSERT INTO WSTotalesEnvio ([CV_RUTA], [TOTAL_ENVIADO],	[TOTAL_ERROR], [TOTAL_MOVIMIENTOS], [EDO_GESTION], [FECHA]) VALUES (@CV_RUTA, 1, 0, @NUM_MOV, @CV_ORIGEN, @FECHA_CAPTURA)
					END
				END
				ELSE
				BEGIN
					SELECT @FECHA_ULTIMO_REG = FECHA_ALTA FROM WSErroresEnvio WITH (NOLOCK) WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND EDO_GESTION = @CV_ORIGEN ORDER BY FECHA_ALTA DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

					SELECT @DIFERENCIA_DIA = DATEDIFF ( DAY , CONVERT (DATE, GETDATE()) , CONVERT (DATE, @FECHA_ULTIMO_REG) )

					IF(@DIFERENCIA_DIA = 0)
					BEGIN
						UPDATE WSErroresEnvio SET ENVIADO = 1, FECHA_ENVIADO = GETDATE() WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND EDO_GESTION = @CV_ORIGEN
						
						SELECT @NO_REGISTROS_CORRECTOS = TOTAL_ENVIADO, @NO_MOVIMIENTOS = TOTAL_MOVIMIENTOS FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
						SELECT @NO_REGISTROS_INCORRECTOS = TOTAL_ERROR FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA

						SET @NO_REGISTROS_CORRECTOS = @NO_REGISTROS_CORRECTOS + 1
						SET @NO_REGISTROS_INCORRECTOS = @NO_REGISTROS_INCORRECTOS - 1
						SET @NO_MOVIMIENTOS = @NO_MOVIMIENTOS + @NUM_MOV
				
						UPDATE WSTotalesEnvio SET TOTAL_ENVIADO = @NO_REGISTROS_CORRECTOS, TOTAL_MOVIMIENTOS = @NO_MOVIMIENTOS WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
						UPDATE WSTotalesEnvio SET TOTAL_ERROR = @NO_REGISTROS_INCORRECTOS WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
						
					END
					IF(@DIFERENCIA_DIA = -1)
					BEGIN
						IF EXISTS (SELECT 1 FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA)
						BEGIN	
							SELECT @NO_REGISTROS_CORRECTOS = TOTAL_ENVIADO, @NO_MOVIMIENTOS = TOTAL_MOVIMIENTOS FROM WSTotalesEnvio WITH(NOLOCK) WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA

							SET @NO_REGISTROS_CORRECTOS = @NO_REGISTROS_CORRECTOS + 1
							SET @NO_MOVIMIENTOS = @NO_MOVIMIENTOS + @NUM_MOV
				
							UPDATE WSTotalesEnvio SET TOTAL_ENVIADO = @NO_REGISTROS_CORRECTOS, TOTAL_MOVIMIENTOS = @NO_MOVIMIENTOS WHERE CV_RUTA = @CV_RUTA AND EDO_GESTION = @CV_ORIGEN AND FECHA = @FECHA_CAPTURA
							UPDATE WSErroresEnvio SET ENVIADO = 1, FECHA_ENVIADO = GETDATE() WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND EDO_GESTION = @CV_ORIGEN
						END
						ELSE
						BEGIN
							INSERT INTO WSTotalesEnvio ([CV_RUTA], [TOTAL_ENVIADO],	[TOTAL_ERROR], [TOTAL_MOVIMIENTOS], [EDO_GESTION], [FECHA]) VALUES (@CV_RUTA, 1, 0, @NUM_MOV, @CV_ORIGEN, @FECHA_CAPTURA)
							UPDATE WSErroresEnvio SET ENVIADO = 1, FECHA_ENVIADO = GETDATE() WHERE ID_ORDEN = @ID_ORDEN AND ID_VISITA = @ID_VISITA AND EDO_GESTION = @CV_ORIGEN
						END
					END
				END
			END
		COMMIT TRAN RegistroEnvioWS
		END TRY
		BEGIN CATCH
		SELECT ERROR_NUMBER() AS Codigo, ERROR_MESSAGE() AS Descripcion;
		ROLLBACK TRAN RegistroEnvioWS
	END CATCH
END
