SELECT PEO.EMPLOYEE_NUMBER PERSONA_LINK_ID
,PEO.FULL_NAME NOMBRE_COMPLETO
,CASE WHEN PEO.MIDDLE_NAMES IS NOT NULL THEN
TRIM(PEO.FIRST_NAME)||' '
||TRIM(PEO.MIDDLE_NAMES)
ELSE
TRIM(PEO.FIRST_NAME)
END NOMBRE
,PEO.LAST_NAME APATERNO
,PEO.PER_INFORMATION1 AMATERNO
,PEO.DATE_OF_BIRTH FECHA_NAC
,REPLACE(PEO.PER_INFORMATION2,'-','') RFC
,REPLACE(PEO.NATIONAL_IDENTIFIER,'-','') CURP
,PEO.PER_INFORMATION3 IMSS
,PEO.SEX SEXO
,PEO.NATIONALITY NACIONALIDAD
,POS.DATE_START FECHA_INGRESO
,POS.ACTUAL_TERMINATION_DATE FECHA_BAJA
,(select name from APPS.HR_ALL_ORGANIZATION_UNITS WHERE TYPE LIKE 'BRE_RH_04' and organization_id=HOUV.ATTRIBUTE1) CENTRO_DE_COSTOS
,O.NAME AREA
,'' DEPARTAMENTO
,PJ.NAME PUESTO
,PPG.GROUP_NAME GRUPO
,'' LINEA_PRODUCCION
,PEO.EMPLOYEE_NUMBER CLAVE_EMPL
,(SELECT min(NAME)
FROM APPS.HR_ALL_ORGANIZATION_UNITS_TL
WHERE ORGANIZATION_ID = NOD.ENTITY_ID
AND LANGUAGE = 'ESA') COMPANIA
,'' DIVISION
,PAY.PAYROLL_NAME TIPO_NOMINA
FROM APPS.PER_PEOPLE_F PEO
,APPS.PER_ASSIGNMENTS_F PAF
,APPS.PER_PERIODS_OF_SERVICE POS
,APPS.HR_ALL_ORGANIZATION_UNITS O
,APPS.PER_JOBS PJ
,APPS.PAY_PEOPLE_GROUPS PPG
,APPS.PAY_PAYROLLS_F PAY
,APPS.HR_SOFT_CODING_KEYFLEX SOFT
,APPS.PER_GEN_HIERARCHY_NODES NODH
,APPS.PER_GEN_HIERARCHY_NODES NOD
,APPS.hr_all_organization_units houv
,APPS.eclock_modif_emp ecl
WHERE 1=1
AND PAF.PERSON_ID = PEO.PERSON_ID
AND PAF.PERIOD_OF_SERVICE_ID = POS.PERIOD_OF_SERVICE_ID
AND PAF.ORGANIZATION_ID=HOUV.ORGANIZATION_ID
AND PAF.ORGANIZATION_ID=O.ORGANIZATION_ID
AND PPG.PEOPLE_GROUP_ID(+) = PAF.PEOPLE_GROUP_ID
AND PAY.PAYROLL_ID = PAF.PAYROLL_ID
AND PAF.JOB_ID=PJ.JOB_ID
AND PAF.SOFT_CODING_KEYFLEX_ID = SOFT.SOFT_CODING_KEYFLEX_ID
AND NODH.ENTITY_ID = SOFT.SEGMENT1
AND NOD.HIERARCHY_NODE_ID = NODH.PARENT_HIERARCHY_NODE_ID
AND NODH.NODE_TYPE = 'MX GRE'
AND NOD.NODE_TYPE = 'MX LEGAL EMPLOYER'
and ecl.clave_empl=PEO.EMPLOYEE_NUMBER
AND ecl.fecha_efectiva BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
AND ecl.fecha_efectiva BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE