--Consulta GRID

SELECT * FROM CAT_TECNOLOGIA

SELECT * FROM ABE_REGIONES_BIOCLIMATICAS


SELECT * FROM
	(SELECT M.IDREGION_BIOCLIMA,R.REGION, T.Cve_Tecnologia,Dx_Nombre_General,FD.FACTOR_DEGRADACION,
	CASE WHEN FD.MODIFICADO_POR IS NULL THEN FD.ADICIONADO_POR ELSE FD.MODIFICADO_POR END AS USUARIO
	  FROM CAT_TECNOLOGIA T 
	  JOIN FACTOR_DEGRADACION fD ON T.Cve_Tecnologia = FD.CVE_TECNOLOGIA
	  JOIN CAT_DELEG_MUNICIPIO M ON FD.Cve_Deleg_Municipio = M.Cve_Deleg_Municipio
	  JOIN ABE_REGIONES_BIOCLIMATICAS R ON M.IDREGION_BIOCLIMA = R.IDREGION_BIOCLIMA
  ) AS FACTOR
  WHERE IDREGION_BIOCLIMA = 1
  AND Cve_Tecnologia = 1
  GROUP BY IDREGION_BIOCLIMA,REGION, Cve_Tecnologia,Dx_Nombre_General,FACTOR_DEGRADACION,USUARIO
  ORDER BY IDREGION_BIOCLIMA,Cve_Tecnologia ASC

----------UPDATE------------
UPDATE FACTOR_DEGRADACION SET FACTOR_DEGRADACION = 2 
WHERE CVE_TECNOLOGIA = 2 
AND CVE_dELEG_MUNICIPIO 
IN (SELECT Cve_Deleg_Municipio 
	  FROM CAT_DELEG_MUNICIPIO 
	 WHERE IDREGION_BIOCLIMA = 1)
	 

 


