/****** Object:  Table [dbo].[WSErroresEnvio]    Script Date: 11/10/2016 12:05:15 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WSErroresEnvio](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[ID_ORDEN] [INT] NOT NULL,
	[ID_VISITA] [INT] NOT NULL,	
	[EDO_GESTION] [VARCHAR](3) NOT NULL,
	[ERROR] [VARCHAR](1000) NOT NULL,
	[ENVIADO] [BIT] NOT NULL,
	[FECHA_ENVIADO] [DATETIME],
	[FECHA_ALTA] [DATETIME] NOT NULL,
 CONSTRAINT [PK_WSErroresEnvio] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


ALTER TABLE [dbo].[WSErroresEnvio]  WITH CHECK ADD  CONSTRAINT [Ordenes_FK_idOrden] FOREIGN KEY([ID_ORDEN])
REFERENCES [dbo].[Ordenes] ([idOrden])
GO

ALTER TABLE [dbo].[WSErroresEnvio] CHECK CONSTRAINT [Ordenes_FK_idOrden]
GO

