//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubliPayments.Negocios.Originacion.SeguridadMejoravitApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsRespuestaAPP", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WsRespuestaAPP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool WSRespuestaAPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSidMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSNombreAsesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSAtributoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool WSRespuestaAPP {
            get {
                return this.WSRespuestaAPPField;
            }
            set {
                if ((this.WSRespuestaAPPField.Equals(value) != true)) {
                    this.WSRespuestaAPPField = value;
                    this.RaisePropertyChanged("WSRespuestaAPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WSidMensaje {
            get {
                return this.WSidMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSidMensajeField, value) != true)) {
                    this.WSidMensajeField = value;
                    this.RaisePropertyChanged("WSidMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WSMensaje {
            get {
                return this.WSMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSMensajeField, value) != true)) {
                    this.WSMensajeField = value;
                    this.RaisePropertyChanged("WSMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WSNombreAsesor {
            get {
                return this.WSNombreAsesorField;
            }
            set {
                if ((object.ReferenceEquals(this.WSNombreAsesorField, value) != true)) {
                    this.WSNombreAsesorField = value;
                    this.RaisePropertyChanged("WSNombreAsesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WSPerfil {
            get {
                return this.WSPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.WSPerfilField, value) != true)) {
                    this.WSPerfilField = value;
                    this.RaisePropertyChanged("WSPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WSAtributo {
            get {
                return this.WSAtributoField;
            }
            set {
                if ((object.ReferenceEquals(this.WSAtributoField, value) != true)) {
                    this.WSAtributoField = value;
                    this.RaisePropertyChanged("WSAtributo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap")]
    public interface WSSeguridadMejoravitAppSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IdUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiaContrasena", ReplyAction="*")]
        PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaResponse CambiaContrasena(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IdUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaUsuario", ReplyAction="*")]
        PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioResponse ValidaUsuario(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiaContrasenaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiaContrasena", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequestBody Body;
        
        public CambiaContrasenaRequest() {
        }
        
        public CambiaContrasenaRequest(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiaContrasenaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContrasenaNueva;
        
        public CambiaContrasenaRequestBody() {
        }
        
        public CambiaContrasenaRequestBody(string IdUsuario, string Contrasena, string ContrasenaNueva) {
            this.IdUsuario = IdUsuario;
            this.Contrasena = Contrasena;
            this.ContrasenaNueva = ContrasenaNueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiaContrasenaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiaContrasenaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaResponseBody Body;
        
        public CambiaContrasenaResponse() {
        }
        
        public CambiaContrasenaResponse(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiaContrasenaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WsRespuestaAPP CambiaContrasenaResult;
        
        public CambiaContrasenaResponseBody() {
        }
        
        public CambiaContrasenaResponseBody(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WsRespuestaAPP CambiaContrasenaResult) {
            this.CambiaContrasenaResult = CambiaContrasenaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaUsuario", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequestBody Body;
        
        public ValidaUsuarioRequest() {
        }
        
        public ValidaUsuarioRequest(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contrasena;
        
        public ValidaUsuarioRequestBody() {
        }
        
        public ValidaUsuarioRequestBody(string IdUsuario, string Contrasena) {
            this.IdUsuario = IdUsuario;
            this.Contrasena = Contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioResponseBody Body;
        
        public ValidaUsuarioResponse() {
        }
        
        public ValidaUsuarioResponse(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WsRespuestaAPP ValidaUsuarioResult;
        
        public ValidaUsuarioResponseBody() {
        }
        
        public ValidaUsuarioResponseBody(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WsRespuestaAPP ValidaUsuarioResult) {
            this.ValidaUsuarioResult = ValidaUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSeguridadMejoravitAppSoapChannel : PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSeguridadMejoravitAppSoapClient : System.ServiceModel.ClientBase<PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap>, PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap {
        
        public WSSeguridadMejoravitAppSoapClient() {
        }
        
        public WSSeguridadMejoravitAppSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSeguridadMejoravitAppSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSeguridadMejoravitAppSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSeguridadMejoravitAppSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaResponse PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap.CambiaContrasena(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequest request) {
            return base.Channel.CambiaContrasena(request);
        }
        
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WsRespuestaAPP CambiaContrasena(string IdUsuario, string Contrasena, string ContrasenaNueva) {
            PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequest inValue = new PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequest();
            inValue.Body = new PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaRequestBody();
            inValue.Body.IdUsuario = IdUsuario;
            inValue.Body.Contrasena = Contrasena;
            inValue.Body.ContrasenaNueva = ContrasenaNueva;
            PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.CambiaContrasenaResponse retVal = ((PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap)(this)).CambiaContrasena(inValue);
            return retVal.Body.CambiaContrasenaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioResponse PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap.ValidaUsuario(PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequest request) {
            return base.Channel.ValidaUsuario(request);
        }
        
        public PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WsRespuestaAPP ValidaUsuario(string IdUsuario, string Contrasena) {
            PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequest inValue = new PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequest();
            inValue.Body = new PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioRequestBody();
            inValue.Body.IdUsuario = IdUsuario;
            inValue.Body.Contrasena = Contrasena;
            PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.ValidaUsuarioResponse retVal = ((PubliPayments.Negocios.Originacion.SeguridadMejoravitApp.WSSeguridadMejoravitAppSoap)(this)).ValidaUsuario(inValue);
            return retVal.Body.ValidaUsuarioResult;
        }
    }
}
