//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int PKID { get; set; }
        public string USERNAME { get; set; }
        public string APPLICATIONNAME { get; set; }
        public string EMAIL { get; set; }
        public string COMMENT { get; set; }
        public string PASSWORD { get; set; }
        public string PASSWORDQUESTION { get; set; }
        public string PASSWORDANSWER { get; set; }
        public Nullable<bool> ISAPPROVED { get; set; }
        public Nullable<System.DateTime> LASTACTIVITYDATE { get; set; }
        public Nullable<System.DateTime> LASTLOGINDATE { get; set; }
        public Nullable<System.DateTime> LASTPASSWORDCHANGEDDATE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<bool> ISONLINE { get; set; }
        public Nullable<bool> ISLOCKEDOUT { get; set; }
        public Nullable<System.DateTime> LASTLOCKEDOUTDATE { get; set; }
        public Nullable<int> FAILEDPASSWORDATTEMPTCOUNT { get; set; }
        public Nullable<System.DateTime> FAILEDPASSWORDATTEMPTWINDOWSTART { get; set; }
        public Nullable<int> FAILEDPASSWORDANSWERATTEMPTCOUNT { get; set; }
        public Nullable<System.DateTime> FAILEDPASSWORDANSWERATTEMPTWINDOWSTART { get; set; }
        public Nullable<bool> ISSUBSCRIBER { get; set; }
        public string CUSTOMERID { get; set; }
    }
}
