//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubliPayments.Negocios.wsSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class SMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credenciales", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class Credenciales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enviado {
            get {
                return this.EnviadoField;
            }
            set {
                if ((this.EnviadoField.Equals(value) != true)) {
                    this.EnviadoField = value;
                    this.RaisePropertyChanged("Enviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioSMS", Namespace="https://www.broxel.com")]
    [System.SerializableAttribute()]
    public partial class ServicioSMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Valor0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Valor1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Valor2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Valor3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Valor4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor0 {
            get {
                return this.Valor0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor0Field, value) != true)) {
                    this.Valor0Field = value;
                    this.RaisePropertyChanged("Valor0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor1 {
            get {
                return this.Valor1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor1Field, value) != true)) {
                    this.Valor1Field = value;
                    this.RaisePropertyChanged("Valor1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor2 {
            get {
                return this.Valor2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor2Field, value) != true)) {
                    this.Valor2Field = value;
                    this.RaisePropertyChanged("Valor2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor3 {
            get {
                return this.Valor3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor3Field, value) != true)) {
                    this.Valor3Field = value;
                    this.RaisePropertyChanged("Valor3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor4 {
            get {
                return this.Valor4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor4Field, value) != true)) {
                    this.Valor4Field = value;
                    this.RaisePropertyChanged("Valor4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.broxel.com", ConfigurationName="wsSms.IServicioSMS")]
    public interface IServicioSMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IServicioSMS/EnviarSMS", ReplyAction="https://www.broxel.com/IServicioSMS/EnviarSMSResponse")]
        PubliPayments.Negocios.wsSms.Respuesta EnviarSMS(PubliPayments.Negocios.wsSms.SMS sms, PubliPayments.Negocios.wsSms.Credenciales credenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IServicioSMS/EnviarSMSC3ntro", ReplyAction="https://www.broxel.com/IServicioSMS/EnviarSMSC3ntroResponse")]
        PubliPayments.Negocios.wsSms.Respuesta EnviarSMSC3ntro(PubliPayments.Negocios.wsSms.SMS sms, PubliPayments.Negocios.wsSms.Credenciales credenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IServicioSMS/MultiSMSMismoMensaje", ReplyAction="https://www.broxel.com/IServicioSMS/MultiSMSMismoMensajeResponse")]
        PubliPayments.Negocios.wsSms.Respuesta[] MultiSMSMismoMensaje(string[] telefonos, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.broxel.com/IServicioSMS/MultiSMSMensajePersonalizado", ReplyAction="https://www.broxel.com/IServicioSMS/MultiSMSMensajePersonalizadoResponse")]
        PubliPayments.Negocios.wsSms.Respuesta[] MultiSMSMensajePersonalizado(PubliPayments.Negocios.wsSms.ServicioSMS[] smsPersonalizados, string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSMSChannel : PubliPayments.Negocios.wsSms.IServicioSMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSMSClient : System.ServiceModel.ClientBase<PubliPayments.Negocios.wsSms.IServicioSMS>, PubliPayments.Negocios.wsSms.IServicioSMS {
        
        public ServicioSMSClient() {
        }
        
        public ServicioSMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PubliPayments.Negocios.wsSms.Respuesta EnviarSMS(PubliPayments.Negocios.wsSms.SMS sms, PubliPayments.Negocios.wsSms.Credenciales credenciales) {
            return base.Channel.EnviarSMS(sms, credenciales);
        }
        
        public PubliPayments.Negocios.wsSms.Respuesta EnviarSMSC3ntro(PubliPayments.Negocios.wsSms.SMS sms, PubliPayments.Negocios.wsSms.Credenciales credenciales) {
            return base.Channel.EnviarSMSC3ntro(sms, credenciales);
        }
        
        public PubliPayments.Negocios.wsSms.Respuesta[] MultiSMSMismoMensaje(string[] telefonos, string mensaje) {
            return base.Channel.MultiSMSMismoMensaje(telefonos, mensaje);
        }
        
        public PubliPayments.Negocios.wsSms.Respuesta[] MultiSMSMensajePersonalizado(PubliPayments.Negocios.wsSms.ServicioSMS[] smsPersonalizados, string mensaje) {
            return base.Channel.MultiSMSMensajePersonalizado(smsPersonalizados, mensaje);
        }
    }
}
