/****** Object:  Table [dbo].[Pagos]    Script Date: 10/11/2016 12:20:00 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
DROP TABLE [dbo].[Pagos]
CREATE TABLE [dbo].[Pagos](
	[ID_ARCHIVO] [INT] NOT NULL,
	[CV_CREDITO] [VARCHAR](15) NOT NULL,
	[CV_ESTATUS_PAGO] [INT] NOT NULL,
	[NU_PAGO_MES_CORRIENTE] [INT] NOT NULL,
	[IM_PAGO_MES_CORRIENTE] [NUMERIC](10,2) NOT NULL,
	[TX_PAGO_MES_CORRIENTE] [VARCHAR](150) NOT NULL,
	[FECHA] [DATETIME] NOT NULL,
 CONSTRAINT [PK_Pagos] PRIMARY KEY CLUSTERED 
(
	[CV_CREDITO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


ALTER TABLE [dbo].[Pagos]  WITH CHECK ADD  CONSTRAINT [FK_Archivos_Pagos] FOREIGN KEY(ID_ARCHIVO)
REFERENCES [dbo].[Archivos] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Pagos] CHECK CONSTRAINT [FK_Archivos_Pagos]
GO


ALTER TABLE [dbo].[Pagos]  WITH CHECK ADD  CONSTRAINT [FK_CatEstatusPagos_Pagos] FOREIGN KEY([CV_ESTATUS_PAGO])
REFERENCES [dbo].[CatEstatusPagos] ([ID_ESTATUS])
GO

ALTER TABLE [dbo].[Pagos] CHECK CONSTRAINT [FK_CatEstatusPagos_Pagos]
GO
