/****** Object:  Table [dbo].[WSDatosErroresEnvio]    Script Date: 12/10/2016 11:05:15 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WSDatosErroresEnvio](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[ID_ORDEN] [INT] NOT NULL,
	[ID_VISITA] [INT] NOT NULL,		
	[CV_CREDITO] [VARCHAR](15) NOT NULL,
	[FECHA_CAPTURA] [DATETIME] NOT NULL,
	[CV_RUTA] [VARCHAR](10) NOT NULL,
	[CV_DESPACHO] [VARCHAR](10) NOT NULL,
	[CV_USER] [NVARCHAR](100) NOT NULL,
	[CV_ALTER_USER] [VARCHAR](50) NOT NULL,
	[CV_ORIGEN] [VARCHAR](3) NOT NULL,
	[CV_MOVIL] [VARCHAR](50) NOT NULL,
	[NUM_MOV] [INT] NOT NULL, 
	[CV_REGISTRO] [VARCHAR](8000) NOT NULL,
CONSTRAINT [PK_WSDatosErroresEnvio] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


ALTER TABLE [dbo].[WSDatosErroresEnvio]  WITH CHECK ADD  CONSTRAINT [FK_Ordenes_idOrden] FOREIGN KEY([ID_ORDEN])
REFERENCES [dbo].[Ordenes] ([idOrden])
GO

ALTER TABLE [dbo].[WSDatosErroresEnvio] CHECK CONSTRAINT [FK_Ordenes_idOrden]
GO