/****** Object:  Table [dbo].[WSTotalesEnvio]    Script Date: 11/10/2016 11:49:15 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WSTotalesEnvio](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[CV_RUTA] [VARCHAR](10) NOT NULL,
	[TOTAL_ENVIADO] [INT] NOT NULL,
	[TOTAL_ERROR] [INT] NOT NULL,
	[TOTAL_MOVIMIENTOS] [INT] NOT NULL,
	[EDO_GESTION] [VARCHAR](3) NOT NULL,
	[FECHA] [DATE] NOT NULL,
 CONSTRAINT [PK_WSTotalesEnvio] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
