/****** Object:  Table [dbo].[CatResultadoLlamadasSinExito]    Script Date: 03/11/2016 04:28:12 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CatResultadoLlamadasSinExito](
	[ID_RESULTADO] [INT] IDENTITY(1,1) NOT NULL,
	[RESULTADO] [VARCHAR](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_RESULTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LlamadasSinExito]  WITH CHECK ADD  CONSTRAINT [FK_CatResultado_LlamadasSinExito] FOREIGN KEY([ID_RESULTADO])
REFERENCES [dbo].[CatResultadoLlamadasSinExito] ([ID_RESULTADO])
GO

ALTER TABLE [dbo].[LlamadasSinExito] CHECK CONSTRAINT [FK_CatResultado_LlamadasSinExito]
GO
