GO
ALTER TABLE Creditos
ADD IN_SOLICITAR_SERVICIO_EMPLEO int
GO
ALTER TABLE Creditos
ADD TX_PORTAFOLIO varchar(200)

GO
ALTER TABLE BitacoraCreditos
ADD IN_SOLICITAR_SERVICIO_EMPLEO int
GO
ALTER TABLE BitacoraCreditos
ADD TX_PORTAFOLIO varchar(200)
