 function AceptaConfPr(){ if(ValC("AceptaConfPr", "No","==")){$("#AceptaConfPrFin").val("2");$("#AceptaConfPrFin").trigger("blur");}else{$("#AceptaConfPrFin").val("0");$("#AceptaConfPrFin").trigger("blur");}}
 function AceptaFPP(){ if(ValC("AceptaFPP", "No","==")){$("#AceptaFPPFin").val("2");$("#AceptaFPPFin").trigger("blur");}else{$("#AceptaFPPFin").val("0");$("#AceptaFPPFin").trigger("blur");}}
 function AceptaFPP1(){ if(ValC("AceptaFPP1", "No","==")){$("#AceptaFPP1Fin").val("0");$("#AceptaFPP1Fin").trigger("blur");}else{$("#AceptaFPP1Fin").val("1");$("#AceptaFPP1Fin").trigger("blur");}}
 function AceptaFPP2(){ if(ValC("AceptaFPP2", "No","==")){$("#AceptaFPP2Fin").val("0");$("#AceptaFPP2Fin").trigger("blur");}else{$("#AceptaFPP2Fin").val("1");$("#AceptaFPP2Fin").trigger("blur");}}
 function AceptaFPP3(){ if(ValC("AceptaFPP3", "No","==")){$("#AceptaFPP3Fin").val("0");$("#AceptaFPP3Fin").trigger("blur");}else{$("#AceptaFPP3Fin").val("1");$("#AceptaFPP3Fin").trigger("blur");}}
 function AceptaFPP4(){ if(ValC("AceptaFPP4", "No","==")){$("#AceptaFPP4Fin").val("0");$("#AceptaFPP4Fin").trigger("blur");}else{$("#AceptaFPP4Fin").val("1");$("#AceptaFPP4Fin").trigger("blur");}}
 function AceptaFPP5(){ if(ValC("AceptaFPP5", "No","==")){$("#AceptaFPP5Fin").val("0");$("#AceptaFPP5Fin").trigger("blur");}else{$("#AceptaFPP5Fin").val("1");$("#AceptaFPP5Fin").trigger("blur");}}
 function AceptaFPP6(){ if(ValC("AceptaFPP6", "No","==")){$("#AceptaFPP6Fin").val("0");$("#AceptaFPP6Fin").trigger("blur");}else{$("#AceptaFPP6Fin").val("1");$("#AceptaFPP6Fin").trigger("blur");}}
 function Acreditado(){ if(ValC("Acreditado", "No","==")){$("#AcreditadoFin").val("1");$("#AcreditadoFin").trigger("blur");}else{$("#AcreditadoFin").val("5");$("#AcreditadoFin").trigger("blur");}}
 function ActitudHostil(){ if(ValC("ActitudHostil", "No","==")){$("#ActitudHostilFin").val("1");$("#ActitudHostilFin").trigger("blur");}else{$("#ActitudHostilFin").val("3");$("#ActitudHostilFin").trigger("blur");}}
 function AplicaConfPr(){ if(ValC("AplicaConfPr", "No","==")){$("#AplicaConfPrFin").val("2");$("#AplicaConfPrFin").trigger("blur");}else{$("#AplicaConfPrFin").val("0");$("#AplicaConfPrFin").trigger("blur");}}
 function AplicaFPP(){ if(ValC("AplicaFPP", "No","==")){$("#AplicaFPPFin").val("2");$("#AplicaFPPFin").trigger("blur");}else{$("#AplicaFPPFin").val("0");$("#AplicaFPPFin").trigger("blur");}}
 function func_1_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'No','=='))&&(ValC('DomicilioCorrecto', 'No','=='))){Mostrar('DictamenNumeroEquivocado', true);}else{Mostrar('DictamenNumeroEquivocado',false);}}
 function func_10_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))){Mostrar('ConoceAcreditado', true);}else{Mostrar('ConoceAcreditado',false);}}
 function func_11_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'Si','=='))){Mostrar('NumeroContactoAV', true);Mostrar('HorarioContactoAV', true);Mostrar('NombreContestoAV', true);Mostrar('ParentescoAV', true);Mostrar('DictamenRecado', true);}else{Mostrar('NumeroContactoAV',false);Mostrar('HorarioContactoAV',false);Mostrar('NombreContestoAV',false);Mostrar('ParentescoAV',false);Mostrar('DictamenRecado',false);}}
 function func_12_194(){ if((ValC('Acreditado', 'No','=='))){Mostrar('AcreditadoVive', true);}else{Mostrar('AcreditadoVive',false);}}
 function func_13_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT1', 'Oficina','=='))){Mostrar('AgExtensionT1', true);}else{Mostrar('AgExtensionT1',false);}}
 function func_14_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT2', 'Oficina','=='))){Mostrar('AgExtensionT2', true);}else{Mostrar('AgExtensionT2',false);}}
 function func_15_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT3', 'Oficina','=='))){Mostrar('AgExtensionT3', true);}else{Mostrar('AgExtensionT3',false);}}
 function func_16_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT4', 'Oficina','=='))){Mostrar('AgExtensionT4', true);}else{Mostrar('AgExtensionT4',false);}}
 function func_17_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('AgTelefonos', 'Si','=='))){Mostrar('TelTipoAgT4', true);Mostrar('AgTelefonoT4', true);Mostrar('TelTipoAgT3', true);Mostrar('AgTelefonoT3', true);Mostrar('TelTipoAgT2', true);Mostrar('AgTelefonoT2', true);Mostrar('TelTipoAgT1', true);Mostrar('AgTelefonoT1', true);}else{Mostrar('TelTipoAgT4',false);Mostrar('AgTelefonoT4',false);Mostrar('TelTipoAgT3',false);Mostrar('AgTelefonoT3',false);Mostrar('TelTipoAgT2',false);Mostrar('AgTelefonoT2',false);Mostrar('TelTipoAgT1',false);Mostrar('AgTelefonoT1',false);}}
 function func_18_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','<='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('AceptaFPP', 'Si','=='))){Mostrar('InstrFPP2', true);Mostrar('FH_PROMESA_PAGOFPP', true);Mostrar('InstrFPP4', true);Mostrar('DictamenFPP', true);}else{Mostrar('InstrFPP2',false);Mostrar('FH_PROMESA_PAGOFPP',false);Mostrar('InstrFPP4',false);Mostrar('DictamenFPP',false);}}
 function func_19_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '1','=='))){Mostrar('AceptaFPP1', true);}else{Mostrar('AceptaFPP1',false);}}
 function func_2_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'No','=='))&&(ValC('DomicilioCorrecto', 'Si','=='))){Mostrar('DictamenHabitadaDesconocidos', true);}else{Mostrar('DictamenHabitadaDesconocidos',false);}}
 function func_20_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '1','>='))){Mostrar('TX_PAGA1', true);}else{Mostrar('TX_PAGA1',false);}}
 function func_21_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '2','=='))){Mostrar('AceptaFPP2', true);}else{Mostrar('AceptaFPP2',false);}}
 function func_22_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '2','>='))){Mostrar('TX_PAGA2', true);}else{Mostrar('TX_PAGA2',false);}}
 function func_23_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '3','=='))){Mostrar('AceptaFPP3', true);}else{Mostrar('AceptaFPP3',false);}}
 function func_24_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '3','>='))){Mostrar('TX_PAGA3', true);}else{Mostrar('TX_PAGA3',false);}}
 function func_25_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '4','=='))){Mostrar('AceptaFPP4', true);}else{Mostrar('AceptaFPP4',false);}}
 function func_26_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '4','>='))){Mostrar('TX_PAGA4', true);}else{Mostrar('TX_PAGA4',false);}}
 function func_27_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '5','=='))){Mostrar('AceptaFPP5', true);}else{Mostrar('AceptaFPP5',false);}}
 function func_28_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '5','>='))){Mostrar('TX_PAGA5', true);}else{Mostrar('TX_PAGA5',false);}}
 function func_29_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '6','=='))){Mostrar('AceptaFPP6', true);}else{Mostrar('AceptaFPP6',false);}}
 function func_3_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'No','=='))){Mostrar('DomicilioCorrecto', true);}else{Mostrar('DomicilioCorrecto',false);}}
 function func_30_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '6','>='))){Mostrar('TX_PAGA6', true);}else{Mostrar('TX_PAGA6',false);}}
 function func_31_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))){Mostrar('txtNCFPP', true);Mostrar('InstrFPP', true);Mostrar('NU_MESES_DISP_FPP', true);Mostrar('NU_MESES_RECUPERARFPP', true);Mostrar('InstrFPP7', true);Mostrar('CantidadPagos', true);}else{Mostrar('txtNCFPP',false);Mostrar('InstrFPP',false);Mostrar('NU_MESES_DISP_FPP',false);Mostrar('NU_MESES_RECUPERARFPP',false);Mostrar('InstrFPP7',false);Mostrar('CantidadPagos',false);}}
 function func_31_194xxx(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))){Mostrar('AceptaFPP', true);}else{Mostrar('AceptaFPP',false);}}
 function func_32_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','=='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('TotalizaD', '2','>='))&&(ValC('RealizoPago', 'Si','=='))){Mostrar('FechaPagoRealizado', true);}else{Mostrar('FechaPagoRealizado',false);}}
 function func_33_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','=='))&&(ValC('PromesaPago', 'Si','=='))){Mostrar('FechaPromesaPago', true);}else{Mostrar('FechaPromesaPago',false);}}
 function func_34_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('AplicaConfPr', 'Si','=='))&&(ValC('AceptaConfPr', 'Si','=='))&&(ValC('SelTipoProrroga', 'Parcial','=='))){Mostrar('DictamenCONFPRParcial', true);}else{Mostrar('DictamenCONFPRParcial',false);}}
 function func_35_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('AplicaConfPr', 'Si','=='))&&(ValC('AceptaConfPr', 'Si','=='))&&(ValC('SelTipoProrroga', 'Total','=='))){Mostrar('DictamenCONFPRTotal', true);}else{Mostrar('DictamenCONFPRTotal',false);}}
 function func_36_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('AplicaConfPr', 'Si','=='))&&(ValC('AceptaConfPr', 'Si','=='))){Mostrar('InstrFPR1', true);Mostrar('InstrFPR2', true);Mostrar('FechaInicioFPR', true);Mostrar('FechaConclusionFPR', true);Mostrar('SelTipoProrroga', true);}else{Mostrar('InstrFPR1',false);Mostrar('InstrFPR2',false);Mostrar('FechaInicioFPR',false);Mostrar('FechaConclusionFPR',false);Mostrar('SelTipoProrroga',false);}}
 function func_37_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('AplicaConfPr', 'Si','=='))){Mostrar('AceptaConfPr', true);Mostrar('InstacrednopromesaCONFPR', true);}else{Mostrar('AceptaConfPr',false);Mostrar('InstacrednopromesaCONFPR',false);}}
 function func_38_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('TotalizaD', '2','>='))&&(ValC('RealizoPago', 'No','=='))){Mostrar('DictamenNegativaPago', true);}else{Mostrar('DictamenNegativaPago',false);}}
 function func_39_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('TotalizaD', '2','>='))&&(ValC('RealizoPago', 'Si','=='))){Mostrar('DictamenPagoEfectuado', true);Mostrar('FolioPago', true);}else{Mostrar('DictamenPagoEfectuado',false);Mostrar('FolioPago',false);}}
 function func_4_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'No','=='))&&(ValC('AclaracionDefuncion', 'No','=='))){Mostrar('DictamenHabitadaTerceros', true);}else{Mostrar('DictamenHabitadaTerceros',false);}}
 function func_40_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('TotalizaD', '2','>='))){Mostrar('RealizoPago', true);}else{Mostrar('RealizoPago',false);}}
 function func_41_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('IM_MONTO_LIQUIDAR_CON_DESCUENTO', true);}else{Mostrar('IM_MONTO_LIQUIDAR_CON_DESCUENTO',false);}}
 function func_42_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('InstCantidad', true);Mostrar('ppagoMensualAct', true);}else{Mostrar('InstCantidad',false);Mostrar('ppagoMensualAct',false);}}
 function func_43_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('Instacredpagar', true);Mostrar('ppagoOmisosOms', true);}else{Mostrar('Instacredpagar',false);Mostrar('ppagoOmisosOms',false);}}
 function func_44_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))){Mostrar('TX_DESCRIPCION_ETIQUETA2', true);Mostrar('Insmontprom', true);Mostrar('montoPromesa', true);Mostrar('insSolacreprom', true);Mostrar('DictamenPromesaPago', true);}else{Mostrar('TX_DESCRIPCION_ETIQUETA2',false);Mostrar('Insmontprom',false);Mostrar('montoPromesa',false);Mostrar('insSolacreprom',false);Mostrar('DictamenPromesaPago',false);}}
 function func_45_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))){Mostrar('PromesaPago', true);}else{Mostrar('PromesaPago',false);}}
 function func_46_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))){Mostrar('NU_TELEFONO_CASA_ACT', true);Mostrar('CORROBNU_TELEFONO_CASA', true);Mostrar('NU_TELEFONO_CELULAR_ACT', true);Mostrar('CORROBNU_TELEFONO_CELULAR', true);Mostrar('NU_TELEFONO_TRABAJO_ACT', true);Mostrar('AgTelefonos', true);Mostrar('TX_CORREO_ELECTRONICO_ACT', true);Mostrar('TX_CALLE_ACT', true);Mostrar('TX_NU_CALLE_EXT_ACT', true);Mostrar('TX_NU_CALLE_INT_ACT', true);Mostrar('TX_EDIFICIO_ACT', true);Mostrar('TX_COLONIA_ACT', true);Mostrar('TX_MUNICIPIO_ACT', true);Mostrar('TX_ESTADO_ACT', true);Mostrar('CV_CODIGO_POSTAL_ACT', true);Mostrar('TX_ENTRE_CALLE1_ACT', true);Mostrar('TX_ENTRE_CALLE2_ACT', true);}else{Mostrar('NU_TELEFONO_CASA_ACT',false);Mostrar('CORROBNU_TELEFONO_CASA',false);Mostrar('NU_TELEFONO_CELULAR_ACT',false);Mostrar('CORROBNU_TELEFONO_CELULAR',false);Mostrar('NU_TELEFONO_TRABAJO_ACT',false);Mostrar('AgTelefonos',false);Mostrar('TX_CORREO_ELECTRONICO_ACT',false);Mostrar('TX_CALLE_ACT',false);Mostrar('TX_NU_CALLE_EXT_ACT',false);Mostrar('TX_NU_CALLE_INT_ACT',false);Mostrar('TX_EDIFICIO_ACT',false);Mostrar('TX_COLONIA_ACT',false);Mostrar('TX_MUNICIPIO_ACT',false);Mostrar('TX_ESTADO_ACT',false);Mostrar('CV_CODIGO_POSTAL_ACT',false);Mostrar('TX_ENTRE_CALLE1_ACT',false);Mostrar('TX_ENTRE_CALLE2_ACT',false);}}
 function func_47_194(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'Si','=='))){Mostrar('DictamenActitudHostil', true);}else{Mostrar('DictamenActitudHostil',false);}}
 function func_48_194(){ if((ValC('Acreditado', 'Si','=='))){Mostrar('ActitudHostil', true);}else{Mostrar('ActitudHostil',false);}}
 function func_49_194(){ if((ValC('LlamadaEntrada', 'No','=='))||(ValC('Contesta', 'Si','=='))){Mostrar('Acreditado', true);}else{Mostrar('Acreditado',false);}}
 function func_5_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'No','=='))&&(ValC('AclaracionDefuncion', 'Si','=='))){Mostrar('DictamenDefuncion', true);}else{Mostrar('DictamenDefuncion',false);}}
 function func_50_194(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))&&(ValC('ClasificaLlamada', 'BV','=='))){Mostrar('DictamenBuzonVoz', true);}else{Mostrar('DictamenBuzonVoz',false);}}
 function func_51_194(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))&&(ValC('ClasificaLlamada', 'FS','=='))){Mostrar('DictamenFueraServicio', true);}else{Mostrar('DictamenFueraServicio',false);}}
 function func_52_194(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))&&(ValC('ClasificaLlamada', 'TL','=='))){Mostrar('DictamenNoContestan', true);}else{Mostrar('DictamenNoContestan',false);}}
 function func_53_194(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))){Mostrar('ClasificaLlamada', true);}else{Mostrar('ClasificaLlamada',false);}}
 function func_54_194(){ if((ValC('LlamadaEntrada', 'Si','=='))){Mostrar('Contesta', true);}else{Mostrar('Contesta',false);}}
 function func_55_194xxx(){ $('#TotalizaC').val(Calc('AceptaFPP1Fin+AceptaFPP2Fin+AceptaFPP3Fin+AceptaFPP4Fin+AceptaFPP5Fin+AceptaFPP6Fin'));}
 function func_56_194(){ $('#TotalizaA').val(Calc('AcreditadoFin+ActitudHostilFin'));}
 function func_57_194(){ $('#TotalizaD').val(Calc('AplicaConfPrFin+AceptaConfPrFin'));}
 function func_58_194xxx(){ $('#TotalizaB').val(Calc('AplicaFPPFin+AceptaFPPFin'));}
 function func_6_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'No','=='))){Mostrar('AclaracionDefuncion', true);}else{Mostrar('AclaracionDefuncion',false);}}
 function func_7_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'Si','=='))){Mostrar('ParentescoPL', true);Mostrar('DictamenRecado2', true);Mostrar('NumeroContactoPL', true);Mostrar('HorarioContactoPL', true);}else{Mostrar('ParentescoPL',false);Mostrar('DictamenRecado2',false);Mostrar('NumeroContactoPL',false);Mostrar('HorarioContactoPL',false);}}
 function func_8_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))){Mostrar('PuedeLocalizarlo', true);}else{Mostrar('PuedeLocalizarlo',false);}}
 function func_9_194(){ if((ValC('Acreditado', 'No','=='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))||(ValC('ConoceAcreditado', 'Si','=='))){Mostrar('NombreContestoPL', true);}else{Mostrar('NombreContestoPL',false);}}
 function FuncMTelefonos(){ if((ValC("reqAct", "Si","==") && ValC("AgTelefonos", "Si","=="))){Mostrar("TelTipoAgT1",true);Mostrar("AgTelefonoT1",true);Mostrar("TelTipoAgT2",true);Mostrar("AgTelefonoT2",true);Mostrar("TelTipoAgT3",true);Mostrar("AgTelefonoT3",true);Mostrar("TelTipoAgT4",true);Mostrar("AgTelefonoT4",true);}else{Mostrar("TelTipoAgT1",false);Mostrar("AgTelefonoT1",false);Mostrar("TelTipoAgT2",false);Mostrar("AgTelefonoT2",false);Mostrar("TelTipoAgT3",false);Mostrar("AgTelefonoT3",false);Mostrar("TelTipoAgT4",false);Mostrar("AgTelefonoT4",false);}}
 function TotalizaA(){ if(true){$("#TotalizaA").trigger("blur");}else{$("#TotalizaA").trigger("blur");}}
 function TotalizaB(){ if(true){$("#TotalizaB").trigger("blur");}else{$("#TotalizaB").trigger("blur");}}
 function TotalizaC(){ if(true){$("#TotalizaC").trigger("blur");}else{$("#TotalizaC").trigger("blur");}}
 function TotalizaD(){ if(true){$("#TotalizaD").trigger("blur");}else{$("#TotalizaD").trigger("blur");}}
