 function AceptaFPP(){ if(ValC("AceptaFPP", "No","==")){$("#AceptaFPPFin").val("2");$("#AceptaFPPFin").trigger("blur");}else{$("#AceptaFPPFin").val("0");$("#AceptaFPPFin").trigger("blur");}}
 function AceptaFPP1(){ if(ValC("AceptaFPP1", "No","==")){$("#AceptaFPP1Fin").val("0");$("#AceptaFPP1Fin").trigger("blur");}else{$("#AceptaFPP1Fin").val("1");$("#AceptaFPP1Fin").trigger("blur");}}
 function AceptaFPP2(){ if(ValC("AceptaFPP2", "No","==")){$("#AceptaFPP2Fin").val("0");$("#AceptaFPP2Fin").trigger("blur");}else{$("#AceptaFPP2Fin").val("1");$("#AceptaFPP2Fin").trigger("blur");}}
 function AceptaFPP3(){ if(ValC("AceptaFPP3", "No","==")){$("#AceptaFPP3Fin").val("0");$("#AceptaFPP3Fin").trigger("blur");}else{$("#AceptaFPP3Fin").val("1");$("#AceptaFPP3Fin").trigger("blur");}}
 function AceptaFPP4(){ if(ValC("AceptaFPP4", "No","==")){$("#AceptaFPP4Fin").val("0");$("#AceptaFPP4Fin").trigger("blur");}else{$("#AceptaFPP4Fin").val("1");$("#AceptaFPP4Fin").trigger("blur");}}
 function AceptaFPP5(){ if(ValC("AceptaFPP5", "No","==")){$("#AceptaFPP5Fin").val("0");$("#AceptaFPP5Fin").trigger("blur");}else{$("#AceptaFPP5Fin").val("1");$("#AceptaFPP5Fin").trigger("blur");}}
 function AceptaFPP6(){ if(ValC("AceptaFPP6", "No","==")){$("#AceptaFPP6Fin").val("0");$("#AceptaFPP6Fin").trigger("blur");}else{$("#AceptaFPP6Fin").val("1");$("#AceptaFPP6Fin").trigger("blur");}}
 function Acreditado(){ if(ValC("Acreditado", "No","==")){$("#AcreditadoFin").val("5");$("#AcreditadoFin").trigger("blur");}else{$("#AcreditadoFin").val("1");$("#AcreditadoFin").trigger("blur");}}
 function ActitudHostil(){ if(ValC("ActitudHostil", "No","==")){$("#ActitudHostilFin").val("2");$("#DatosCorrectosFin").trigger("blur");}else{$("#ActitudHostilFin").val("0");$("#DatosCorrectosFin").trigger("blur");}}
 function AplicaFPP(){ if(ValC("AplicaFPP", "No","==")){$("#AplicaFPPFin").val("2");$("#AplicaFPPFin").trigger("blur");}else{$("#AplicaFPPFin").val("0");$("#AplicaFPPFin").trigger("blur");}}
 function DatosCorrectos(){ if(ValC("DatosCorrectos", "No","==")){$("#DatosCorrectosFin").val("5");$("#DatosCorrectosFin").trigger("blur");}else{$("#DatosCorrectosFin").val("1");$("#DatosCorrectosFin").trigger("blur");}}
 function func_1_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('AcreditadoFin', '1','=='))){Mostrar('ActitudHostil', true);}else{Mostrar('ActitudHostil',false);}}
 function func_10_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','<='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('AceptaFPP', 'Si','=='))){Mostrar('InstrFPP2', true);Mostrar('FH_PROMESA_PAGOFPP', true);Mostrar('InstrFPP4', true);Mostrar('DictamenFPP', true);}else{Mostrar('InstrFPP2',false);Mostrar('FH_PROMESA_PAGOFPP',false);Mostrar('InstrFPP4',false);Mostrar('DictamenFPP',false);}}
 function func_11_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '1','=='))){Mostrar('AceptaFPP1', true);}else{Mostrar('AceptaFPP1',false);}}
 function func_12_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '1','>='))){Mostrar('TX_PAGA1', true);}else{Mostrar('TX_PAGA1',false);}}
 function func_13_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '2','=='))){Mostrar('AceptaFPP2', true);}else{Mostrar('AceptaFPP2',false);}}
 function func_14_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '2','>='))){Mostrar('TX_PAGA2', true);}else{Mostrar('TX_PAGA2',false);}}
 function func_15_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '3','=='))){Mostrar('AceptaFPP3', true);}else{Mostrar('AceptaFPP3',false);}}
 function func_16_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '3','>='))){Mostrar('TX_PAGA3', true);}else{Mostrar('TX_PAGA3',false);}}
 function func_17_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '4','=='))){Mostrar('AceptaFPP4', true);}else{Mostrar('AceptaFPP4',false);}}
 function func_18_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '4','>='))){Mostrar('TX_PAGA4', true);}else{Mostrar('TX_PAGA4',false);}}
 function func_19_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '5','=='))){Mostrar('AceptaFPP5', true);}else{Mostrar('AceptaFPP5',false);}}
 function func_2_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))&&(ValC('reqAct', 'Si','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT1', 'Oficina','=='))){Mostrar('AgExtensionT1', true);}else{Mostrar('AgExtensionT1',false);}}
 function func_20_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '5','>='))){Mostrar('TX_PAGA5', true);}else{Mostrar('TX_PAGA5',false);}}
 function func_21_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '6','=='))){Mostrar('AceptaFPP6', true);}else{Mostrar('AceptaFPP6',false);}}
 function func_22_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))&&(ValC('CantidadPagos', '6','>='))){Mostrar('TX_PAGA6', true);}else{Mostrar('TX_PAGA6',false);}}
 function func_23_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))){Mostrar('txtNCFPP', true);Mostrar('InstrFPP', true);Mostrar('NU_MESES_DISP_FPP', true);Mostrar('NU_MESES_RECUPERARFPP', true);Mostrar('InstrFPP7', true);Mostrar('CantidadPagos', true);}else{Mostrar('txtNCFPP',false);Mostrar('InstrFPP',false);Mostrar('NU_MESES_DISP_FPP',false);Mostrar('NU_MESES_RECUPERARFPP',false);Mostrar('InstrFPP7',false);Mostrar('CantidadPagos',false);}}
 function func_23_144xxx(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('AplicaFPP', 'Si','=='))){Mostrar('AceptaFPP', true);}else{Mostrar('AceptaFPP',false);}}
 function func_24_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','=='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('RealizoPago', 'Si','=='))){Mostrar('FechaPagoRealizado', true);}else{Mostrar('FechaPagoRealizado',false);}}
 function func_25_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','=='))&&(ValC('PromesaPago', 'Si','=='))){Mostrar('FechaPromesaPago', true);}else{Mostrar('FechaPromesaPago',false);}}
 function func_26_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('RealizoPago', 'No','=='))&&(ValC('EsProrroga', 'No','=='))){Mostrar('DictamenNegativaPago', true);}else{Mostrar('DictamenNegativaPago',false);}}
 function func_27_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('RealizoPago', 'No','=='))&&(ValC('EsProrroga', 'Si','=='))){Mostrar('InsProrrogaSi', true);Mostrar('DictamenPagoProrroga', true);}else{Mostrar('InsProrrogaSi',false);Mostrar('DictamenPagoProrroga',false);}}
 function func_28_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('RealizoPago', 'No','=='))){Mostrar('EsProrroga', true);}else{Mostrar('EsProrroga',false);}}
 function func_29_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))&&(ValC('RealizoPago', 'Si','=='))){Mostrar('DictamenPagoEfectuado', true);Mostrar('FolioPago', true);}else{Mostrar('DictamenPagoEfectuado',false);Mostrar('FolioPago',false);}}
 function func_3_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))&&(ValC('reqAct', 'Si','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT2', 'Oficina','=='))){Mostrar('AgExtensionT2', true);}else{Mostrar('AgExtensionT2',false);}}
 function func_30_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'No','=='))){Mostrar('RealizoPago', true);}else{Mostrar('RealizoPago',false);}}
 function func_31_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('IM_MONTO_LIQUIDAR_CON_DESCUENTO', true);}else{Mostrar('IM_MONTO_LIQUIDAR_CON_DESCUENTO',false);}}
 function func_32_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('ppagoMensualAct', true);Mostrar('InstCantidad', true);}else{Mostrar('ppagoMensualAct',false);Mostrar('InstCantidad',false);}}
 function func_33_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('Instacredpagar', true);Mostrar('ppagoOmisosOms', true);}else{Mostrar('Instacredpagar',false);Mostrar('ppagoOmisosOms',false);}}
 function func_34_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))&&(ValC('PromesaPago', 'Si','=='))){Mostrar('insSolacreprom', true);Mostrar('DictamenPromesaPago', true);Mostrar('TX_DESCRIPCION_ETIQUETA2', true);Mostrar('Insmontprom', true);Mostrar('montoPromesa', true);}else{Mostrar('insSolacreprom',false);Mostrar('DictamenPromesaPago',false);Mostrar('TX_DESCRIPCION_ETIQUETA2',false);Mostrar('Insmontprom',false);Mostrar('montoPromesa',false);}}
 function func_35_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('TotalizaA', '6','=='))&&(ValC('TotalizaB', '2','>='))){Mostrar('PromesaPago', true);}else{Mostrar('PromesaPago',false);}}
 function func_36_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))){Mostrar('DatosCorrectos', true);}else{Mostrar('DatosCorrectos',false);}}
 function func_37_144(){ if((ValC('AcreditadoFin', '1','=='))&&(ValC('ActitudHostil', 'Si','=='))||(ValC('VerificarDatos', 'No','=='))){Mostrar('DictamenActitudHostil', true);}else{Mostrar('DictamenActitudHostil',false);}}
 function func_38_144(){ if((ValC('LlamadaEntrada', 'No','=='))||(ValC('Contesta', 'Si','=='))){Mostrar('Acreditado', true);}else{Mostrar('Acreditado',false);}}
 function func_39_144(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))&&(ValC('ClasificaLlamada', 'BV','=='))){Mostrar('DictamenBuzonVoz', true);}else{Mostrar('DictamenBuzonVoz',false);}}
 function func_4_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))&&(ValC('reqAct', 'Si','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT3', 'Oficina','=='))){Mostrar('AgExtensionT3', true);}else{Mostrar('AgExtensionT3',false);}}
 function func_40_144(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))&&(ValC('ClasificaLlamada', 'FS','=='))){Mostrar('DictamenFueraServicio', true);}else{Mostrar('DictamenFueraServicio',false);}}
 function func_41_144(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))&&(ValC('ClasificaLlamada', 'TL','=='))){Mostrar('DictamenNoContestan', true);}else{Mostrar('DictamenNoContestan',false);}}
 function func_42_144(){ if((ValC('LlamadaEntrada', 'Si','=='))&&(ValC('Contesta', 'No','=='))){Mostrar('ClasificaLlamada', true);}else{Mostrar('ClasificaLlamada',false);}}
 function func_43_144(){ if((ValC('LlamadaEntrada', 'Si','=='))){Mostrar('Contesta', true);}else{Mostrar('Contesta',false);}}
 function func_44_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'No','=='))&&(ValC('DomicilioCorrecto', 'No','=='))){Mostrar('DictamenNumeroEquivocado', true);}else{Mostrar('DictamenNumeroEquivocado',false);}}
 function func_45_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'No','=='))&&(ValC('DomicilioCorrecto', 'Si','=='))){Mostrar('DictamenHabitadaDesconocidos', true);}else{Mostrar('DictamenHabitadaDesconocidos',false);}}
 function func_46_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'No','=='))){Mostrar('DomicilioCorrecto', true);}else{Mostrar('DomicilioCorrecto',false);}}
 function func_47_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'No','=='))&&(ValC('AclaracionDefuncion', 'No','=='))){Mostrar('DictamenHabitadaTerceros', true);}else{Mostrar('DictamenHabitadaTerceros',false);}}
 function func_48_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'No','=='))&&(ValC('AclaracionDefuncion', 'Si','=='))){Mostrar('DictamenDefuncion', true);}else{Mostrar('DictamenDefuncion',false);}}
 function func_49_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'No','=='))){Mostrar('AclaracionDefuncion', true);}else{Mostrar('AclaracionDefuncion',false);}}
 function func_5_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))&&(ValC('reqAct', 'Si','=='))&&(ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT4', 'Oficina','=='))){Mostrar('AgExtensionT4', true);}else{Mostrar('AgExtensionT4',false);}}
 function func_50_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))){Mostrar('PuedeLocalizarlo', true);}else{Mostrar('PuedeLocalizarlo',false);}}
 function func_51_144(){ if((ValC('TotalizaA', '5','>='))&&(ValC('AcreditadoVive', 'No','=='))){Mostrar('ConoceAcreditado', true);}else{Mostrar('ConoceAcreditado',false);}}
 function func_52_144(){ if((ValC('TotalizaA', '8','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))&&(ValC('PuedeLocalizarlo', 'Si','=='))){Mostrar('NumeroContactoPL', true);Mostrar('HorarioContactoPL', true);Mostrar('ParentescoPL', true);Mostrar('DictamenRecado2', true);}else{Mostrar('NumeroContactoPL',false);Mostrar('HorarioContactoPL',false);Mostrar('ParentescoPL',false);Mostrar('DictamenRecado2',false);}}
 function func_53_144(){ if((ValC('TotalizaA', '8','>='))&&(ValC('AcreditadoVive', 'No','=='))&&(ValC('ConoceAcreditado', 'Si','=='))||(ValC('ConoceAcreditado', 'Si','=='))){Mostrar('NombreContestoPL', true);}else{Mostrar('NombreContestoPL',false);}}
 function func_54_144(){ if((ValC('TotalizaA', '8','>='))&&(ValC('AcreditadoVive', 'Si','=='))){Mostrar('NumeroContactoAV', true);Mostrar('HorarioContactoAV', true);Mostrar('NombreContestoAV', true);Mostrar('ParentescoAV', true);Mostrar('DictamenRecado', true);}else{Mostrar('NumeroContactoAV',false);Mostrar('HorarioContactoAV',false);Mostrar('NombreContestoAV',false);Mostrar('ParentescoAV',false);Mostrar('DictamenRecado',false);}}
 function func_55_144(){ if((ValC('TotalizaA', '8','>='))){Mostrar('AcreditadoVive', true);}else{Mostrar('AcreditadoVive',false);}}
 function func_56_144xxx(){ $('#TotalizaC').val(Calc('AceptaFPP1Fin+AceptaFPP2Fin+AceptaFPP3Fin+AceptaFPP4Fin+AceptaFPP5Fin+AceptaFPP6Fin'));}
 function func_57_144(){ $('#TotalizaA').val(Calc('AcreditadoFin+VerificarDatosFin+DatosCorrectosFin+ActitudHostilFin'));}
 function func_58_144xxx(){ $('#TotalizaB').val(Calc('AplicaFPPFin+AceptaFPPFin'));}
 function func_6_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))&&(ValC('reqAct', 'Si','=='))&&(ValC('AgTelefonos', 'Si','=='))){Mostrar('TelTipoAgT4', true);Mostrar('AgTelefonoT4', true);Mostrar('TelTipoAgT3', true);Mostrar('AgTelefonoT3', true);Mostrar('TelTipoAgT1', true);Mostrar('AgTelefonoT1', true);Mostrar('TelTipoAgT2', true);Mostrar('AgTelefonoT2', true);}else{Mostrar('TelTipoAgT4',false);Mostrar('AgTelefonoT4',false);Mostrar('TelTipoAgT3',false);Mostrar('AgTelefonoT3',false);Mostrar('TelTipoAgT1',false);Mostrar('AgTelefonoT1',false);Mostrar('TelTipoAgT2',false);Mostrar('AgTelefonoT2',false);}}
 function func_7_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))&&(ValC('reqAct', 'Si','=='))){Mostrar('NU_TELEFONO_CASA_ACT', true);Mostrar('CORROBNU_TELEFONO_CASA', true);Mostrar('NU_TELEFONO_CELULAR_ACT', true);Mostrar('CORROBNU_TELEFONO_CELULAR', true);Mostrar('NU_TELEFONO_TRABAJO_ACT', true);Mostrar('AgTelefonos', true);Mostrar('TX_CORREO_ELECTRONICO_ACT', true);Mostrar('TX_CALLE_ACT', true);Mostrar('TX_NU_CALLE_EXT_ACT', true);Mostrar('TX_NU_CALLE_INT_ACT', true);Mostrar('TX_EDIFICIO_ACT', true);Mostrar('TX_COLONIA_ACT', true);Mostrar('TX_MUNICIPIO_ACT', true);Mostrar('TX_ESTADO_ACT', true);Mostrar('CV_CODIGO_POSTAL_ACT', true);Mostrar('TX_ENTRE_CALLE1_ACT', true);Mostrar('TX_ENTRE_CALLE2_ACT', true);}else{Mostrar('NU_TELEFONO_CASA_ACT',false);Mostrar('CORROBNU_TELEFONO_CASA',false);Mostrar('NU_TELEFONO_CELULAR_ACT',false);Mostrar('CORROBNU_TELEFONO_CELULAR',false);Mostrar('NU_TELEFONO_TRABAJO_ACT',false);Mostrar('AgTelefonos',false);Mostrar('TX_CORREO_ELECTRONICO_ACT',false);Mostrar('TX_CALLE_ACT',false);Mostrar('TX_NU_CALLE_EXT_ACT',false);Mostrar('TX_NU_CALLE_INT_ACT',false);Mostrar('TX_EDIFICIO_ACT',false);Mostrar('TX_COLONIA_ACT',false);Mostrar('TX_MUNICIPIO_ACT',false);Mostrar('TX_ESTADO_ACT',false);Mostrar('CV_CODIGO_POSTAL_ACT',false);Mostrar('TX_ENTRE_CALLE1_ACT',false);Mostrar('TX_ENTRE_CALLE2_ACT',false);}}
 function func_8_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))&&(ValC('VerificarDatos', 'Si','=='))){Mostrar('reqAct', true);}else{Mostrar('reqAct',false);}}
 function func_9_144(){ if((ValC('Acreditado', 'Si','=='))&&(ValC('ActitudHostil', 'No','=='))){Mostrar('VerificarDatos', true);}else{Mostrar('VerificarDatos',false);}}
 function FuncMTelefonos(){ if((ValC("reqAct", "Si","==") && ValC("AgTelefonos", "Si","=="))){Mostrar("TelTipoAgT1",true);Mostrar("AgTelefonoT1",true);Mostrar("TelTipoAgT2",true);Mostrar("AgTelefonoT2",true);Mostrar("TelTipoAgT3",true);Mostrar("AgTelefonoT3",true);Mostrar("TelTipoAgT4",true);Mostrar("AgTelefonoT4",true);}else{Mostrar("TelTipoAgT1",false);Mostrar("AgTelefonoT1",false);Mostrar("TelTipoAgT2",false);Mostrar("AgTelefonoT2",false);Mostrar("TelTipoAgT3",false);Mostrar("AgTelefonoT3",false);Mostrar("TelTipoAgT4",false);Mostrar("AgTelefonoT4",false);}}
 function TotalizaA(){ if(true){$("#TotalizaA").trigger("blur");}else{$("#TotalizaA").trigger("blur");}}
 function TotalizaB(){ if(true){$("#TotalizaB").trigger("blur");}else{$("#TotalizaB").trigger("blur");}}
 function TotalizaC(){ if(true){$("#TotalizaC").trigger("blur");}else{$("#TotalizaC").trigger("blur");}}
 function VerificarDatos(){ if(ValC("VerificarDatos", "No","==")){$("#VerificarDatosFin").val("0");$("#VerificarDatosFin").trigger("blur");}else{$("#VerificarDatosFin").val("2");$("#VerificarDatosFin").trigger("blur");}}
