 function DicAplicaSMS(){ if((ValC("DicAplicaSMS", "No","=="))){pcFormularios.GetTabByName("Actualizacion").SetEnabled(true);pcFormularios.GetTabByName("GestVisita").SetEnabled(true);}else{pcFormularios.GetTabByName("Actualizacion").SetEnabled(false);pcFormularios.GetTabByName("GestVisita").SetEnabled(false);}}
 function func_1_152(){ $('#ingresos').val(Calc('IngtotalesDCP+ingresos_total_concubina'));}
 function func_10_148(){ if((ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT2', 'Oficina','=='))){Mostrar('AgExtensionT2', true);}else{Mostrar('AgExtensionT2',false);}}
 function func_100_145(){ if((ValC('IN_OPCION_JUDICIAL', '0','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))){Mostrar('DictamenSiAceptaSTM', true);}else{Mostrar('DictamenSiAceptaSTM',false);}}
 function func_102_145(){ if((ValC('IN_OPCION_JUDICIAL', '0','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))){Mostrar('DictamenSTM', true);}else{Mostrar('DictamenSTM',false);}}
 function func_104_145(){ if((ValC('IN_OPCION_JUDICIAL', '0','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))){Mostrar('DictamenBCN', true);}else{Mostrar('DictamenBCN',false);}}
 function func_106_145(){ if((ValC('IN_OPCION_JUDICIAL', '0','=='))){Mostrar('DictamenDCP', true);}else{Mostrar('DictamenDCP',false);}}
 function func_107_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('TipoConvenioDCP', 'Convenio_judicial','=='))){Mostrar('DictamenDCPJudicial', true);}else{Mostrar('DictamenDCPJudicial',false);}}
 function func_109_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('TipoConvenioDCP', 'Convenio_privado','=='))){Mostrar('DictamenDCPPrivado', true);}else{Mostrar('DictamenDCPPrivado',false);}}
 function func_11_148(){ if((ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT3', 'Oficina','=='))){Mostrar('AgExtensionT3', true);}else{Mostrar('AgExtensionT3',false);}}
 function func_111_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))&&(ValC('TipoConvenioSiAceptaSTM', 'Convenio_judicial','=='))){Mostrar('DictamenSiAceptaSTMJudicial', true);}else{Mostrar('DictamenSiAceptaSTMJudicial',false);}}
 function func_113_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))&&(ValC('TipoConvenioSiAceptaSTM', 'Convenio_privado','=='))){Mostrar('DictamenSiAceptaSTMPrivado', true);}else{Mostrar('DictamenSiAceptaSTMPrivado',false);}}
 function func_115_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))){Mostrar('TipoConvenioSiAceptaSTM', true);}else{Mostrar('TipoConvenioSiAceptaSTM',false);}}
 function func_117_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))&&(ValC('TipoConvenioSTM1', 'Convenio_judicial','=='))){Mostrar('DictamenSTMJudicial', true);}else{Mostrar('DictamenSTMJudicial',false);}}
 function func_119_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))&&(ValC('TipoConvenioSTM1', 'Convenio_privado','=='))){Mostrar('DictamenSTMPrivado', true);}else{Mostrar('DictamenSTMPrivado',false);}}
 function func_12_148(){ if((ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT4', 'Oficina','=='))){Mostrar('AgExtensionT4', true);}else{Mostrar('AgExtensionT4',false);}}
 function func_121_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))){Mostrar('TipoConvenioSTM1', true);}else{Mostrar('TipoConvenioSTM1',false);}}
 function func_123_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))&&(ValC('TipoConvenioBCN', 'Convenio_judicial','=='))){Mostrar('DictamenBCNJudicial', true);}else{Mostrar('DictamenBCNJudicial',false);}}
 function func_125_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))&&(ValC('TipoConvenioBCN', 'Convenio_privado','=='))){Mostrar('DictamenBCNPrivado', true);}else{Mostrar('DictamenBCNPrivado',false);}}
 function func_127_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))){Mostrar('TipoConvenioBCN', true);}else{Mostrar('TipoConvenioBCN',false);}}
 function func_129_145(){ if((ValC('IN_OPCION_JUDICIAL', '1','>='))){Mostrar('TipoConvenioDCP', true);}else{Mostrar('TipoConvenioDCP',false);}}
 function func_13_148(){ if((ValC('AgTelefonos', 'Si','=='))){Mostrar('TelTipoAgT3', true);Mostrar('AgTelefonoT3', true);Mostrar('TelTipoAgT2', true);Mostrar('AgTelefonoT2', true);Mostrar('TelTipoAgT1', true);Mostrar('AgTelefonoT1', true);Mostrar('TelTipoAgT4', true);Mostrar('AgTelefonoT4', true);}else{Mostrar('TelTipoAgT3',false);Mostrar('AgTelefonoT3',false);Mostrar('TelTipoAgT2',false);Mostrar('AgTelefonoT2',false);Mostrar('TelTipoAgT1',false);Mostrar('AgTelefonoT1',false);Mostrar('TelTipoAgT4',false);Mostrar('AgTelefonoT4',false);}}
 function func_130_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))&&(ValC('ParCelularSMS_Liquid', 'Otro','=='))){Mostrar('OtroParCelularSMS_Liquid', true);}else{Mostrar('OtroParCelularSMS_Liquid',false);}}
 function func_132_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('ValSMS_Liquid', true);Mostrar('CelularSMS_Liquid', true);}else{Mostrar('ValSMS_Liquid',false);Mostrar('CelularSMS_Liquid',false);}}
 function func_133_149(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('ConfirmeSMS_Liquid', true);Mostrar('ParCelularSMS_Liquid', true);}else{Mostrar('ConfirmeSMS_Liquid',false);Mostrar('ParCelularSMS_Liquid',false);}}
 function func_134_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))&&(ValC('ParCelularSMS_ProPag', 'Otro','=='))){Mostrar('OtroParCelularSMS_ProPag', true);}else{Mostrar('OtroParCelularSMS_ProPag',false);}}
 function func_136_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('CelularSMS_ProPag', true);Mostrar('ValSMS_ProPag', true);}else{Mostrar('CelularSMS_ProPag',false);Mostrar('ValSMS_ProPag',false);}}
 function func_137_149(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('ParCelularSMS_ProPag', true);Mostrar('ConfirmeSMS_ProPag', true);}else{Mostrar('ParCelularSMS_ProPag',false);Mostrar('ConfirmeSMS_ProPag',false);}}
 function func_138_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))&&(ValC('ParCelularSMS_promdepagoTOM', 'Otro','=='))){Mostrar('OtroParCelularSMS_ProPagTOM', true);}else{Mostrar('OtroParCelularSMS_ProPagTOM',false);}}
 function func_14_152(){ if((ValC('AguinalDCP', 'Si','=='))){Mostrar('MontoaguinalDCP', true);}else{Mostrar('MontoaguinalDCP',false);}}
 function func_140_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))&&(ValC('ParCelularSMS_promdepagoTOM2', 'Otro','=='))){Mostrar('OtroParCelularSMS_ProPagTOM2', true);}else{Mostrar('OtroParCelularSMS_ProPagTOM2',false);}}
 function func_142_145(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('CelularSMS_promdepagoTOM', true);Mostrar('ValSMS_promdepagoTOM', true);}else{Mostrar('CelularSMS_promdepagoTOM',false);Mostrar('ValSMS_promdepagoTOM',false);}}
 function func_143_149(){ if((ValC('IN_SOLICITAR_CEL', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('ParCelularSMS_promdepagoTOM', true);Mostrar('ConfirmeSMS_promdepagoTOM', true);}else{Mostrar('ParCelularSMS_promdepagoTOM',false);Mostrar('ConfirmeSMS_promdepagoTOM',false);}}
 function func_144_145(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('ConfirmeSMS_promdepagoTOM2', true);}else{Mostrar('ConfirmeSMS_promdepagoTOM2',false);}}
 function func_146_145(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))&&(ValC('ParCelularSMS_Liquid2', 'Otro','=='))){Mostrar('OtroParCelularSMS_Liquid2', true);}else{Mostrar('OtroParCelularSMS_Liquid2',false);}}
 function func_148_145(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('ValSMS_Liquid2', true);Mostrar('CelularSMS_Liquid2', true);}else{Mostrar('ValSMS_Liquid2',false);Mostrar('CelularSMS_Liquid2',false);}}
 function func_149_149(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('ConfirmeSMS_Liquid2', true);Mostrar('ParCelularSMS_Liquid2', true);}else{Mostrar('ConfirmeSMS_Liquid2',false);Mostrar('ParCelularSMS_Liquid2',false);}}
 function func_15_152(){ if((ValC('AportotrosfamDCP', 'Si','=='))){Mostrar('Cantmensotrosfam', true);Mostrar('Instperiootrosf', true);Mostrar('PeriodisotrosfamDCP', true);}else{Mostrar('Cantmensotrosfam',false);Mostrar('Instperiootrosf',false);Mostrar('PeriodisotrosfamDCP',false);}}
 function func_150_145(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))&&(ValC('ParCelularSMS_ProPag2', 'Otro','=='))){Mostrar('OtroParCelularSMS_ProPag2', true);}else{Mostrar('OtroParCelularSMS_ProPag2',false);}}
 function func_152_145(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('CelularSMS_ProPag2', true);Mostrar('ValSMS_ProPag2', true);}else{Mostrar('CelularSMS_ProPag2',false);Mostrar('ValSMS_ProPag2',false);}}
 function func_153_149(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('ParCelularSMS_ProPag2', true);Mostrar('ConfirmeSMS_ProPag2', true);}else{Mostrar('ParCelularSMS_ProPag2',false);Mostrar('ConfirmeSMS_ProPag2',false);}}
 function func_154_145(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('ParCelularSMS_promdepagoTOM2', true);Mostrar('CelularSMS_promdepagoTOM2', true);}else{Mostrar('ParCelularSMS_promdepagoTOM2',false);Mostrar('CelularSMS_promdepagoTOM2',false);}}
 function func_155_149(){ if((ValC('IN_SOLICITAR_CEL', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('ValSMS_promdepagoTOM2', true);}else{Mostrar('ValSMS_promdepagoTOM2',false);}}
 function func_156_152(){ if((ValC('MtoVivienda', 'No','=='))){Mostrar('motivo_no_32', true);}else{Mostrar('motivo_no_32',false);}}
 function func_157_152(){ if((ValC('MtoVivienda', 'Si','=='))){Mostrar('monto_32', true);}else{Mostrar('monto_32',false);}}
 function func_158_145(){ if((ValC('OP_REGIMEN', '1','=='))&&(ValC('TipoConvenioDCP', 'Convenio_judicial','=='))){Mostrar('InstDCPOPR1', true);}else{Mostrar('InstDCPOPR1',false);}}
 function func_16_152(){ if((ValC('BecasDCP', 'Si','=='))){Mostrar('Cantmensbecas', true);Mostrar('Instperiobeca', true);Mostrar('PeriodisbecaDCP', true);}else{Mostrar('Cantmensbecas',false);Mostrar('Instperiobeca',false);Mostrar('PeriodisbecaDCP',false);}}
 function func_160_145(){ if((ValC('OP_REGIMEN', '1','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))&&(ValC('TipoConvenioSiAceptaSTM', 'Convenio_judicial','=='))){Mostrar('InstSiAceptaSTMOPR1', true);}else{Mostrar('InstSiAceptaSTMOPR1',false);}}
 function func_162_145(){ if((ValC('OP_REGIMEN', '1','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))&&(ValC('TipoConvenioSTM1', 'Convenio_judicial','=='))){Mostrar('InstSTMOPR1', true);}else{Mostrar('InstSTMOPR1',false);}}
 function func_164_145(){ if((ValC('OP_REGIMEN', '1','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))&&(ValC('TipoConvenioBCN', 'Convenio_judicial','=='))){Mostrar('InstBCNOPR1', true);}else{Mostrar('InstBCNOPR1',false);}}
 function func_166_145(){ if((ValC('OP_REGIMEN', '2','=='))&&(ValC('TipoConvenioDCP', 'Convenio_judicial','=='))){Mostrar('InstDCPOPR2', true);}else{Mostrar('InstDCPOPR2',false);}}
 function func_168_145(){ if((ValC('OP_REGIMEN', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))&&(ValC('TipoConvenioSiAceptaSTM', 'Convenio_judicial','=='))){Mostrar('InstSiAceptaSTMOPR2', true);}else{Mostrar('InstSiAceptaSTMOPR2',false);}}
 function func_17_151xxx(){ if((ValC('CantidadPagos', '1','=='))){Mostrar('AceptaFPP1', true);}else{Mostrar('AceptaFPP1',false);}}
 function func_170_145(){ if((ValC('OP_REGIMEN', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))&&(ValC('TipoConvenioSTM1', 'Convenio_judicial','=='))){Mostrar('InstSTMOPR2', true);}else{Mostrar('InstSTMOPR2',false);}}
 function func_172_145(){ if((ValC('OP_REGIMEN', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))&&(ValC('TipoConvenioBCN', 'Convenio_judicial','=='))){Mostrar('InstBCNOPR2', true);}else{Mostrar('InstBCNOPR2',false);}}
 function func_174_152(){ if((ValC('OtroDCP47', 'No','=='))){Mostrar('motivo_no_47', true);}else{Mostrar('motivo_no_47',false);}}
 function func_175_152(){ if((ValC('OtroDCP47', 'Si','=='))){Mostrar('monto_47', true);}else{Mostrar('monto_47',false);}}
 function func_176_152(){ if((ValC('OtrosIngDCP', 'Si','=='))){Mostrar('Cantmensotros', true);Mostrar('Instperiootros', true);Mostrar('PeriodiotroDCP', true);}else{Mostrar('Cantmensotros',false);Mostrar('Instperiootros',false);Mostrar('PeriodiotroDCP',false);}}
 function func_177_153(){ if((ValC('ParCelularSMS_CONFPR', 'Otro','=='))){Mostrar('OtroParCelularSMS_CONFPR', true);}else{Mostrar('OtroParCelularSMS_CONFPR',false);}}
 function func_178_152(){ if((ValC('ParCelularSMS_DCP', 'Otro','=='))){Mostrar('OtroParCelularSMS_DCP', true);}else{Mostrar('OtroParCelularSMS_DCP',false);}}
 function func_179_151(){ if((ValC('ParCelularSMS_FPP', 'Otro','=='))){Mostrar('OtroParCelularSMS_FPP', true);}else{Mostrar('OtroParCelularSMS_FPP',false);}}
 function func_18_151(){ if((ValC('CantidadPagos', '1','>='))){Mostrar('TX_PAGA1', true);}else{Mostrar('TX_PAGA1',false);}}
 function func_180_152(){ if((ValC('PensionDCP', 'Si','=='))){Mostrar('Cantmenspension', true);Mostrar('Instperiodpen', true);Mostrar('PeriodipensDCP', true);}else{Mostrar('Cantmenspension',false);Mostrar('Instperiodpen',false);Mostrar('PeriodipensDCP',false);}}
 function func_181_152(){ if((ValC('PensMtoAuto', 'No','=='))){Mostrar('motivo_no_39', true);}else{Mostrar('motivo_no_39',false);}}
 function func_182_152(){ if((ValC('PensMtoAuto', 'Si','=='))){Mostrar('monto_39', true);}else{Mostrar('monto_39',false);}}
 function func_183_152(){ if((ValC('Predial', 'No','=='))){Mostrar('motivo_no_44', true);}else{Mostrar('motivo_no_44',false);}}
 function func_184_152(){ if((ValC('Predial', 'Si','=='))){Mostrar('monto_44', true);}else{Mostrar('monto_44',false);}}
 function func_185_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'No','=='))){Mostrar('Ocupaactcony', true);}else{Mostrar('Ocupaactcony',false);}}
 function func_186_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('AguiCony', 'Si','=='))){Mostrar('Cantagiocony', true);}else{Mostrar('Cantagiocony',false);}}
 function func_187_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('BecasCony', 'Si','=='))){Mostrar('CantBecasCony', true);Mostrar('InsBecCony', true);Mostrar('PeriodBecCony', true);}else{Mostrar('CantBecasCony',false);Mostrar('InsBecCony',false);Mostrar('PeriodBecCony',false);}}
 function func_188_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('EmpTempCon', 'Si','=='))){Mostrar('Cantemptempcon', true);Mostrar('InsemptemCony', true);Mostrar('PeriodEmpTempCon', true);}else{Mostrar('Cantemptempcon',false);Mostrar('InsemptemCony',false);Mostrar('PeriodEmpTempCon',false);}}
 function func_189_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('HonoCony', 'Si','=='))){Mostrar('CantHonoCony', true);Mostrar('InsHonoCony', true);Mostrar('PerioHonCony', true);}else{Mostrar('CantHonoCony',false);Mostrar('InsHonoCony',false);Mostrar('PerioHonCony',false);}}
 function func_19_151xxx(){ if((ValC('CantidadPagos', '2','=='))){Mostrar('AceptaFPP2', true);}else{Mostrar('AceptaFPP2',false);}}
 function func_190_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('OtroCony', 'Si','=='))){Mostrar('CantOtroCony', true);Mostrar('InsOtroCony', true);Mostrar('PeriodOtrosCony', true);}else{Mostrar('CantOtroCony',false);Mostrar('InsOtroCony',false);Mostrar('PeriodOtrosCony',false);}}
 function func_191_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('OtrosFamCon', 'Si','=='))){Mostrar('CantOtrCony', true);Mostrar('Insotroscony', true);Mostrar('PeriodOfamCony', true);}else{Mostrar('CantOtrCony',false);Mostrar('Insotroscony',false);Mostrar('PeriodOfamCony',false);}}
 function func_192_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('Penscony', 'Si','=='))){Mostrar('CantPensCony', true);Mostrar('Inspenscon', true);Mostrar('PerioPenscony', true);}else{Mostrar('CantPensCony',false);Mostrar('Inspenscon',false);Mostrar('PerioPenscony',false);}}
 function func_193_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))&&(ValC('Valesdepcony', 'Si','=='))){Mostrar('CantValesCony', true);Mostrar('InsValcony', true);Mostrar('Periocidad', true);}else{Mostrar('CantValesCony',false);Mostrar('InsValcony',false);Mostrar('Periocidad',false);}}
 function func_194_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('Conyugactrem', 'Si','=='))){Mostrar('AguiCony', true);Mostrar('Ingmensconyneto', true);Mostrar('ComrIngcony', true);Mostrar('PercIngcony', true);Mostrar('Valesdepcony', true);Mostrar('EmpTempCon', true);Mostrar('HonoCony', true);Mostrar('Penscony', true);Mostrar('BecasCony', true);Mostrar('OtroCony', true);Mostrar('OtrosFamCon', true);Mostrar('ingresos_total_concubina', true);}else{Mostrar('AguiCony',false);Mostrar('Ingmensconyneto',false);Mostrar('ComrIngcony',false);Mostrar('PercIngcony',false);Mostrar('Valesdepcony',false);Mostrar('EmpTempCon',false);Mostrar('HonoCony',false);Mostrar('Penscony',false);Mostrar('BecasCony',false);Mostrar('OtroCony',false);Mostrar('OtrosFamCon',false);Mostrar('ingresos_total_concubina',false);}}
 function func_195_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('TipoactconyDCP', 'Otra actividad renumerada','=='))){Mostrar('Espotractcony', true);}else{Mostrar('Espotractcony',false);}}
 function func_196_152(){ if((ValC('PregDCP_17', 'Si','=='))&&(ValC('TipoactconyDCP', 'Trabajo independiente','=='))){Mostrar('Cualtrabindcony', true);}else{Mostrar('Cualtrabindcony',false);}}
 function func_197_152(){ if((ValC('PregDCP_17', 'Si','=='))){Mostrar('TipoactconyDCP', true);Mostrar('Nodepersconact', true);Mostrar('Conyugactrem', true);}else{Mostrar('TipoactconyDCP',false);Mostrar('Nodepersconact',false);Mostrar('Conyugactrem',false);}}
 function func_198_147(){ if((ValC('RecMenSMS', 'No','=='))&&(ValC('CorroboroCelularSMS', 'No','=='))){Mostrar('CelularSMS_Actualizado', true);}else{Mostrar('CelularSMS_Actualizado',false);}}
 function func_199_147(){ if((ValC('RecMenSMS', 'No','=='))&&(ValC('CorroboroCelularSMS', 'Si','=='))&&(ValC('ContinuarGestion', 'Si','=='))){pcFormularios.GetTabByName('Actualizacion').SetEnabled(true);pcFormularios.GetTabByName('GestVisita').SetEnabled(true);}else{pcFormularios.GetTabByName('Actualizacion').SetEnabled(false);pcFormularios.GetTabByName('GestVisita').SetEnabled(false);}}
 function func_2_152(){ $('#IngtotalesDCP').val(Calc('Ingnetoactdcp+Cantmensvales+MontoaguinalDCP+Cantmenspension+CantmensEmptempDCP+CantmenssncontDCP+CantmenshonoDCP+CantmensremesDCP+Cantmensotrosfam+Cantmensbecas+Cantmensotros'));}
 function func_20_151(){ if((ValC('CantidadPagos', '2','>='))){Mostrar('TX_PAGA2', true);}else{Mostrar('TX_PAGA2',false);}}
 function func_200_147(){ if((ValC('RecMenSMS', 'No','=='))&&(ValC('CorroboroCelularSMS', 'Si','=='))){Mostrar('NotSMS2', true);Mostrar('ContinuarGestion',false);}else{Mostrar('NotSMS2',false);Mostrar('ContinuarGestion',false);}}
 function func_201_147(){ if((ValC('RecMenSMS', 'No','=='))){Mostrar('NotSMS', true);Mostrar('CorroboroCelularSMS', true);}else{Mostrar('NotSMS',false);Mostrar('CorroboroCelularSMS',false);}}
 function func_202_147(){ if((ValC('RecMenSMS', 'Si','=='))){Mostrar('CodSMS', true);Mostrar('ValCodSMS', true);}else{Mostrar('CodSMS',false);Mostrar('ValCodSMS',false);}}
 function func_203_152(){ if((ValC('Recreacion', 'No','=='))){Mostrar('motivo_no_37', true);}else{Mostrar('motivo_no_37',false);}}
 function func_204_152(){ if((ValC('Recreacion', 'Si','=='))){Mostrar('monto_37', true);}else{Mostrar('monto_37',false);}}
 function func_205_152(){ if((ValC('RemesasDCP', 'Si','=='))){Mostrar('CantmensremesDCP', true);Mostrar('Instperiodreme', true);Mostrar('PeriodisremeDCP', true);}else{Mostrar('CantmensremesDCP',false);Mostrar('Instperiodreme',false);Mostrar('PeriodisremeDCP',false);}}
 function func_206_148(){ if((ValC('reqAct', 'Si','=='))){Mostrar('NU_TELEFONO_CASA_ACT', true);Mostrar('CORROBNU_TELEFONO_CASA', true);Mostrar('NU_TELEFONO_CELULAR_ACT', true);Mostrar('CORROBNU_TELEFONO_CELULAR', true);Mostrar('NU_TELEFONO_TRABAJO_ACT', true);Mostrar('AgTelefonos', true);Mostrar('TX_CORREO_ELECTRONICO_ACT', true);Mostrar('TX_CALLE_ACT', true);Mostrar('TX_NU_CALLE_EXT_ACT', true);Mostrar('TX_NU_CALLE_INT_ACT', true);Mostrar('TX_EDIFICIO_ACT', true);Mostrar('TX_COLONIA_ACT', true);Mostrar('TX_MUNICIPIO_ACT', true);Mostrar('TX_ESTADO_ACT', true);Mostrar('CV_CODIGO_POSTAL_ACT', true);Mostrar('TX_ENTRE_CALLE1_ACT', true);Mostrar('TX_ENTRE_CALLE2_ACT', true);}else{Mostrar('NU_TELEFONO_CASA_ACT',false);Mostrar('CORROBNU_TELEFONO_CASA',false);Mostrar('NU_TELEFONO_CELULAR_ACT',false);Mostrar('CORROBNU_TELEFONO_CELULAR',false);Mostrar('NU_TELEFONO_TRABAJO_ACT',false);Mostrar('AgTelefonos',false);Mostrar('TX_CORREO_ELECTRONICO_ACT',false);Mostrar('TX_CALLE_ACT',false);Mostrar('TX_NU_CALLE_EXT_ACT',false);Mostrar('TX_NU_CALLE_INT_ACT',false);Mostrar('TX_EDIFICIO_ACT',false);Mostrar('TX_COLONIA_ACT',false);Mostrar('TX_MUNICIPIO_ACT',false);Mostrar('TX_ESTADO_ACT',false);Mostrar('CV_CODIGO_POSTAL_ACT',false);Mostrar('TX_ENTRE_CALLE1_ACT',false);Mostrar('TX_ENTRE_CALLE2_ACT',false);}}
 function func_207_153(){ if((ValC('SelTipoProrroga', 'Parcial','=='))&&(ValC('ParCelularSMS_CONFPRParcial', 'Otro','=='))){Mostrar('OtroParCelularSMS_CONFPRParcial', true);}else{Mostrar('OtroParCelularSMS_CONFPRParcial',false);}}
 function func_208_153(){ if((ValC('SelTipoProrroga', 'Parcial','=='))){Mostrar('InstrPR50503', true);Mostrar('MensualidadPR5050', true);Mostrar('AportCompPR5050', true);Mostrar('AportInfonavitPR5050', true);Mostrar('InstrPR50504', true);Mostrar('FH_PROMESA_PAGOPR5050', true);Mostrar('InstrPR50505', true);Mostrar('InstrPR50506', true);Mostrar('fotoIFEPR5050', true);Mostrar('fotoIFERevPR5050', true);Mostrar('InstrPR50507', true);Mostrar('DictamenPR5050', true);Mostrar('CelularSMS_CONFPRParcial', true);Mostrar('ConfirmeSMS_CONFPRParcial', true);Mostrar('ValSMS_CONFPRParcial', true);Mostrar('ParCelularSMS_CONFPRParcial', true);}else{Mostrar('InstrPR50503',false);Mostrar('MensualidadPR5050',false);Mostrar('AportCompPR5050',false);Mostrar('AportInfonavitPR5050',false);Mostrar('InstrPR50504',false);Mostrar('FH_PROMESA_PAGOPR5050',false);Mostrar('InstrPR50505',false);Mostrar('InstrPR50506',false);Mostrar('fotoIFEPR5050',false);Mostrar('fotoIFERevPR5050',false);Mostrar('InstrPR50507',false);Mostrar('DictamenPR5050',false);Mostrar('CelularSMS_CONFPRParcial',false);Mostrar('ConfirmeSMS_CONFPRParcial',false);Mostrar('ValSMS_CONFPRParcial',false);Mostrar('ParCelularSMS_CONFPRParcial',false);}}
 function func_209_153(){ if((ValC('SelTipoProrroga', 'Total','=='))){Mostrar('InstrFPR6', true);Mostrar('fotoIFEConfPR', true);Mostrar('fotoIFERevConfPR', true);Mostrar('InstrFPR7', true);Mostrar('DictamenCONFPR', true);Mostrar('CelularSMS_CONFPR', true);Mostrar('ConfirmeSMS_CONFPR', true);Mostrar('ValSMS_CONFPR', true);}else{Mostrar('InstrFPR6',false);Mostrar('fotoIFEConfPR',false);Mostrar('fotoIFERevConfPR',false);Mostrar('InstrFPR7',false);Mostrar('DictamenCONFPR',false);Mostrar('CelularSMS_CONFPR',false);Mostrar('ConfirmeSMS_CONFPR',false);Mostrar('ValSMS_CONFPR',false);}}
 function func_21_151xxx(){ if((ValC('CantidadPagos', '3','=='))){Mostrar('AceptaFPP3', true);}else{Mostrar('AceptaFPP3',false);}}
 function func_210_152(){ if((ValC('ServSalud', 'No','=='))){Mostrar('motivo_no_35', true);}else{Mostrar('motivo_no_35',false);}}
 function func_211_152(){ if((ValC('ServSalud', 'Si','=='))){Mostrar('monto_35', true);}else{Mostrar('monto_35',false);}}
 function func_212_147(){ if((ValC('SMSDuplicado', '1','=='))){Mostrar('NumRegAnt', true);}else{Mostrar('NumRegAnt',false);}}
 function func_213_152(){ if((ValC('TelefCelular', 'No','=='))){Mostrar('motivo_no_40', true);}else{Mostrar('motivo_no_40',false);}}
 function func_214_152(){ if((ValC('TelefCelular', 'Si','=='))){Mostrar('monto_40', true);}else{Mostrar('monto_40',false);}}
 function func_215_152(){ if((ValC('TrabsincontDCP', 'Si','=='))){Mostrar('CantmenssncontDCP', true);Mostrar('Instperiodsncont', true);Mostrar('PeriodisncontDCP', true);}else{Mostrar('CantmenssncontDCP',false);Mostrar('Instperiodsncont',false);Mostrar('PeriodisncontDCP',false);}}
 function func_216_152(){ if((ValC('TransPublico', 'No','=='))){Mostrar('motivo_no_33', true);}else{Mostrar('motivo_no_33',false);}}
 function func_217_152(){ if((ValC('TransPublico', 'Si','=='))){Mostrar('monto_33', true);}else{Mostrar('monto_33',false);}}
 function func_218_152(){ if((ValC('TVPaga', 'No','=='))){Mostrar('motivo_no_41', true);}else{Mostrar('motivo_no_41',false);}}
 function func_219_152(){ if((ValC('TVPaga', 'Si','=='))){Mostrar('monto_41', true);}else{Mostrar('monto_41',false);}}
 function func_22_151(){ if((ValC('CantidadPagos', '3','>='))){Mostrar('TX_PAGA3', true);}else{Mostrar('TX_PAGA3',false);}}
 function func_220_152(){ if((ValC('UtilesEscolares', 'No','=='))){Mostrar('motivo_no_45', true);}else{Mostrar('motivo_no_45',false);}}
 function func_221_152(){ if((ValC('UtilesEscolares', 'Si','=='))){Mostrar('monto_45', true);}else{Mostrar('monto_45',false);}}
 function func_222_152(){ if((ValC('Vacaciones', 'No','=='))){Mostrar('motivo_no_46', true);}else{Mostrar('motivo_no_46',false);}}
 function func_223_152(){ if((ValC('Vacaciones', 'Si','=='))){Mostrar('monto_46', true);}else{Mostrar('monto_46',false);}}
 function func_224_152(){ if((ValC('Valesdespdcp', 'Si','=='))){Mostrar('Cantmensvales', true);Mostrar('Instmesesdcp', true);Mostrar('PeriodivalesDCP', true);}else{Mostrar('Cantmensvales',false);Mostrar('Instmesesdcp',false);Mostrar('PeriodivalesDCP',false);}}
 function func_225_149(){ if((ValC('vivLoc', 'No','=='))){Mostrar('Nolocvivhead', true);Mostrar('comentario_noLocalizo', true);Mostrar('Dictamenviviendailoc', true);}else{Mostrar('Nolocvivhead',false);Mostrar('comentario_noLocalizo',false);Mostrar('Dictamenviviendailoc',false);}}
 function func_226_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'No','=='))&&(ValC('comentario_noAcceso', 'Otra razón','=='))){Mostrar('Otrarazon', true);}else{Mostrar('Otrarazon',false);}}
 function func_227_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'No','=='))){Mostrar('Instfonoac', true);Mostrar('foto_noAccesible', true);Mostrar('Dictamennoaccesible', true);Mostrar('Instnoacce', true);Mostrar('comentario_noAcceso', true);}else{Mostrar('Instfonoac',false);Mostrar('foto_noAccesible',false);Mostrar('Dictamennoaccesible',false);Mostrar('Instnoacce',false);Mostrar('comentario_noAcceso',false);}}
 function func_228_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMedluz', 'Si','=='))){Mostrar('txt_Medidor', true);Mostrar('NotaFotoventanapri', true);Mostrar('foto_marco', true);Mostrar('NotaFotoInt', true);Mostrar('foto_interior', true);Mostrar('NotaFotoFrente', true);Mostrar('foto_vecino', true);Mostrar('NotaparaCapt', true);Mostrar('vec1', true);Mostrar('vec2', true);}else{Mostrar('txt_Medidor',false);Mostrar('NotaFotoventanapri',false);Mostrar('foto_marco',false);Mostrar('NotaFotoInt',false);Mostrar('foto_interior',false);Mostrar('NotaFotoFrente',false);Mostrar('foto_vecino',false);Mostrar('NotaparaCapt',false);Mostrar('vec1',false);Mostrar('vec2',false);}}
 function func_229_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'No','=='))&&(ValC('selMtto', 'No','=='))&&(ValC('selVentanas', 'Si','=='))&&(ValC('selGrafitt', 'Si','=='))){Mostrar('DictamenM4', true);}else{Mostrar('DictamenM4',false);}}
 function func_23_151xxx(){ if((ValC('CantidadPagos', '4','=='))){Mostrar('AceptaFPP4', true);}else{Mostrar('AceptaFPP4',false);}}
 function func_230_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'No','=='))&&(ValC('selMtto', 'Si','=='))){Mostrar('DictamenM2', true);}else{Mostrar('DictamenM2',false);}}
 function func_231_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'Si','=='))){Mostrar('DictamenM3', true);}else{Mostrar('DictamenM3',false);}}
 function func_232_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))){Mostrar('selMuebles', true);Mostrar('selMtto', true);Mostrar('selVentanas', true);Mostrar('selGrafitt', true);Mostrar('selMedluz', true);Mostrar('instfotositviv1', true);Mostrar('instimsitviv', true);Mostrar('NotaFotofachacomp', true);Mostrar('foto_fachada', true);Mostrar('NotaFotomedidor', true);Mostrar('Fotomedidor', true);}else{Mostrar('selMuebles',false);Mostrar('selMtto',false);Mostrar('selVentanas',false);Mostrar('selGrafitt',false);Mostrar('selMedluz',false);Mostrar('instfotositviv1',false);Mostrar('instimsitviv',false);Mostrar('NotaFotofachacomp',false);Mostrar('foto_fachada',false);Mostrar('NotaFotomedidor',false);Mostrar('Fotomedidor',false);}}
 function func_233_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))){Mostrar('vivHab', true);}else{Mostrar('vivHab',false);}}
 function func_234_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))){Mostrar('aclaracionB', true);}else{Mostrar('aclaracionB',false);}}
 function func_235_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))){Mostrar('aclaracionA', true);}else{Mostrar('aclaracionA',false);}}
 function func_236_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))&&(ValC('AcreditadoPropietario', 'No','=='))&&(ValC('ComproAcreditado2', 'No','=='))){Mostrar('DictamenVivInvadida2', true);}else{Mostrar('DictamenVivInvadida2',false);}}
 function func_237_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))&&(ValC('AcreditadoPropietario', 'No','=='))&&(ValC('ComproAcreditado2', 'Si','=='))){Mostrar('DictamenTraspaso', true);}else{Mostrar('DictamenTraspaso',false);}}
 function func_238_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))&&(ValC('AcreditadoPropietario', 'No','=='))){Mostrar('ComproAcreditado2', true);}else{Mostrar('ComproAcreditado2',false);}}
 function func_239_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))&&(ValC('AcreditadoPropietario', 'Si','=='))&&(ValC('FamiliarDirecto', 'No','=='))){Mostrar('DictamenVivInvadida', true);}else{Mostrar('DictamenVivInvadida',false);}}
 function func_24_151(){ if((ValC('CantidadPagos', '4','>='))){Mostrar('TX_PAGA4', true);}else{Mostrar('TX_PAGA4',false);}}
 function func_240_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))&&(ValC('AcreditadoPropietario', 'Si','=='))&&(ValC('FamiliarDirecto', 'Si','=='))){Mostrar('Parentesco', true);Mostrar('DictamenHabixfami', true);}else{Mostrar('Parentesco',false);Mostrar('DictamenHabixfami',false);}}
 function func_241_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))&&(ValC('AcreditadoPropietario', 'Si','=='))){Mostrar('FamiliarDirecto', true);}else{Mostrar('FamiliarDirecto',false);}}
 function func_242_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'No','=='))){Mostrar('AcreditadoPropietario', true);}else{Mostrar('AcreditadoPropietario',false);}}
 function func_243_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))){Mostrar('AcreditadoHabita', true);}else{Mostrar('AcreditadoHabita',false);}}
 function func_244_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))&&(ValC('tipoAclaracionB', 'Con_relacion_laboral','=='))){Mostrar('InstNomina', true);Mostrar('razSocAcla3', true);Mostrar('telEm', true);Mostrar('foto_reciboNomina', true);}else{Mostrar('InstNomina',false);Mostrar('razSocAcla3',false);Mostrar('telEm',false);Mostrar('foto_reciboNomina',false);}}
 function func_245_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))&&(ValC('tipoAclaracionB', 'Con_relacion_laborar','=='))){Mostrar('fechaIngAcla3', true);}else{Mostrar('fechaIngAcla3',false);}}
 function func_246_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))&&(ValC('tipoAclaracionB', 'Entrega_Aviso_Retencion','=='))){Mostrar('InstEvi', true);Mostrar('empresa_Retencion', true);Mostrar('foto_Retencion', true);}else{Mostrar('InstEvi',false);Mostrar('empresa_Retencion',false);Mostrar('foto_Retencion',false);}}
 function func_247_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))&&(ValC('tipoAclaracionB', 'Otra','=='))){Mostrar('otraAclaracionB', true);}else{Mostrar('otraAclaracionB',false);}}
 function func_248_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))&&(ValC('tipoAclaracionB', 'Pago_del_mes_actual','=='))){Mostrar('auxiliarPago', true);Mostrar('InstAclara2', true);Mostrar('folioAcla', true);Mostrar('montoRecuperar1', true);Mostrar('instPagoAcla', true);Mostrar('fechaPagoAcla', true);Mostrar('foto_pagoMesAct', true);}else{Mostrar('auxiliarPago',false);Mostrar('InstAclara2',false);Mostrar('folioAcla',false);Mostrar('montoRecuperar1',false);Mostrar('instPagoAcla',false);Mostrar('fechaPagoAcla',false);Mostrar('foto_pagoMesAct',false);}}
 function func_249_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))&&(ValC('tipoAclaracionB', 'Pago_del_mes_anterior','=='))){Mostrar('InstAclara3', true);Mostrar('folioAcla2', true);Mostrar('montoRecuperar2', true);Mostrar('instPagoAcla2', true);Mostrar('fechaPagoAcla2', true);Mostrar('foto_pagoMesAnte', true);Mostrar('auxiliarPagoMesAnterior', true);}else{Mostrar('InstAclara3',false);Mostrar('folioAcla2',false);Mostrar('montoRecuperar2',false);Mostrar('instPagoAcla2',false);Mostrar('fechaPagoAcla2',false);Mostrar('foto_pagoMesAnte',false);Mostrar('auxiliarPagoMesAnterior',false);}}
 function func_25_151xxx(){ if((ValC('CantidadPagos', '5','=='))){Mostrar('AceptaFPP5', true);}else{Mostrar('AceptaFPP5',false);}}
 function func_250_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('aclaracionB', 'Si','=='))){Mostrar('tipoAclaracionB', true);}else{Mostrar('tipoAclaracionB',false);}}
 function func_251_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('AcreditadoRegCan', '1','=='))&&(ValC('IN_SOLICITAR_SERVICIO_EMPLEO', 'Si','=='))){pcFormularios.GetTabByName('EncuestaSNE').SetEnabled(true);}else{pcFormularios.GetTabByName('EncuestaSNE').SetEnabled(false);}}
 function func_252_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaFPP', 'Si','=='))&&(ValC('InteresaFPP', 'Si','=='))){pcFormularios.GetTabByName('FPP').SetEnabled(true);}else{pcFormularios.GetTabByName('FPP').SetEnabled(false);}}
 function func_253_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))){Mostrar('RazonNoAcepta', true);}else{Mostrar('RazonNoAcepta',false);}}
 function func_254_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))&&(ValC('OtroParCelularSMS_SiAceptaSTM', 'Otro','=='))){Mostrar('OtroParCelularSMS_SiAceptaSTM', true);}else{Mostrar('OtroParCelularSMS_SiAceptaSTM',false);}}
 function func_255_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))){Mostrar('ValSMS_SiAceptaSTM', true);Mostrar('ParCelularSMS_SiAceptaSTM', true);Mostrar('QuienAceptaSTM2', true);Mostrar('CelularSMS_SiAceptaSTM', true);Mostrar('ConfirmeSMS_SiAceptaSTM', true);}else{Mostrar('ValSMS_SiAceptaSTM',false);Mostrar('ParCelularSMS_SiAceptaSTM',false);Mostrar('QuienAceptaSTM2',false);Mostrar('CelularSMS_SiAceptaSTM',false);Mostrar('ConfirmeSMS_SiAceptaSTM',false);}}
 function func_256_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))){Mostrar('IM_PRIMER_PAGO_SELEC', true);Mostrar('IM_SELEC_STM_PAGO_SUBSEC', true);Mostrar('CalcularMejorOpcion', true);Mostrar('IM_BENSELEC_STM', true);}else{Mostrar('IM_PRIMER_PAGO_SELEC',false);Mostrar('IM_SELEC_STM_PAGO_SUBSEC',false);Mostrar('CalcularMejorOpcion',false);Mostrar('IM_BENSELEC_STM',false);}}
 function func_257_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))){Mostrar('IM_OPC_SELEC', true);Mostrar('Instacrednopromesadepag', true);Mostrar('IM_OPC1_STM_PRIMER_PAGO', true);Mostrar('IM_OPC1_STM_PAGO_SUBSEC', true);Mostrar('Instacrednopromesadepag27', true);}else{Mostrar('IM_OPC_SELEC',false);Mostrar('Instacrednopromesadepag',false);Mostrar('IM_OPC1_STM_PRIMER_PAGO',false);Mostrar('IM_OPC1_STM_PAGO_SUBSEC',false);Mostrar('Instacrednopromesadepag27',false);}}
 function func_258_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))&&(ValC('ParCelularSMS_BCN', 'Otro','=='))){Mostrar('OtroParCelularSMS_BCN', true);}else{Mostrar('OtroParCelularSMS_BCN',false);}}
 function func_259_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'Si','=='))){pcFormularios.GetTabByName('SubFormDCP').SetEnabled(true);}else{pcFormularios.GetTabByName('SubFormDCP').SetEnabled(false);}}
 function func_26_151(){ if((ValC('CantidadPagos', '5','>='))){Mostrar('TX_PAGA5', true);}else{Mostrar('TX_PAGA5',false);}}
 function func_260_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaProrroga', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'Si','=='))){pcFormularios.GetTabByName('Prorroga').SetEnabled(true);}else{pcFormularios.GetTabByName('Prorroga').SetEnabled(false);}}
 function func_261_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'Si','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('ppagoOmisosAct', true);}else{Mostrar('ppagoOmisosAct',false);}}
 function func_262_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'Si','=='))&&(ValC('tipoAclaracionA', 'Defuncion','=='))){Mostrar('InstDefuncion', true);Mostrar('foto_def', true);Mostrar('InstDefuncion2', true);Mostrar('Dictamendefuncion', true);}else{Mostrar('InstDefuncion',false);Mostrar('foto_def',false);Mostrar('InstDefuncion2',false);Mostrar('Dictamendefuncion',false);}}
 function func_263_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'Si','=='))&&(ValC('tipoAclaracionA', 'Incapacidad','=='))){Mostrar('InstAclara1', true);Mostrar('foto_incapacidad', true);Mostrar('DictamenIncapacidad', true);}else{Mostrar('InstAclara1',false);Mostrar('foto_incapacidad',false);Mostrar('DictamenIncapacidad',false);}}
 function func_264_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'Si','=='))){Mostrar('tipoAclaracionA', true);}else{Mostrar('tipoAclaracionA',false);}}
 function func_265_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'No','=='))&&(ValC('VenderCasa', 'No','=='))&&(ValC('solicitudEspecial', 'DP','=='))){Mostrar('DictamenDacionPago', true);}else{Mostrar('DictamenDacionPago',false);}}
 function func_266_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'No','=='))&&(ValC('VenderCasa', 'No','=='))&&(ValC('solicitudEspecial', 'EP','=='))){Mostrar('DictamenEntregaPoder', true);}else{Mostrar('DictamenEntregaPoder',false);}}
 function func_267_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'No','=='))&&(ValC('VenderCasa', 'No','=='))){Mostrar('instnovendes', true);Mostrar('solicitudEspecial', true);}else{Mostrar('instnovendes',false);Mostrar('solicitudEspecial',false);}}
 function func_268_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'No','=='))&&(ValC('VenderCasa', 'Si','=='))){Mostrar('Instventasi', true);Mostrar('DictamenInivtaasist', true);}else{Mostrar('Instventasi',false);Mostrar('DictamenInivtaasist',false);}}
 function func_269_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'No','=='))){Mostrar('Instraznovivir', true);Mostrar('comentario_Noviv', true);Mostrar('VenderCasa', true);}else{Mostrar('Instraznovivir',false);Mostrar('comentario_Noviv',false);Mostrar('VenderCasa',false);}}
 function func_27_151xxx(){ if((ValC('CantidadPagos', '6','=='))){Mostrar('AceptaFPP6', true);}else{Mostrar('AceptaFPP6',false);}}
 function func_270_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('AcreditadoRegCan', '1','=='))){Mostrar('IN_SOLICITAR_SERVICIO_EMPLEO', true);}else{Mostrar('IN_SOLICITAR_SERVICIO_EMPLEO',false);}}
 function func_271_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'No','=='))&&(ValC('DicAplicaFPP', 'Si','=='))&&(ValC('InteresaFPP', 'Si','=='))){Mostrar('InstSubFormFPP', true);}else{Mostrar('InstSubFormFPP',false);}}
 function func_272_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'No','=='))&&(ValC('DicAplicaFPP', 'Si','=='))){Mostrar('InstFPP', true);Mostrar('InteresaFPP', true);}else{Mostrar('InstFPP',false);Mostrar('InteresaFPP',false);}}
 function func_273_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))){Mostrar('aceptaConv', true);}else{Mostrar('aceptaConv',false);}}
 function func_274_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))){Mostrar('aceptaBCN', true);}else{Mostrar('aceptaBCN',false);}}
 function func_275_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'No','=='))&&(ValC('DicCalificaProrroga', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))){Mostrar('aceptaProrr', true);}else{Mostrar('aceptaProrr',false);}}
 function func_276_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'Si','=='))){Mostrar('FechaPromesaSiSTM', true);Mostrar('InstFotoPPMens27', true);Mostrar('FotoIDanversoSTM', true);Mostrar('FotoIDreversoSTM', true);}else{Mostrar('FechaPromesaSiSTM',false);Mostrar('InstFotoPPMens27',false);Mostrar('FotoIDanversoSTM',false);Mostrar('FotoIDreversoSTM',false);}}
 function func_277_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))){Mostrar('InstSTM1', true);Mostrar('InstSTM', true);Mostrar('PagoQuePuede', true);Mostrar('InstSTM2', true);Mostrar('lbl_info', true);Mostrar('AceptaPagoSTM', true);}else{Mostrar('InstSTM1',false);Mostrar('InstSTM',false);Mostrar('PagoQuePuede',false);Mostrar('InstSTM2',false);Mostrar('lbl_info',false);Mostrar('AceptaPagoSTM',false);}}
 function func_278_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))&&(ValC('ParCelularSMS_STM', 'Otro','=='))){Mostrar('OtroParCelularSMS_STM', true);}else{Mostrar('OtroParCelularSMS_STM',false);}}
 function func_279_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'Si','=='))){Mostrar('ParCelularSMS_STM', true);Mostrar('FechaPromesaSTM', true);Mostrar('InstacredsiSTM', true);Mostrar('foto_ifeFrenteSTM', true);Mostrar('QuienAceptaSTM', true);Mostrar('CelularSMS_STM', true);Mostrar('ConfirmeSMS_STM', true);Mostrar('ValSMS_STM', true);Mostrar('foto_ifeRevSTM', true);}else{Mostrar('ParCelularSMS_STM',false);Mostrar('FechaPromesaSTM',false);Mostrar('InstacredsiSTM',false);Mostrar('foto_ifeFrenteSTM',false);Mostrar('QuienAceptaSTM',false);Mostrar('CelularSMS_STM',false);Mostrar('ConfirmeSMS_STM',false);Mostrar('ValSMS_STM',false);Mostrar('foto_ifeRevSTM',false);}}
 function func_28_151(){ if((ValC('CantidadPagos', '6','>='))){Mostrar('TX_PAGA6', true);}else{Mostrar('TX_PAGA6',false);}}
 function func_280_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaBCN', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'Si','=='))){Mostrar('foto_identificacionBCN', true);Mostrar('foto_identificacionBCN2', true);Mostrar('InstBCN11', true);Mostrar('BCNSigMeses', true);Mostrar('InstSBCN12', true);Mostrar('BCNMesActual', true);Mostrar('InstBCN5', true);Mostrar('QuienAceptaBCN', true);Mostrar('CelularSMS_BCN', true);Mostrar('ConfirmeSMS_BCN', true);Mostrar('ValSMS_BCN', true);Mostrar('ParCelularSMS_BCN', true);}else{Mostrar('foto_identificacionBCN',false);Mostrar('foto_identificacionBCN2',false);Mostrar('InstBCN11',false);Mostrar('BCNSigMeses',false);Mostrar('InstSBCN12',false);Mostrar('BCNMesActual',false);Mostrar('InstBCN5',false);Mostrar('QuienAceptaBCN',false);Mostrar('CelularSMS_BCN',false);Mostrar('ConfirmeSMS_BCN',false);Mostrar('ValSMS_BCN',false);Mostrar('ParCelularSMS_BCN',false);}}
 function func_281_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'Si','=='))){Mostrar('Instr2DCP3', true);Mostrar('Instr2DCP4', true);Mostrar('txt2Justificacion', true);Mostrar('Instr2DCP5', true);Mostrar('txt2Referencia1', true);Mostrar('txt2Referencia2', true);Mostrar('Dictamen2ESE', true);}else{Mostrar('Instr2DCP3',false);Mostrar('Instr2DCP4',false);Mostrar('txt2Justificacion',false);Mostrar('Instr2DCP5',false);Mostrar('txt2Referencia1',false);Mostrar('txt2Referencia2',false);Mostrar('Dictamen2ESE',false);}}
 function func_282_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'Si','=='))){Mostrar('Instr2DCP6', true);}else{Mostrar('Instr2DCP6',false);}}
 function func_283_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))){Mostrar('Inst2DCP1', true);Mostrar('AutorizaDCP', true);}else{Mostrar('Inst2DCP1',false);Mostrar('AutorizaDCP',false);}}
 function func_284_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaProrroga', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'Si','=='))){Mostrar('InstPrroga', true);}else{Mostrar('InstPrroga',false);}}
 function func_285_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('DicAplicaMttoFPP', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('Dictamenpromdepago', true);}else{Mostrar('Dictamenpromdepago',false);}}
 function func_286_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('DicAplicaMttoFPP', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('DictamenpromdepagoTOM', true);}else{Mostrar('DictamenpromdepagoTOM',false);}}
 function func_287_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('DicAplicaMttoFPP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('DictamenFPPMen', true);}else{Mostrar('DictamenFPPMen',false);}}
 function func_288_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('DicAplicaMttoFPP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('DictamenFPPTOM', true);}else{Mostrar('DictamenFPPTOM',false);}}
 function func_289_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'LIQ','=='))){Mostrar('Dictamenliquida', true);Mostrar('IM_MONTO_LIQUIDAR_CON_DESCUENTO', true);}else{Mostrar('Dictamenliquida',false);Mostrar('IM_MONTO_LIQUIDAR_CON_DESCUENTO',false);}}
 function func_29_152(){ if((ValC('ComidaFueraCasa', 'No','=='))){Mostrar('motivo_no_38', true);}else{Mostrar('motivo_no_38',false);}}
 function func_290_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'MEN','=='))){Mostrar('ppagoMensualAct', true);Mostrar('InstCantidad', true);}else{Mostrar('ppagoMensualAct',false);Mostrar('InstCantidad',false);}}
 function func_291_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))&&(ValC('montoPromesa', 'TOM','=='))){Mostrar('Instacredpagar', true);Mostrar('ppagoOmisosOms', true);Mostrar('Instacredpagmes', true);}else{Mostrar('Instacredpagar',false);Mostrar('ppagoOmisosOms',false);Mostrar('Instacredpagmes',false);}}
 function func_292_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'Si','=='))){Mostrar('insSolacreprom', true);Mostrar('FH_PROMESA_PAGO', true);Mostrar('Insmontprom', true);Mostrar('montoPromesa', true);}else{Mostrar('insSolacreprom',false);Mostrar('FH_PROMESA_PAGO',false);Mostrar('Insmontprom',false);Mostrar('montoPromesa',false);}}
 function func_293_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicPagoLiquid', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))){Mostrar('promPago', true);Mostrar('TX_DESCRIPCION_ETIQUETA2', true);}else{Mostrar('promPago',false);Mostrar('TX_DESCRIPCION_ETIQUETA2',false);}}
 function func_294_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))){Mostrar('Inspedirpreg', true);Mostrar('AcreditadoRegCan',false);}else{Mostrar('Inspedirpreg',false);Mostrar('AcreditadoRegCan',false);}}
 function func_295_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))){Mostrar('locAcrSol', true);Mostrar('desVivCasa', true);Mostrar('Instrco', true);}else{Mostrar('locAcrSol',false);Mostrar('desVivCasa',false);Mostrar('Instrco',false);}}
 function func_296_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))){Mostrar('locAcr', true);}else{Mostrar('locAcr',false);}}
 function func_297_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('otroUso', 'Si','=='))){Mostrar('notatotrousosi', true);Mostrar('folioEng', true);Mostrar('foto_otrouso1', true);Mostrar('comentario_otroUso', true);}else{Mostrar('notatotrousosi',false);Mostrar('folioEng',false);Mostrar('foto_otrouso1',false);Mostrar('comentario_otroUso',false);}}
 function func_298_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))){Mostrar('Alguienviv', true);Mostrar('Instotrouso', true);Mostrar('otroUso', true);Mostrar('Instsiacc', true);Mostrar('foto_vivienda', true);}else{Mostrar('Alguienviv',false);Mostrar('Instotrouso',false);Mostrar('otroUso',false);Mostrar('Instsiacc',false);Mostrar('foto_vivienda',false);}}
 function func_299_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('acce', 'Si','=='))&&(ValC('vivHab', 'Si','=='))){Mostrar('Instcasaaban', true);}else{Mostrar('Instcasaaban',false);}}
 function func_3_145(){ $('#BCNMesActual').val(Calc('BCNSigMeses+IM_SALDO_SEG_DAN'));}
 function func_30_152(){ if((ValC('ComidaFueraCasa', 'Si','=='))){Mostrar('monto_38', true);}else{Mostrar('monto_38',false);}}
 function func_300_149(){ if((ValC('vivLoc', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaProrroga', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))){Mostrar('InstacrednopromesaCONFPR', true);}else{Mostrar('InstacrednopromesaCONFPR',false);}}
 function func_301_149(){ if((ValC('vivLoc', 'Si','=='))){Mostrar('acce', true);}else{Mostrar('acce',false);}}
 function func_302_152(){ $('#TotalOcuviv').val(Calc('SolicitanteDCP+EsposoDCP+HijoDCP+PadresDCP+OtrosDCP'));}
 function func_31_152(){ if((ValC('CredDeudas', 'No','=='))){Mostrar('motivo_no_42', true);}else{Mostrar('motivo_no_42',false);}}
 function func_32_152(){ if((ValC('CredDeudas', 'Si','=='))){Mostrar('monto_42', true);}else{Mostrar('monto_42',false);}}
 function func_33_152(){ if((ValC('CuentaconCopiaIFE', 'Si','=='))&&(ValC('EntregoCopiaIFE', 'Si','=='))){Mostrar('documen_nota_credencial', true);}else{Mostrar('documen_nota_credencial',false);}}
 function func_34_152(){ if((ValC('CuentaconCopiaIFE', 'Si','=='))){Mostrar('MostroCopiaIFE', true);Mostrar('EntregoCopiaIFE', true);}else{Mostrar('MostroCopiaIFE',false);Mostrar('EntregoCopiaIFE',false);}}
 function func_35_152(){ if((ValC('CuentaPodNotarial', 'Si','=='))&&(ValC('EntCopPodNotarial', 'Si','=='))){Mostrar('documen_nota_notaria', true);}else{Mostrar('documen_nota_notaria',false);}}
 function func_36_152(){ if((ValC('CuentaPodNotarial', 'Si','=='))){Mostrar('MostroPodNotarial', true);Mostrar('EntCopPodNotarial', true);}else{Mostrar('MostroPodNotarial',false);Mostrar('EntCopPodNotarial',false);}}
 function func_37_152(){ if((ValC('CuentaRecibTel', 'Si','=='))&&(ValC('EntCopRecibTel', 'Si','=='))){Mostrar('documen_nota_telefono', true);}else{Mostrar('documen_nota_telefono',false);}}
 function func_38_152(){ if((ValC('CuentaRecibTel', 'Si','=='))){Mostrar('MostroRecibTel', true);Mostrar('EntCopRecibTel', true);}else{Mostrar('MostroRecibTel',false);Mostrar('EntCopRecibTel',false);}}
 function func_39_152(){ if((ValC('CuentaRecIng', 'Si','=='))&&(ValC('EntCopRecIng', 'Si','=='))){Mostrar('documen_nota_notaria2', true);}else{Mostrar('documen_nota_notaria2',false);}}
 function func_40_152(){ if((ValC('CuentaRecIng', 'Si','=='))){Mostrar('MostroRecIng', true);Mostrar('EntCopRecIng', true);}else{Mostrar('MostroRecIng',false);Mostrar('EntCopRecIng',false);}}
 function func_41_152(){ if((ValC('DCPpreg_1', 'OTRO','=='))){Mostrar('OtracausaDCP', true);}else{Mostrar('OtracausaDCP',false);}}
 function func_42_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('ParentesDCP', 'Otro','=='))){Mostrar('otroparentDCP', true);}else{Mostrar('otroparentDCP',false);}}
 function func_43_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('Porquesolusted', 'Divorcio','=='))&&(ValC('aportecomenDiv', 'Si','=='))){Mostrar('CantaportecoDiv', true);}else{Mostrar('CantaportecoDiv',false);}}
 function func_44_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('Porquesolusted', 'Divorcio','=='))){Mostrar('aportecomenDiv', true);}else{Mostrar('aportecomenDiv',false);}}
 function func_45_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('Porquesolusted', 'Otro','=='))&&(ValC('EdocivilDCP', 'Viudo(a)','=='))){Mostrar('Viudodesdecuan', true);}else{Mostrar('Viudodesdecuan',false);}}
 function func_46_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('Porquesolusted', 'Otro','=='))){Mostrar('Otrosolicita', true);Mostrar('EdocivilDCP', true);}else{Mostrar('Otrosolicita',false);Mostrar('EdocivilDCP',false);}}
 function func_47_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('Porquesolusted', 'Separacion','=='))&&(ValC('aportecomen', 'Si','=='))){Mostrar('Cantaporteco', true);}else{Mostrar('Cantaporteco',false);}}
 function func_48_152(){ if((ValC('DCPpreg_2', 'No','=='))&&(ValC('Porquesolusted', 'Separacion','=='))){Mostrar('aportecomen', true);}else{Mostrar('aportecomen',false);}}
 function func_49_152(){ if((ValC('DCPpreg_2', 'No','=='))){Mostrar('ApepatDCP', true);Mostrar('ApematDCP', true);Mostrar('NombresDCP', true);Mostrar('ParentesDCP', true);}else{Mostrar('ApepatDCP',false);Mostrar('ApematDCP',false);Mostrar('NombresDCP',false);Mostrar('ParentesDCP',false);}}
 function func_5_152(){ $('#ingresos_total_concubina').val(Calc('CantOtroCony+CantBecasCony+CantOtrCony+CantHonoCony+Cantemptempcon+CantPensCony+Cantagiocony+CantValesCony+Ingmensconyneto'));}
 function func_50_152(){ if((ValC('DCPpreg_5', 'No','=='))){Mostrar('Ocupaactdcp', true);}else{Mostrar('Ocupaactdcp',false);}}
 function func_51_146(){ if((ValC('DicAplicaSMS', 'Si','=='))){pcFormularios.GetTabByName('RegistroSMS').SetEnabled(true);}else{pcFormularios.GetTabByName('RegistroSMS').SetEnabled(false);}}
 function func_52_145(){ if((ValC('DicCalificaDCP', 'No','=='))&&(ValC('DicAplicaSTM', 'No','=='))&&(ValC('IN_OPCION_JUDICIAL', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('DictamenRechBCNMed', true);}else{Mostrar('DictamenRechBCNMed',false);}}
 function func_54_145(){ if((ValC('DicCalificaDCP', 'No','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('IN_OPCION_JUDICIAL', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('DictamenRechSTMMed', true);}else{Mostrar('DictamenRechSTMMed',false);}}
 function func_56_152(){ if((ValC('EdocivilDCP', 'Divorciado(a)','=='))){Mostrar('Divordesdecuan', true);}else{Mostrar('Divordesdecuan',false);}}
 function func_57_152(){ if((ValC('Educacion', 'No','=='))){Mostrar('motivo_no_36', true);}else{Mostrar('motivo_no_36',false);}}
 function func_58_152(){ if((ValC('Educacion', 'Si','=='))){Mostrar('monto_36', true);}else{Mostrar('monto_36',false);}}
 function func_59_152(){ if((ValC('egreso_telefonico_31', 'No','=='))){Mostrar('motivo_no_gasto', true);}else{Mostrar('motivo_no_gasto',false);}}
 function func_6_152(){ $('#gastos').val(Calc('Despensa_Alimentacion+Gas+Luz+Agua+monto_31+monto_32+monto_33+monto_34+monto_35+monto_36+monto_37+monto_38+monto_39+monto_40+monto_41+monto_42+monto_44+monto_45+monto_46+monto_47'));}
 function func_60_152(){ if((ValC('egreso_telefonico_31', 'Si','=='))){Mostrar('monto_31', true);}else{Mostrar('monto_31',false);}}
 function func_61_152(){ if((ValC('EmptempDCP', 'Si','=='))){Mostrar('CantmensEmptempDCP', true);Mostrar('Instperiodemptemp', true);Mostrar('PeriodiemptempDCP', true);}else{Mostrar('CantmensEmptempDCP',false);Mostrar('Instperiodemptemp',false);Mostrar('PeriodiemptempDCP',false);}}
 function func_62_152(){ if((ValC('Gasolina', 'No','=='))){Mostrar('motivo_no_34', true);}else{Mostrar('motivo_no_34',false);}}
 function func_63_152(){ if((ValC('Gasolina', 'Si','=='))){Mostrar('monto_34', true);}else{Mostrar('monto_34',false);}}
 function func_64_152(){ if((ValC('gastos', '0','>'))||(ValC('ingresos', '0','>'))){Mostrar('CalcularDCP', true);}else{Mostrar('CalcularDCP', true);}}
 function func_65_145(){ if((ValC('GestDesAnt', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'No','=='))&&(ValC('selMtto', 'No','=='))&&(ValC('selVentanas', 'No','=='))){Mostrar('DictamenM1', true);}else{Mostrar('DictamenM1',false);}}
 function func_67_145(){ if((ValC('GestDesAnt', 'No','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'No','=='))&&(ValC('selMtto', 'No','=='))&&(ValC('selVentanas', 'Si','=='))&&(ValC('selGrafitt', 'No','=='))){Mostrar('DictamenM5', true);}else{Mostrar('DictamenM5',false);}}
 function func_69_145(){ if((ValC('GestDesAnt', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'No','=='))&&(ValC('selMtto', 'No','=='))&&(ValC('selVentanas', 'No','=='))){Mostrar('DictamenPAE', true);}else{Mostrar('DictamenPAE',false);}}
 function func_7_151(){ if((ValC('AceptaFPP1', 'No','=='))||(ValC('AceptaFPP2', 'No','=='))||(ValC('AceptaFPP3', 'No','=='))||(ValC('AceptaFPP4', 'No','=='))||(ValC('AceptaFPP5', 'No','=='))||(ValC('AceptaFPP6', 'No','=='))){Mostrar('InstrFPP2', false);Mostrar('FH_PROMESA_PAGOFPP', false);Mostrar('InstrFPP3', false);Mostrar('InstrFPP4', false);Mostrar('DictamenFPP', false);Mostrar('fotoIFEFFPP', false);Mostrar('fotoIFERevFPP', false);Mostrar('InstrFPP5', false);Mostrar('fotoCartaAceptacionFPP', false);Mostrar('InstrFPP6', false);Mostrar('CelularSMS_FPP', false);Mostrar('ConfirmeSMS_FPP', false);Mostrar('ValSMS_FPP', false);Mostrar('InstrFPP23', true);Mostrar('ParCelularSMS_FPP', false);}else{Mostrar('InstrFPP2',true);Mostrar('FH_PROMESA_PAGOFPP',true);Mostrar('InstrFPP3',true);Mostrar('InstrFPP4',true);Mostrar('DictamenFPP',true);Mostrar('fotoIFEFFPP',true);Mostrar('fotoIFERevFPP',true);Mostrar('InstrFPP5',true);Mostrar('fotoCartaAceptacionFPP',true);Mostrar('InstrFPP6',true);Mostrar('CelularSMS_FPP',true);Mostrar('ConfirmeSMS_FPP',true);Mostrar('ValSMS_FPP',true);Mostrar('InstrFPP23',false);Mostrar('ParCelularSMS_FPP',true);}}
 function func_71_145(){ if((ValC('GestDesAnt', 'Si','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'Si','=='))&&(ValC('selMuebles', 'No','=='))&&(ValC('selMtto', 'No','=='))&&(ValC('selVentanas', 'Si','=='))&&(ValC('selGrafitt', 'No','=='))){Mostrar('DictamenPAE2', true);}else{Mostrar('DictamenPAE2',false);}}
 function func_73_152(){ if((ValC('HonorarDCP', 'Si','=='))){Mostrar('CantmenshonoDCP', true);Mostrar('Instperiodhono', true);Mostrar('PeriodishonoDCP', true);}else{Mostrar('CantmenshonoDCP',false);Mostrar('Instperiodhono',false);Mostrar('PeriodishonoDCP',false);}}
 function func_74_145(){ if((ValC('IDVISITA', '1','<='))&&(ValC('IN_OPCION_JUDICIAL', '1','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('InstrMediacionFin', true);}else{Mostrar('InstrMediacionFin',false);}}
 function func_75_149(){ if((ValC('IDVISITA', '1','<='))&&(ValC('IN_OPCION_JUDICIAL', '1','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('DictamenVisAdicionalNoESE', true);}else{Mostrar('DictamenVisAdicionalNoESE',false);}}
 function func_76_145(){ if((ValC('IDVISITA', '1','=='))&&(ValC('IN_OPCION_JUDICIAL', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))){Mostrar('DictamenRechDCPMed', true);}else{Mostrar('DictamenRechDCPMed',false);}}
 function func_78_145(){ if((ValC('IDVISITA', '1','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'Si','=='))){Mostrar('DictamenAcreditadoNoDisponible', true);}else{Mostrar('DictamenAcreditadoNoDisponible',false);}}
 function func_8_152(){ if((ValC('Activsoldcp', 'Otra actividad renumerada','=='))){Mostrar('Especifactdcp', true);}else{Mostrar('Especifactdcp',false);}}
 function func_80_145(){ if((ValC('IDVISITA', '1','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))){Mostrar('DicAplicaConvenio', true);}else{Mostrar('DicAplicaConvenio',false);}}
 function func_82_145(){ if((ValC('IDVISITA', '2','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'No','=='))){Mostrar('Lbl_SinContacto', true);Mostrar('foto_comNoAcre2', true);}else{Mostrar('Lbl_SinContacto',false);Mostrar('foto_comNoAcre2',false);}}
 function func_83_149(){ if((ValC('IDVISITA', '2','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'No','=='))){Mostrar('DictamenVisSContactoIDV2', true);Mostrar('Instcapotcom2', true);}else{Mostrar('DictamenVisSContactoIDV2',false);Mostrar('Instcapotcom2',false);}}
 function func_84_145(){ if((ValC('IDVISITA', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'Si','=='))){Mostrar('DictamenIDV2AcNoDisponible', true);}else{Mostrar('DictamenIDV2AcNoDisponible',false);}}
 function func_86_145(){ if((ValC('IDVISITA', '2','=='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'Si','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))){Mostrar('DictamenVisAdicional', true);}else{Mostrar('DictamenVisAdicional',false);}}
 function func_88_145(){ if((ValC('IDVISITA', '2','>='))&&(ValC('IN_OPCION_JUDICIAL', '1','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))){Mostrar('Inst2ESE1', true);}else{Mostrar('Inst2ESE1',false);}}
 function func_89_149(){ if((ValC('IDVISITA', '2','>='))&&(ValC('IN_OPCION_JUDICIAL', '1','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicCalificaDCP', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))){Mostrar('AutorizaESEV1', true);}else{Mostrar('AutorizaESEV1',false);}}
 function func_9_148(){ if((ValC('AgTelefonos', 'Si','=='))&&(ValC('TelTipoAgT1', 'Oficina','=='))){Mostrar('AgExtensionT1', true);}else{Mostrar('AgExtensionT1',false);}}
 function func_90_145(){ if((ValC('IDVISITA', '2','>='))&&(ValC('IN_OPCION_JUDICIAL', '1','<='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('DictamenMediacionFinal', true);}else{Mostrar('DictamenMediacionFinal',false);}}
 function func_92_145(){ if((ValC('IDVISITA', '2','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('InsMediacion2Final', true);Mostrar('InstrMediacion1Final', true);Mostrar('InsMediacionFinal', true);}else{Mostrar('InsMediacion2Final',false);Mostrar('InstrMediacion1Final',false);Mostrar('InsMediacionFinal',false);}}
 function func_93_149(){ if((ValC('IDVISITA', '2','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))&&(ValC('AutorizaDCP', 'No','=='))&&(ValC('AutorizaESEV1', 'No','=='))){Mostrar('comentario_MediacionFinal', true);Mostrar('fotoMediacionFinal', true);}else{Mostrar('comentario_MediacionFinal',false);Mostrar('fotoMediacionFinal',false);}}
 function func_94_145(){ if((ValC('IDVISITA', '3','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'No','=='))){Mostrar('InstrMediacion', true);}else{Mostrar('InstrMediacion',false);}}
 function func_95_149(){ if((ValC('IDVISITA', '3','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'No','=='))&&(ValC('vivHab', 'No','=='))){Mostrar('DictamenSC', true);}else{Mostrar('DictamenSC',false);}}
 function func_96_145(){ if((ValC('IDVISITA', '3','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'Si','=='))){Mostrar('InstrMediacionAH', true);}else{Mostrar('InstrMediacionAH',false);}}
 function func_97_149(){ if((ValC('IDVISITA', '3','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'No','=='))&&(ValC('AcreditadoHabita', 'Si','=='))){Mostrar('DictamenSC2', true);}else{Mostrar('DictamenSC2',false);}}
 function func_98_145(){ if((ValC('IDVISITA', '3','>='))&&(ValC('vivLoc', 'Si','=='))&&(ValC('acce', 'Si','=='))&&(ValC('Alguienviv', 'Si','=='))&&(ValC('locAcr', 'Si','=='))&&(ValC('desVivCasa', 'Si','=='))&&(ValC('aclaracionA', 'No','=='))&&(ValC('DicAplicaConvenio', 'Si','=='))&&(ValC('DicAplicaSTM', 'Si','=='))&&(ValC('InteresaFPP', 'No','=='))&&(ValC('promPago', 'No','=='))&&(ValC('aceptaProrr', 'No','=='))&&(ValC('aceptaBCN', 'No','=='))&&(ValC('aceptaConv', 'No','=='))&&(ValC('AceptaPagoSTM', 'No','=='))){Mostrar('DictamenVisAdicionalIDV3', true);}else{Mostrar('DictamenVisAdicionalIDV3',false);}}
 function FuncBtCalcularDCP998(){ var continuar = true; $("#FM,#FT,#IM_PRIMA_SEG_DAN,#IM_SALDO_SEG_DAN").each(function () { if (!$(this).val()) { alert("El campo " + $(this).attr("id") + " no fue proporcionado por el Instituto, favor de informar a soporte "); continuar = false; } }); if (continuar) { ingtotalesDcp = parseFloat($("#IngtotalesDCP").val()); gastos = parseFloat($("#gastos").val()); fm = parseFloat($("#FM").val()); ft = parseFloat($("#FT").val()); salarioMinimo = parseFloat($("#salarioMinimo").val()); segDanAct = parseFloat($("#IM_PRIMA_SEG_DAN").val()); segDanOms = parseFloat($("#IM_SALDO_SEG_DAN").val()); pagotemp = 0; factorFinal = 0; pagotemp = (ingtotalesDcp >= gastos) ? (gastos * 0.15) : (ingtotalesDcp * 0.15); if (pagotemp <= fm) { factorFinal = (fm >= (salarioMinimo * 6.8)) ? (fm + segDanAct + segDanOms) : ((salarioMinimo * 6.8) + segDanAct + segDanOms); finalizarQPagoTemp(); } else { if (pagotemp >= ft) { factorFinal = (ft >= (salarioMinimo * 6.8)) ? (ft + segDanAct + segDanOms) : ((salarioMinimo * 6.8) + segDanAct + segDanOms); finalizarQPagoTemp(); } else { if ((pagotemp * 1.20) > ft) { factorFinal = (pagotemp >= (salarioMinimo * 6.8)) ? (pagotemp + segDanAct + segDanOms) : ((salarioMinimo * 6.8) + segDanAct + segDanOms); finalizarQPagoTemp(); } else { $("#QPagoTempHeader").html("¿Acepta la cantidad de " + pagotemp * 1.20 + " (sin seguro) para el pago de los siguientes meses?"); window.QPagoTemp.Show(); } } } } } function QPagoTempSi() { factorFinal = ((pagotemp * 1.20) >= (salarioMinimo * 6.8)) ? ((pagotemp * 1.20) + segDanAct + segDanOms) : ((salarioMinimo * 6.8) + segDanAct + segDanOms); finalizarQPagoTemp(); } function QPagoTempNo() { factorFinal = (pagotemp >= (salarioMinimo * 6.8)) ? (pagotemp + segDanAct + segDanOms) : ((salarioMinimo * 6.8) + segDanAct + segDanOms); finalizarQPagoTemp(); } function finalizarQPagoTemp() { window.QPagoTemp.Hide(); $("#Res_factorDCP").val(factorFinal.toFixed(4)); $("#factorSinFee").val((factorFinal - segDanOms).toFixed(4));}
 function FuncBtCalcularMejorOpcion396(){ var pagoPuede = $("#PagoQuePuede").val();var i = 4;while (!isNaN(parseInt($("#IM_OPC" + i + "_STM").val(), 10))){if(pagoPuede >= parseInt($("#IM_OPC" + i + "_STM").val(), 10)){ i--; } else {i++;break;}}i = i == 0 ? 1 : i > 4? 4: i;OPC_STM = "IM_OPC" + (i) + "_STM";$("#IM_OPC_SELEC").val(OPC_STM);$("#IM_PRIMER_PAGO_SELEC").val($("#IM_OPC" + (i) + "_STM_PRIMER_PAGO").val());$("#IM_SELEC_STM_PAGO_SUBSEC").val($("#IM_OPC" + (i) + "_STM_PAGO_SUBSEC").val());$("#IM_BENSELEC_STM").val($("#IM_BEN" + (i) + "_STM").val());}
 function FuncMTelefonos(){ if((ValC("reqAct", "Si","==") && ValC("AgTelefonos", "Si","=="))){Mostrar("TelTipoAgT1",true);Mostrar("AgTelefonoT1",true);Mostrar("TelTipoAgT2",true);Mostrar("AgTelefonoT2",true);Mostrar("TelTipoAgT3",true);Mostrar("AgTelefonoT3",true);Mostrar("TelTipoAgT4",true);Mostrar("AgTelefonoT4",true);}else{Mostrar("TelTipoAgT1",false);Mostrar("AgTelefonoT1",false);Mostrar("TelTipoAgT2",false);Mostrar("AgTelefonoT2",false);Mostrar("TelTipoAgT3",false);Mostrar("AgTelefonoT3",false);Mostrar("TelTipoAgT4",false);Mostrar("AgTelefonoT4",false);}}
 function funcValSMS_BCN(){ $('#ValSMS_BCN').val(Calc('(CelularSMS_BCN)=(ConfirmeSMS_BCN)'));ValidaFormato($("#ValSMS_BCN"));}
 function funcValSMS_CONFPR(){ $('#ValSMS_CONFPR').val(Calc('(CelularSMS_CONFPR)=(ConfirmeSMS_CONFPR)'));ValidaFormato($("#ValSMS_CONFPR"));}
 function funcValSMS_CONFPRParcial(){ $('#ValSMS_CONFPRParcial').val(Calc('(CelularSMS_CONFPRParcial)=(ConfirmeSMS_CONFPRParcial)'));ValidaFormato($("#ValSMS_CONFPRParcial"));}
 function funcValSMS_DCP(){ $('#ValSMS_DCP').val(Calc('(CelularSMS_DCP)=(ConfirmeSMS_DCP)'));ValidaFormato($("#ValSMS_DCP"));}
 function funcValSMS_FPP(){ $('#ValSMS_FPP').val(Calc('(CelularSMS_FPP)=(ConfirmeSMS_FPP)'));ValidaFormato($("#ValSMS_FPP"));}
 function funcValSMS_Liquid(){ $('#ValSMS_Liquid').val(Calc('(CelularSMS_Liquid)=(ConfirmeSMS_Liquid)'));ValidaFormato($("#ValSMS_Liquid"));}
 function funcValSMS_Liquid2(){ $('#ValSMS_Liquid2').val(Calc('(CelularSMS_Liquid2)=(ConfirmeSMS_Liquid2)'));ValidaFormato($("#ValSMS_Liquid2"));}
 function funcValSMS_promdepagoTOM(){ $('#ValSMS_promdepagoTOM').val(Calc('(CelularSMS_promdepagoTOM)=(ConfirmeSMS_promdepagoTOM)'));ValidaFormato($("#ValSMS_promdepagoTOM"));}
 function funcValSMS_promdepagoTOM2(){ $('#ValSMS_promdepagoTOM2').val(Calc('(CelularSMS_promdepagoTOM2)=(ConfirmeSMS_promdepagoTOM2)'));ValidaFormato($("#ValSMS_promdepagoTOM2"));}
 function funcValSMS_ProPag(){ $('#ValSMS_ProPag').val(Calc('(CelularSMS_ProPag)=(ConfirmeSMS_ProPag)'));ValidaFormato($("#ValSMS_ProPag"));}
 function funcValSMS_ProPag2(){ $('#ValSMS_ProPag2').val(Calc('(CelularSMS_ProPag2)=(ConfirmeSMS_ProPag2)'));ValidaFormato($("#ValSMS_ProPag2"));}
 function funcValSMS_SiAceptaSTM(){ $('#ValSMS_SiAceptaSTM').val(Calc('(CelularSMS_SiAceptaSTM)=(ConfirmeSMS_SiAceptaSTM)'));ValidaFormato($("#ValSMS_SiAceptaSTM"));}
 function funcValSMS_STM(){ $('#ValSMS_STM').val(Calc('(CelularSMS_STM)=(ConfirmeSMS_STM)'));ValidaFormato($("#ValSMS_STM"));}
 function validaSMS(){ $('#ValCodSMS').val(Calc('(CodRecSMS)=(CodSMS)'));ValidaFormato($("#ValCodSMS"))}
