//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.42
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace eClock {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DS_UsuariosxE")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_UsuariosxE : System.Data.DataSet {
        
        private EC_PERSONASDataTable tableEC_PERSONAS;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_UsuariosxE() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_UsuariosxE(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["EC_PERSONAS"] != null)) {
                    base.Tables.Add(new EC_PERSONASDataTable(ds.Tables["EC_PERSONAS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public EC_PERSONASDataTable EC_PERSONAS {
            get {
                return this.tableEC_PERSONAS;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DS_UsuariosxE cln = ((DS_UsuariosxE)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["EC_PERSONAS"] != null)) {
                    base.Tables.Add(new EC_PERSONASDataTable(ds.Tables["EC_PERSONAS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableEC_PERSONAS = ((EC_PERSONASDataTable)(base.Tables["EC_PERSONAS"]));
            if ((initTable == true)) {
                if ((this.tableEC_PERSONAS != null)) {
                    this.tableEC_PERSONAS.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_UsuariosxE";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DS_UsuariosxE.xsd";
            this.Locale = new System.Globalization.CultureInfo("es-MX");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableEC_PERSONAS = new EC_PERSONASDataTable();
            base.Tables.Add(this.tableEC_PERSONAS);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeEC_PERSONAS() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DS_UsuariosxE ds = new DS_UsuariosxE();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void EC_PERSONASRowChangeEventHandler(object sender, EC_PERSONASRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class EC_PERSONASDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnPERSONA_ID;
            
            private System.Data.DataColumn columnPERSONA_LINK_ID;
            
            private System.Data.DataColumn columnTIPO_PERSONA_ID;
            
            private System.Data.DataColumn columnSUSCRIPCION_ID;
            
            private System.Data.DataColumn columnPERSONA_NOMBRE;
            
            private System.Data.DataColumn columnPERSONA_EMAIL;
            
            private System.Data.DataColumn columnPERSONA_BORRADO;
            
            private System.Data.DataColumn columnPERSONA_CLAVE;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASDataTable() {
                this.TableName = "EC_PERSONAS";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal EC_PERSONASDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected EC_PERSONASDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PERSONA_IDColumn {
                get {
                    return this.columnPERSONA_ID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PERSONA_LINK_IDColumn {
                get {
                    return this.columnPERSONA_LINK_ID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TIPO_PERSONA_IDColumn {
                get {
                    return this.columnTIPO_PERSONA_ID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SUSCRIPCION_IDColumn {
                get {
                    return this.columnSUSCRIPCION_ID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PERSONA_NOMBREColumn {
                get {
                    return this.columnPERSONA_NOMBRE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PERSONA_EMAILColumn {
                get {
                    return this.columnPERSONA_EMAIL;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PERSONA_BORRADOColumn {
                get {
                    return this.columnPERSONA_BORRADO;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PERSONA_CLAVEColumn {
                get {
                    return this.columnPERSONA_CLAVE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASRow this[int index] {
                get {
                    return ((EC_PERSONASRow)(this.Rows[index]));
                }
            }
            
            public event EC_PERSONASRowChangeEventHandler EC_PERSONASRowChanging;
            
            public event EC_PERSONASRowChangeEventHandler EC_PERSONASRowChanged;
            
            public event EC_PERSONASRowChangeEventHandler EC_PERSONASRowDeleting;
            
            public event EC_PERSONASRowChangeEventHandler EC_PERSONASRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddEC_PERSONASRow(EC_PERSONASRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASRow AddEC_PERSONASRow(decimal PERSONA_ID, decimal PERSONA_LINK_ID, decimal TIPO_PERSONA_ID, decimal SUSCRIPCION_ID, string PERSONA_NOMBRE, string PERSONA_EMAIL, decimal PERSONA_BORRADO, string PERSONA_CLAVE) {
                EC_PERSONASRow rowEC_PERSONASRow = ((EC_PERSONASRow)(this.NewRow()));
                rowEC_PERSONASRow.ItemArray = new object[] {
                        PERSONA_ID,
                        PERSONA_LINK_ID,
                        TIPO_PERSONA_ID,
                        SUSCRIPCION_ID,
                        PERSONA_NOMBRE,
                        PERSONA_EMAIL,
                        PERSONA_BORRADO,
                        PERSONA_CLAVE};
                this.Rows.Add(rowEC_PERSONASRow);
                return rowEC_PERSONASRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASRow FindByPERSONA_ID(decimal PERSONA_ID) {
                return ((EC_PERSONASRow)(this.Rows.Find(new object[] {
                            PERSONA_ID})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                EC_PERSONASDataTable cln = ((EC_PERSONASDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new EC_PERSONASDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnPERSONA_ID = base.Columns["PERSONA_ID"];
                this.columnPERSONA_LINK_ID = base.Columns["PERSONA_LINK_ID"];
                this.columnTIPO_PERSONA_ID = base.Columns["TIPO_PERSONA_ID"];
                this.columnSUSCRIPCION_ID = base.Columns["SUSCRIPCION_ID"];
                this.columnPERSONA_NOMBRE = base.Columns["PERSONA_NOMBRE"];
                this.columnPERSONA_EMAIL = base.Columns["PERSONA_EMAIL"];
                this.columnPERSONA_BORRADO = base.Columns["PERSONA_BORRADO"];
                this.columnPERSONA_CLAVE = base.Columns["PERSONA_CLAVE"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnPERSONA_ID = new System.Data.DataColumn("PERSONA_ID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPERSONA_ID);
                this.columnPERSONA_LINK_ID = new System.Data.DataColumn("PERSONA_LINK_ID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPERSONA_LINK_ID);
                this.columnTIPO_PERSONA_ID = new System.Data.DataColumn("TIPO_PERSONA_ID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIPO_PERSONA_ID);
                this.columnSUSCRIPCION_ID = new System.Data.DataColumn("SUSCRIPCION_ID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUSCRIPCION_ID);
                this.columnPERSONA_NOMBRE = new System.Data.DataColumn("PERSONA_NOMBRE", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPERSONA_NOMBRE);
                this.columnPERSONA_EMAIL = new System.Data.DataColumn("PERSONA_EMAIL", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPERSONA_EMAIL);
                this.columnPERSONA_BORRADO = new System.Data.DataColumn("PERSONA_BORRADO", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPERSONA_BORRADO);
                this.columnPERSONA_CLAVE = new System.Data.DataColumn("PERSONA_CLAVE", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPERSONA_CLAVE);
                this.Constraints.Add(new System.Data.UniqueConstraint("Constraint1", new System.Data.DataColumn[] {
                                this.columnPERSONA_ID}, true));
                this.columnPERSONA_ID.AllowDBNull = false;
                this.columnPERSONA_ID.Unique = true;
                this.columnPERSONA_LINK_ID.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASRow NewEC_PERSONASRow() {
                return ((EC_PERSONASRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new EC_PERSONASRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(EC_PERSONASRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.EC_PERSONASRowChanged != null)) {
                    this.EC_PERSONASRowChanged(this, new EC_PERSONASRowChangeEvent(((EC_PERSONASRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.EC_PERSONASRowChanging != null)) {
                    this.EC_PERSONASRowChanging(this, new EC_PERSONASRowChangeEvent(((EC_PERSONASRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.EC_PERSONASRowDeleted != null)) {
                    this.EC_PERSONASRowDeleted(this, new EC_PERSONASRowChangeEvent(((EC_PERSONASRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.EC_PERSONASRowDeleting != null)) {
                    this.EC_PERSONASRowDeleting(this, new EC_PERSONASRowChangeEvent(((EC_PERSONASRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveEC_PERSONASRow(EC_PERSONASRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DS_UsuariosxE ds = new DS_UsuariosxE();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "EC_PERSONASDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class EC_PERSONASRow : System.Data.DataRow {
            
            private EC_PERSONASDataTable tableEC_PERSONAS;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal EC_PERSONASRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableEC_PERSONAS = ((EC_PERSONASDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal PERSONA_ID {
                get {
                    return ((decimal)(this[this.tableEC_PERSONAS.PERSONA_IDColumn]));
                }
                set {
                    this[this.tableEC_PERSONAS.PERSONA_IDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal PERSONA_LINK_ID {
                get {
                    return ((decimal)(this[this.tableEC_PERSONAS.PERSONA_LINK_IDColumn]));
                }
                set {
                    this[this.tableEC_PERSONAS.PERSONA_LINK_IDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TIPO_PERSONA_ID {
                get {
                    try {
                        return ((decimal)(this[this.tableEC_PERSONAS.TIPO_PERSONA_IDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("El valor de la columna \'TIPO_PERSONA_ID\' de la tabla \'EC_PERSONAS\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEC_PERSONAS.TIPO_PERSONA_IDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SUSCRIPCION_ID {
                get {
                    try {
                        return ((decimal)(this[this.tableEC_PERSONAS.SUSCRIPCION_IDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("El valor de la columna \'SUSCRIPCION_ID\' de la tabla \'EC_PERSONAS\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEC_PERSONAS.SUSCRIPCION_IDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PERSONA_NOMBRE {
                get {
                    try {
                        return ((string)(this[this.tableEC_PERSONAS.PERSONA_NOMBREColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        return "";//      throw new System.Data.StrongTypingException("El valor de la columna \'PERSONA_NOMBRE\' de la tabla \'EC_PERSONAS\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEC_PERSONAS.PERSONA_NOMBREColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PERSONA_EMAIL {
                get {
                    try {
                        return ((string)(this[this.tableEC_PERSONAS.PERSONA_EMAILColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("El valor de la columna \'PERSONA_EMAIL\' de la tabla \'EC_PERSONAS\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEC_PERSONAS.PERSONA_EMAILColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal PERSONA_BORRADO {
                get {
                    try {
                        return ((decimal)(this[this.tableEC_PERSONAS.PERSONA_BORRADOColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("El valor de la columna \'PERSONA_BORRADO\' de la tabla \'EC_PERSONAS\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEC_PERSONAS.PERSONA_BORRADOColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PERSONA_CLAVE {
                get {
                    try {
                        return ((string)(this[this.tableEC_PERSONAS.PERSONA_CLAVEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("El valor de la columna \'PERSONA_CLAVE\' de la tabla \'EC_PERSONAS\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEC_PERSONAS.PERSONA_CLAVEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTIPO_PERSONA_IDNull() {
                return this.IsNull(this.tableEC_PERSONAS.TIPO_PERSONA_IDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTIPO_PERSONA_IDNull() {
                this[this.tableEC_PERSONAS.TIPO_PERSONA_IDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSUSCRIPCION_IDNull() {
                return this.IsNull(this.tableEC_PERSONAS.SUSCRIPCION_IDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSUSCRIPCION_IDNull() {
                this[this.tableEC_PERSONAS.SUSCRIPCION_IDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPERSONA_NOMBRENull() {
                return this.IsNull(this.tableEC_PERSONAS.PERSONA_NOMBREColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPERSONA_NOMBRENull() {
                this[this.tableEC_PERSONAS.PERSONA_NOMBREColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPERSONA_EMAILNull() {
                return this.IsNull(this.tableEC_PERSONAS.PERSONA_EMAILColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPERSONA_EMAILNull() {
                this[this.tableEC_PERSONAS.PERSONA_EMAILColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPERSONA_BORRADONull() {
                return this.IsNull(this.tableEC_PERSONAS.PERSONA_BORRADOColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPERSONA_BORRADONull() {
                this[this.tableEC_PERSONAS.PERSONA_BORRADOColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPERSONA_CLAVENull() {
                return this.IsNull(this.tableEC_PERSONAS.PERSONA_CLAVEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPERSONA_CLAVENull() {
                this[this.tableEC_PERSONAS.PERSONA_CLAVEColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class EC_PERSONASRowChangeEvent : System.EventArgs {
            
            private EC_PERSONASRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASRowChangeEvent(EC_PERSONASRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public EC_PERSONASRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591