/* Updates a columnas de EC_TABLAS de eClock .*/
/* Este archivo se ejecuta una sola vez de forma manual 
   para llenar los datos predeterminados que se encuentran 
   en eClock.
   Se debe ejecutar despues de instalar eClock */

/* Este código SQL llena las columnas para que funcionen correctamente
	algunos metódos de eClock (como los catálogos de los ComboBox) */

/* EC_ALMACEN_VEC */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Almacen Vectores', 
	TABLA_PLURAL = 'Almacenes de Vectores', 
	TABLA_SINGULAR = 'Almacen de Vectores', 
	TABLA_DESCRIPCION = 'Almacen de huella', 
	TABLA_LLAVE = 'ALMACEN_VEC_ID', 
	TABLA_GRID_QRY = '', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_ALMACEN_VEC';
/* EC_CAMPOS */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Campos', 
	TABLA_PLURAL = 'Campos', 
	TABLA_SINGULAR = 'Campo', 
	TABLA_DESCRIPCION = 'Configuración de formatos y nombres de campos', 
	TABLA_LLAVE = 'CAMPO_NOMBRE', 
	TABLA_GRID_QRY = '', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_CAMPOS';
/* EC_CONFIG_USUARIO */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Configuracion de Usuario', 
	TABLA_PLURAL = 'Configuraciones de Usuario', 
	TABLA_SINGULAR = 'Configuración de Usuario', 
	TABLA_DESCRIPCION = 'Contiene variables y sus correspondientes valores para las configuraciones de un usuario', 
	TABLA_LLAVE = 'CONFIG_USUARIO_ID', 
	TABLA_GRID_QRY = 'SELECT CONFIG_USUARIO_ID, USUARIO_ID, CONFIG_USUARIO_VARIABLE, CONFIG_USUARIO_VALOR, CONFIG_USUARIO_VALOR_BIN FROM EC_CONFIG_USUARIO', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_CONFIG_USUARIO';
/* EC_EDO_SUSCRIPCION */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Estado Suscripcion', 
	TABLA_PLURAL = 'Estados de las Suscripciones', 
	TABLA_SINGULAR = 'Estado de la Suscripcion', 
	TABLA_DESCRIPCION = 'Contiene la informacion relevante al estado de la suscripcion seleccionada', 
	TABLA_LLAVE = 'EDO_SUSCRIPCION_ID', 
	TABLA_GRID_QRY = '', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_EDO_SUSCRIPCION';
/* EC_PERIODOS */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Periodos', 
	TABLA_PLURAL = 'Periodos', 
	TABLA_SINGULAR = 'Periodo', 
	TABLA_DESCRIPCION = 'Contiene información sobre los periodos de nómina', 
	TABLA_LLAVE = 'PERIODO_ID', 
	TABLA_GRID_QRY = 'SELECT EC_PERIODOS.PERIODO_ID, EC_PERIODOS.PERIODO_NO, EC_PERIODOS_N.PERIODO_N_NOM, EC_PERIODOS.PERIODO_NOM_INICIO, EC_PERIODOS.PERIODO_NOM_FIN, EC_PERIODOS.PERIODO_ASIS_INICIO, EC_PERIODOS.PERIODO_ASIS_FIN, EC_EDO_PERIODO.EDO_PERIODO_NOMBRE FROM EC_EDO_PERIODO INNER JOIN EC_PERIODOS ON EC_EDO_PERIODO.EDO_PERIODO_ID = EC_PERIODOS.EDO_PERIODO_ID INNER JOIN EC_PERIODOS_N ON EC_PERIODOS.PERIODO_N_ID = EC_PERIODOS_N.PERIODO_N_ID WHERE (EC_PERIODOS.PERIODO_NOM_INICIO > DATEADD(month, - 2, GETDATE()) AND EC_PERIODOS.PERIODO_NOM_INICIO < DATEADD(month, 6, GETDATE()))', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_PERIODOS';
/* EC_PERSONAS */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Empleados', 
	TABLA_PLURAL = 'Empleados', 
	TABLA_SINGULAR = 'Empleado', 
	TABLA_DESCRIPCION = 'Catalogo de empleados', 
	TABLA_LLAVE = 'PERSONA_ID', 
	TABLA_GRID_QRY = 'SELECT EC_PERSONAS_DATOS.PERSONA_ID, EC_PERSONAS_DATOS.PERSONA_LINK_ID, EC_PERSONAS_DATOS.NOMBRE_COMPLETO,  EC_PERSONAS_DATOS.NOMBRE, EC_PERSONAS_DATOS.APATERNO, EC_PERSONAS_DATOS.AMATERNO, EC_PERSONAS_DATOS.RFC,  EC_PERSONAS_DATOS.CURP, EC_PERSONAS_DATOS.IMSS, EC_PERSONAS_DATOS.ESTUDIOS, EC_PERSONAS_DATOS.SEXO,  EC_PERSONAS_DATOS.NACIONALIDAD, EC_PERSONAS_DATOS.FECHA_INGRESO, EC_PERSONAS_DATOS.FECHA_BAJA,  EC_PERSONAS_DATOS.CENTRO_DE_COSTOS, EC_PERSONAS_DATOS.AREA, EC_PERSONAS_DATOS.DEPARTAMENTO,  EC_PERSONAS_DATOS.PUESTO, EC_PERSONAS_DATOS.GRUPO, EC_PERSONAS_DATOS.NO_CREDENCIAL,  EC_PERSONAS_DATOS.LINEA_PRODUCCION, EC_PERSONAS_DATOS.COMPANIA, EC_PERSONAS_DATOS.DIVISION,  EC_PERSONAS_DATOS.TIPO_NOMINA, PERSONA_BORRADO FROM EC_PERSONAS INNER JOIN EC_PERSONAS_DATOS ON EC_PERSONAS.PERSONA_ID = EC_PERSONAS_DATOS.PERSONA_ID INNER JOIN EC_TURNOS ON EC_PERSONAS.TURNO_ID = EC_TURNOS.TURNO_ID', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = 'PERSONA_BORRADO', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = 'EC_TURNOS', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_PERSONAS';
/* EC_SITIOS */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Sitios', 
	TABLA_PLURAL = 'Sitios', 
	TABLA_SINGULAR = 'Sitio', 
	TABLA_DESCRIPCION = 'Contiene el listado de sitios o lugares de trabajo al que pertenecen las terminales', 
	TABLA_LLAVE = 'SITIO_ID', 
	TABLA_GRID_QRY = 'SELECT SITIO_ID, SITIO_NOMBRE, SITIO_CONSULTA, SITIO_HDESDE_SVEC, SITIO_HHASTA_SVEC, SITIO_SEGUNDOS_SYNC, SITIO_BORRADO FROM EC_SITIOS', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_SITIOS';
/* EC_SUSCRIP_PRECIOS */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Precios Suscripcion', 
	TABLA_PLURAL = 'Precios Suscripcion', 
	TABLA_SINGULAR = 'Precio Suscripcion', 
	TABLA_DESCRIPCION = 'Descripcion del precio del tipo de suscripción', 
	TABLA_LLAVE = 'SUSCRIP_PRECIO_ID', 
	TABLA_GRID_QRY = '', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_SUSCRIP_PRECIOS';	
/* EC_SUSCRIPCION */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Suscripcion', 
	TABLA_PLURAL = 'Suscripciones', 
	TABLA_SINGULAR = 'Suscripcion', 
	TABLA_DESCRIPCION = 'Datos de la suscripcion', 
	TABLA_LLAVE = 'SUSCRIPCION_ID', 
	TABLA_GRID_QRY = '', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = '', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_SUSCRIPCION';
/* EC_TIPO_NOMINA */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Tipos de nomina', 
	TABLA_PLURAL = 'Tipos de nominas', 
	TABLA_SINGULAR = 'Tipo de nomina', 
	TABLA_DESCRIPCION = 'Datos de la nomina', 
	TABLA_LLAVE = 'TIPO_NOMINA_ID', 
	TABLA_GRID_QRY = 'SELECT TIPO_NOMINA_ID, PERIODO_N_NOM, TIPO_NOMINA_NOMBRE, TIPO_NOMINA_IDEX, TIPO_NOMINA_BORRADO FROM EC_TIPO_NOMINA, EC_PERIODOS_N  WHERE EC_TIPO_NOMINA.PERIODO_N_ID = EC_PERIODOS_N.PERIODO_N_ID', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = 'TIPO_NOMINA_BORRADO', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_TIPO_NOMINA';
/* EC_TIPO_TERMINAL_ACCESO */
UPDATE EC_TABLAS
	SET TABLA_ETIQUETA = 'Tipo de terminal', 
	TABLA_PLURAL = 'Tipo Terminal', 
	TABLA_SINGULAR = 'Tipos de Terminales', 
	TABLA_DESCRIPCION = 'Tipo de terminal de acceso', 
	TABLA_LLAVE = '', 
	TABLA_GRID_QRY = '', 
	TABLA_ICONO16 = '', 
	TABLA_ICONO24 = '', 
	TABLA_ICONO32 = '', 
	TABLA_ICONO64 = '', 
	TABLA_C_BORRADO = 'TIPO_NOMINA_BORRADO', 
	TABLA_HISTORICO = 0, 
	TABLA_NUEVO = 1, 
	TABLA_EDICION = 1, 
	TABLA_BORRAR = 1, 
	TABLA_HIJOS = '', 
	TABLA_VAL_SUSCRIPCION = 1, 
	TABLA_BORRADO = 0
	WHERE TABLA_NOMBRE = 'EC_TIPO_TERMINAL_ACCESO';
	
/* Se llena el Identificador de los catálogos para que se llenen correctamente los Combos */
UPDATE EC_CAMPOS SET CATALOGO_ID = '30' WHERE CAMPO_NOMBRE = 'ALMACEN_VEC_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '28' WHERE CAMPO_NOMBRE = 'CAMPO_NOMBRE';
UPDATE EC_CAMPOS SET CATALOGO_ID = '1' WHERE CAMPO_NOMBRE = 'CAMPO2';
UPDATE EC_CAMPOS SET CATALOGO_ID = '8' WHERE CAMPO_NOMBRE = 'CATALOGO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '48' WHERE CAMPO_NOMBRE = 'CONFIG_USUARIO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '43' WHERE CAMPO_NOMBRE = 'EDO_PERIODO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '51' WHERE CAMPO_NOMBRE = 'EDO_SUSCRIPCION_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '32' WHERE CAMPO_NOMBRE = 'FORMATO_REP_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '9' WHERE CAMPO_NOMBRE = 'MASCARA_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '31' WHERE CAMPO_NOMBRE = 'MODELO_TERMINAL_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '14' WHERE CAMPO_NOMBRE = 'PERFIL_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '47' WHERE CAMPO_NOMBRE = 'PERIODO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '34' WHERE CAMPO_NOMBRE = 'REPORTE_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '29' WHERE CAMPO_NOMBRE = 'SITIO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '50' WHERE CAMPO_NOMBRE = 'SUSCRIP_PRECIO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '52' WHERE CAMPO_NOMBRE = 'SUSCRIPCION_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '15' WHERE CAMPO_NOMBRE = 'TERMINAL_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '45' WHERE CAMPO_NOMBRE = 'TIPO_ALMACEN_INC_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '10' WHERE CAMPO_NOMBRE = 'TIPO_DATO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '35' WHERE CAMPO_NOMBRE = 'TIPO_FALTA_EX_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '24' WHERE CAMPO_NOMBRE = 'TIPO_INC_SIS_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '23' WHERE CAMPO_NOMBRE = 'TIPO_INCIDENCIA_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '36' WHERE CAMPO_NOMBRE = 'TIPO_INCIDENCIAS_EX_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '40' WHERE CAMPO_NOMBRE = 'TIPO_PERMISO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '25' WHERE CAMPO_NOMBRE = 'TIPO_PERSONA_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '26' WHERE CAMPO_NOMBRE = 'TIPO_TECNOLOGIA_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '27' WHERE CAMPO_NOMBRE = 'TIPO_TERM_DEXTRAS_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '46' WHERE CAMPO_NOMBRE = 'TIPO_TERMINAL_ACCESO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '13' WHERE CAMPO_NOMBRE = 'TIPO_TURNO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '12' WHERE CAMPO_NOMBRE = 'TURNO_ID';
UPDATE EC_CAMPOS SET CATALOGO_ID = '33' WHERE CAMPO_NOMBRE = 'USUARIO_ID';