SELECT t.PERSONA_ID, @CAMPOS_EXTRAS@ FALTAS,NO_FALTAS_ES,RETARDOS_NORMALES,RETARDOS_MENORES,RETARDOS_MAYORES,RETARDOS_SUPERIORES,SALIDAS_TEMPRANO,
convert(decimal,FALTAS) +
convert(decimal,RETARDOS_NORMALES / 4) * 0.5 + 
convert(decimal,RETARDOS_MENORES / 2) * 0.5 + 
convert(decimal,RETARDOS_MAYORES / 2) * 0.5 +
convert(decimal,RETARDOS_SUPERIORES) +
convert(decimal,NO_FALTAS_ES) * 0.5 +
convert(decimal,SALIDAS_TEMPRANO) * 0.5 +
convert(decimal,((RETARDOS_NORMALES % 4) / 3 + RETARDOS_MENORES %2)/2)*0.5
AS FALTAS_DESCUENTO
FROM
(SELECT     PERSONA_ID, sum(case when TIPO_INC_SIS_ID = 12 then 1 else 0 end) as FALTAS,
sum(case when TIPO_INC_SIS_ID = 3 OR  TIPO_INC_SIS_ID = 4 OR 
TIPO_INC_SIS_ID = 6 OR TIPO_INC_SIS_ID = 7 OR TIPO_INC_SIS_ID = 8 OR TIPO_INC_SIS_ID = 17 OR 
TIPO_INC_SIS_ID = 20 OR TIPO_INC_SIS_ID = 23 then 1 else 0 end) as NO_FALTAS_ES,
sum(case when TIPO_INC_SIS_ID = 2 or  TIPO_INC_SIS_ID = 8 or  TIPO_INC_SIS_ID = 9 then 1 else 0 end) as RETARDOS_NORMALES,
sum(case when TIPO_INC_SIS_ID = 16 or  TIPO_INC_SIS_ID = 17 or  TIPO_INC_SIS_ID = 18 then 1 else 0 end) as RETARDOS_MENORES,
sum(case when TIPO_INC_SIS_ID = 19 or  TIPO_INC_SIS_ID = 20 or  TIPO_INC_SIS_ID = 21 then 1 else 0 end) as RETARDOS_MAYORES,
sum(case when TIPO_INC_SIS_ID = 22 or  TIPO_INC_SIS_ID = 23 or  TIPO_INC_SIS_ID = 24 then 1 else 0 end) as RETARDOS_SUPERIORES,
sum(case when TIPO_INC_SIS_ID = 5 or  TIPO_INC_SIS_ID = 7 or  TIPO_INC_SIS_ID = 9 
or TIPO_INC_SIS_ID = 18 or  TIPO_INC_SIS_ID = 21 or  TIPO_INC_SIS_ID = 24
then 1 else 0 end) as SALIDAS_TEMPRANO
FROM         EC_PERSONAS_DIARIO
WHERE    PERSONA_DIARIO_FECHA >= @FECHA_INICIAL@ AND PERSONA_DIARIO_FECHA < @FECHA_FINAL@ @FILTRO_PERSONAS@
GROUP BY PERSONA_ID) t, EC_PERSONAS WHERE t.PERSONA_ID = EC_PERSONAS.PERSONA_ID