DROP VIEW EC_V_TURNOS_DIAS;
CREATE VIEW EC_V_TURNOS_DIAS
AS                      
	SELECT     TURNO_DIA_ID, MIN(Turno) AS Turno, MIN(turno_id) as turno_id, MIN (TURNO_COLOR) AS TURNO_COLOR
	FROM         (SELECT     EC_TURNOS_DIA.TURNO_DIA_ID, CASE WHEN eC_TURNOS.TURNO_ID > 0 THEN RTRIM(eC_TURNOS.TURNO_NOMBRE) 
    WHEN EC_TURNOS_DIA.TURNO_DIA_ID = 0 THEN ' ?' WHEN EC_TURNOS_DIA.TURNO_DIA_ID = - 1 THEN ' -' ELSE
    CONVERT(CHAR(5), TURNO_DIA_HE, 108) + '-' + CONVERT(CHAR(5), TURNO_DIA_HS, 108) END AS TURNO, eC_turnos.turno_id,
	TURNO_COLOR
    FROM          eC_TURNOS RIGHT OUTER JOIN
        eC_TURNOS_SEMANAL_DIA ON eC_TURNOS.TURNO_ID = eC_TURNOS_SEMANAL_DIA.TURNO_ID RIGHT OUTER JOIN
        EC_TURNOS_DIA ON eC_TURNOS_SEMANAL_DIA.TURNO_DIA_ID = EC_TURNOS_DIA.TURNO_DIA_ID) Turnos
GROUP BY TURNO_DIA_ID;

-- Crea una vista para mostrar la incidencia cargada en determinado dia, el horario de entrada y salida
--y la hora de entrada y salida
DROP VIEW EC_V_PERSONAS_DIARIO;
CREATE VIEW EC_V_PERSONAS_DIARIO
AS
SELECT     EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID, 
                      CASE eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ID WHEN 0 THEN eC_TIPO_INC_SIS.TIPO_INC_SIS_NOMBRE ELSE RTRIM(eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_NOMBRE)
                       END AS INCIDENCIA_NOMBRE, CASE WHEN eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ID = 0 AND eC_TIPO_INC_SIS.TIPO_INC_SIS_ABR IS NOT NULL 
                      THEN eC_TIPO_INC_SIS.TIPO_INC_SIS_ABR WHEN eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ID > 0 AND 
                      eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ABR IS NOT NULL THEN eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ABR ELSE '' END AS INCIDENCIA_ABR, 
					  CASE eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ID WHEN 0 THEN eC_TIPO_INC_SIS.TIPO_INC_SIS_COLOR ELSE EC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_COLOR
                       END AS INCIDENCIA_COLOR,
                      EC_V_TURNOS_DIAS.TURNO, EC_V_TURNOS_DIAS.TURNO_COLOR, eC_ACCESOS.ACCESO_FECHAHORA AS ENTRADA, 
                      eC_ACCESOS_1.ACCESO_FECHAHORA AS SALIDA, CASE WHEN eC_ACCESOS.ACCESO_FECHAHORA IS NULL AND 
                      eC_ACCESOS_1.ACCESO_FECHAHORA IS NULL THEN ' ? - ?' WHEN eC_ACCESOS_1.ACCESO_FECHAHORA IS NULL THEN TO_CHAR(
                      eC_ACCESOS.ACCESO_FECHAHORA - EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA,'HH24:MI') || '- ? ' WHEN eC_ACCESOS.ACCESO_FECHAHORA IS NULL
                       THEN ' ? -' || TO_CHAR(eC_ACCESOS_1.ACCESO_FECHAHORA - EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA,'HH24:MI') ELSE TO_CHAR(
                      eC_ACCESOS.ACCESO_FECHAHORA - EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA,'HH24:MI') || '-' || TO_CHAR(
                      eC_ACCESOS_1.ACCESO_FECHAHORA - EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA,'HH24:MI') END AS ENTRADASALIDA, 
                      EC_V_TURNOS_DIAS.TURNO_ID, EC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ID, INCIDENCIA_COMENTARIO
FROM         eC_ACCESOS eC_ACCESOS_1 INNER JOIN
                      eC_INCIDENCIAS INNER JOIN
                      EC_PERSONAS_DIARIO ON eC_INCIDENCIAS.INCIDENCIA_ID = EC_PERSONAS_DIARIO.INCIDENCIA_ID INNER JOIN
                      eC_TIPO_INCIDENCIAS ON eC_INCIDENCIAS.TIPO_INCIDENCIA_ID = eC_TIPO_INCIDENCIAS.TIPO_INCIDENCIA_ID INNER JOIN
                      eC_TIPO_INC_SIS ON EC_PERSONAS_DIARIO.TIPO_INC_SIS_ID = eC_TIPO_INC_SIS.TIPO_INC_SIS_ID INNER JOIN
                      EC_V_TURNOS_DIAS ON EC_PERSONAS_DIARIO.TURNO_DIA_ID = EC_V_TURNOS_DIAS.TURNO_DIA_ID ON 
                      eC_ACCESOS_1.ACCESO_ID = EC_PERSONAS_DIARIO.ACCESO_S_ID INNER JOIN
                      eC_ACCESOS ON EC_PERSONAS_DIARIO.ACCESO_E_ID = eC_ACCESOS.ACCESO_ID ;
                      
-- Crea una vista para mostrar los detalles de asistencia en un dia
DROP VIEW EC_V_ASISTENCIAS;
CREATE VIEW EC_V_ASISTENCIAS   
AS       
SELECT     EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID, EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA, EC_ACCESOS.ACCESO_FECHAHORA AS ACCESO_E, 
                      EC_ACCESOS_3.ACCESO_FECHAHORA AS ACCESO_S, EC_ACCESOS_1.ACCESO_FECHAHORA AS ACCESO_CS, 
                      EC_ACCESOS_2.ACCESO_FECHAHORA AS ACCESO_CR, EC_V_PERSONAS_DIARIO.INCIDENCIA_NOMBRE, EC_V_PERSONAS_DIARIO.TURNO, 
                      EC_PERSONAS_DIARIO.INCIDENCIA_ID, EC_PERSONAS_DIARIO.PERSONA_DIARIO_TT, EC_PERSONAS_DIARIO.PERSONA_DIARIO_TE, 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_TC, EC_PERSONAS_DIARIO.PERSONA_DIARIO_TDE, EC_PERSONAS_DIARIO.PERSONA_DIARIO_TES, 
                      EC_PERSONAS_D_HE.PERSONA_D_HE_SIS, EC_PERSONAS_D_HE.PERSONA_D_HE_CAL, EC_PERSONAS_D_HE.PERSONA_D_HE_APL, 
                      EC_V_PERSONAS_DIARIO.TURNO_ID, EC_PERSONAS_DIARIO.PERSONA_ID, EC_PERSONAS_DIARIO.TIPO_INC_SIS_ID, 
                      EC_PERSONAS_DIARIO.TIPO_INC_C_SIS_ID, EC_PERSONAS_DIARIO.TURNO_DIA_ID, EC_PERSONAS_DIARIO.PERSONA_D_HE_ID, 
                      EC_V_PERSONAS_DIARIO.ENTRADASALIDA, EC_PERSONAS.SUSCRIPCION_ID, EC_PERSONAS.PERSONA_LINK_ID, 
                      EC_PERSONAS.PERSONA_NOMBRE, EC_PERSONAS.AGRUPACION_NOMBRE, EC_V_PERSONAS_DIARIO.INCIDENCIA_ABR, 
                      EC_TIPO_INC_COMIDA_SIS.TIPO_INC_C_SIS_NOMBRE, PERSONA_D_HE_SIMPLE, PERSONA_D_HE_DOBLE, PERSONA_D_HE_TRIPLE, PERSONA_D_HE_COMEN, EC_PERSONAS_D_HE.TIPO_INCIDENCIA_ID as TIPO_INCIDENCIA_IDHE,
                      EC_V_PERSONAS_DIARIO.TIPO_INCIDENCIA_ID, INCIDENCIA_COMENTARIO,TURNO_COLOR, INCIDENCIA_COLOR
FROM         EC_PERSONAS_DIARIO INNER JOIN
                      EC_V_PERSONAS_DIARIO ON EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID = EC_V_PERSONAS_DIARIO.PERSONA_DIARIO_ID INNER JOIN
                      EC_PERSONAS ON EC_PERSONAS_DIARIO.PERSONA_ID = EC_PERSONAS.PERSONA_ID INNER JOIN
                      EC_TIPO_INC_COMIDA_SIS ON EC_PERSONAS_DIARIO.TIPO_INC_C_SIS_ID = EC_TIPO_INC_COMIDA_SIS.TIPO_INC_C_SIS_ID LEFT OUTER JOIN
                      EC_ACCESOS EC_ACCESOS_1 ON EC_PERSONAS_DIARIO.ACCESO_CS_ID = EC_ACCESOS_1.ACCESO_ID LEFT OUTER JOIN
                      EC_ACCESOS EC_ACCESOS_2 ON EC_PERSONAS_DIARIO.ACCESO_CR_ID = EC_ACCESOS_2.ACCESO_ID LEFT OUTER JOIN
                      EC_ACCESOS EC_ACCESOS_3 ON EC_PERSONAS_DIARIO.ACCESO_S_ID = EC_ACCESOS_3.ACCESO_ID LEFT OUTER JOIN
                      EC_ACCESOS ON EC_PERSONAS_DIARIO.ACCESO_E_ID = EC_ACCESOS.ACCESO_ID LEFT OUTER JOIN
                      EC_PERSONAS_D_HE ON EC_PERSONAS_DIARIO.PERSONA_D_HE_ID = EC_PERSONAS_D_HE.PERSONA_D_HE_ID;

DROP VIEW EC_V_ASISTENCIAS_V5;
CREATE VIEW EC_V_ASISTENCIAS_V5  
AS   
SELECT EC_V_ASISTENCIAS.*,TURNO_DIA_PHEX,TURNO_DIA_HAYCOMIDA
FROM EC_V_ASISTENCIAS INNER JOIN EC_TURNOS_DIA ON EC_V_ASISTENCIAS.TURNO_DIA_ID = EC_TURNOS_DIA.TURNO_DIA_ID;
                                  
DROP VIEW EC_V_ACCESOS;
CREATE VIEW EC_V_ACCESOS   
AS       
SELECT     EC_ACCESOS.ACCESO_ID, EC_PERSONAS.PERSONA_ID, EC_PERSONAS.SUSCRIPCION_ID, EC_PERSONAS.PERSONA_LINK_ID, 
                      EC_PERSONAS.PERSONA_NOMBRE, EC_TERMINALES.TERMINAL_NOMBRE, EC_TIPO_ACCESOS.TIPO_ACCESO_NOMBRE, 
                      EC_ACCESOS.ACCESO_FECHAHORA, EC_ACCESOS.ACCESO_CALCULADO, EC_PERSONAS.AGRUPACION_NOMBRE
FROM         EC_PERSONAS INNER JOIN
                      EC_ACCESOS ON EC_PERSONAS.PERSONA_ID = EC_ACCESOS.PERSONA_ID INNER JOIN
                      EC_TIPO_ACCESOS ON EC_ACCESOS.TIPO_ACCESO_ID = EC_TIPO_ACCESOS.TIPO_ACCESO_ID INNER JOIN
                      EC_TERMINALES ON EC_ACCESOS.TERMINAL_ID = EC_TERMINALES.TERMINAL_ID;

DROP VIEW EC_V_ASISTENCIAS_SEMANA;
CREATE VIEW EC_V_ASISTENCIAS_SEMANA   
AS                            
SELECT     EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID, EC_PERSONAS.PERSONA_ID, EC_PERSONAS.PERSONA_LINK_ID, 
                      EC_PERSONAS.PERSONA_NOMBRE, EC_TURNOS.TURNO_NOMBRE, EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA, 
                      EC_V_PERSONAS_DIARIO.TURNO_ID AS TURNO_ID_D0, 
                      EC_V_PERSONAS_DIARIO.TURNO || ' / ' || EC_V_PERSONAS_DIARIO.INCIDENCIA_ABR AS TURNO_D0, 
                      EC_V_PERSONAS_DIARIO.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO.INCIDENCIA_ABR AS ASISTENCIA_D0, 
                      EC_V_PERSONAS_DIARIO_1.TURNO_ID AS TURNO_ID_D1, EC_V_PERSONAS_DIARIO_1.TURNO || ' / ' || EC_V_PERSONAS_DIARIO_1.INCIDENCIA_ABR AS TURNO_D1,
                       EC_V_PERSONAS_DIARIO_1.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO_1.INCIDENCIA_ABR AS ASISTENCIA_D1, 
                      EC_V_PERSONAS_DIARIO_2.TURNO_ID AS TURNO_ID_D2, EC_V_PERSONAS_DIARIO_2.TURNO || ' / ' || EC_V_PERSONAS_DIARIO_2.INCIDENCIA_ABR AS TURNO_D2,
                       EC_V_PERSONAS_DIARIO_2.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO_2.INCIDENCIA_ABR AS ASISTENCIA_D2, 
                      EC_V_PERSONAS_DIARIO_3.TURNO_ID AS TURNO_ID_D3, EC_V_PERSONAS_DIARIO_3.TURNO || ' / ' || EC_V_PERSONAS_DIARIO_3.INCIDENCIA_ABR AS TURNO_D3,
                       EC_V_PERSONAS_DIARIO_3.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO_3.INCIDENCIA_ABR AS ASISTENCIA_D3, 
                      EC_V_PERSONAS_DIARIO_4.TURNO_ID AS TURNO_ID_D4, EC_V_PERSONAS_DIARIO_4.TURNO || ' / ' || EC_V_PERSONAS_DIARIO_4.INCIDENCIA_ABR AS TURNO_D4,
                       EC_V_PERSONAS_DIARIO_4.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO_4.INCIDENCIA_ABR AS ASISTENCIA_D4, 
                      EC_V_PERSONAS_DIARIO_5.TURNO_ID AS TURNO_ID_D5, EC_V_PERSONAS_DIARIO_5.TURNO || ' / ' || EC_V_PERSONAS_DIARIO_5.INCIDENCIA_ABR AS TURNO_D5,
                       EC_V_PERSONAS_DIARIO_5.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO_5.INCIDENCIA_ABR AS ASISTENCIA_D5, 
                      EC_V_PERSONAS_DIARIO_6.TURNO_ID AS TURNO_ID_D6, EC_V_PERSONAS_DIARIO_6.TURNO || ' / ' || EC_V_PERSONAS_DIARIO_6.INCIDENCIA_ABR AS TURNO_D6,
                       EC_V_PERSONAS_DIARIO_6.ENTRADASALIDA || ' / ' || EC_V_PERSONAS_DIARIO_6.INCIDENCIA_ABR AS ASISTENCIA_D6, 
                      EC_PERSONAS.AGRUPACION_NOMBRE, EC_PERSONAS.TURNO_ID, EC_PERSONAS.SUSCRIPCION_ID
FROM         EC_PERSONAS_DIARIO INNER JOIN
                      EC_PERSONAS ON EC_PERSONAS_DIARIO.PERSONA_ID = EC_PERSONAS.PERSONA_ID INNER JOIN
                      EC_TURNOS ON EC_PERSONAS.TURNO_ID = EC_TURNOS.TURNO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO ON EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID = EC_V_PERSONAS_DIARIO.PERSONA_DIARIO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO EC_V_PERSONAS_DIARIO_1 ON 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID + 1 = EC_V_PERSONAS_DIARIO_1.PERSONA_DIARIO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO EC_V_PERSONAS_DIARIO_2 ON 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID + 2 = EC_V_PERSONAS_DIARIO_2.PERSONA_DIARIO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO EC_V_PERSONAS_DIARIO_3 ON 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID + 3 = EC_V_PERSONAS_DIARIO_3.PERSONA_DIARIO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO EC_V_PERSONAS_DIARIO_4 ON 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID + 4 = EC_V_PERSONAS_DIARIO_4.PERSONA_DIARIO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO EC_V_PERSONAS_DIARIO_5 ON 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID + 5 = EC_V_PERSONAS_DIARIO_5.PERSONA_DIARIO_ID INNER JOIN
                      EC_V_PERSONAS_DIARIO EC_V_PERSONAS_DIARIO_6 ON 
                      EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID + 6 = EC_V_PERSONAS_DIARIO_6.PERSONA_DIARIO_ID;

DROP VIEW EC_V_ASISTENCIAS_ES;
CREATE VIEW EC_V_ASISTENCIAS_ES   
AS                           
SELECT     EC_PERSONAS_ES.PERSONA_ES_ID, EC_PERSONAS_DIARIO.PERSONA_DIARIO_FECHA, EC_PERSONAS_ES.PERSONA_ES_ORD, 
                      EC_ACCESOS.ACCESO_FECHAHORA AS ACCESO_E_ES, EC_ACCESOS_1.ACCESO_FECHAHORA AS ACCESO_S_ES, EC_PERSONAS_ES.PERSONA_ES_TE, 
                      EC_PERSONAS.PERSONA_ID, EC_PERSONAS_ES.TIPO_INC_SIS_ID, EC_PERSONAS.SUSCRIPCION_ID, EC_PERSONAS.PERSONA_LINK_ID, 
                      EC_PERSONAS.PERSONA_NOMBRE, EC_PERSONAS.AGRUPACION_NOMBRE
FROM         EC_PERSONAS_DIARIO INNER JOIN
                      EC_PERSONAS_ES ON EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID = EC_PERSONAS_ES.PERSONA_DIARIO_ID INNER JOIN
                      EC_PERSONAS ON EC_PERSONAS_DIARIO.PERSONA_ID = EC_PERSONAS.PERSONA_ID INNER JOIN
                      EC_ACCESOS ON EC_PERSONAS_ES.ACCESO_E_ES_ID = EC_ACCESOS.ACCESO_ID INNER JOIN
                      EC_ACCESOS EC_ACCESOS_1 ON EC_PERSONAS_ES.ACCESO_S_ES_ID = EC_ACCESOS_1.ACCESO_ID;

DROP VIEW EC_V_PERSONAS_DIARIO_EX;
CREATE VIEW EC_V_PERSONAS_DIARIO_EX   
AS 
SELECT     EC_PERSONAS_DIARIO.PERSONA_DIARIO_ID,
CASE WHEN EC_PERSONAS_DIARIO.INCIDENCIA_ID = 0 
	 THEN 
		EC_TIPO_INCIDENCIAS_EX.TIPO_INCIDENCIAS_EX_ID
	 ELSE
		EC_TIPO_INCIDENCIAS_EX_1.TIPO_INCIDENCIAS_EX_ID
	 END AS TIPO_INCIDENCIAS_EX_ID,
	 CASE WHEN EC_PERSONAS_DIARIO.INCIDENCIA_ID = 0 
	 THEN 
		EC_TIPO_INCIDENCIAS_EX.TIPO_INCIDENCIAS_EX_TXT
	 ELSE
		EC_TIPO_INCIDENCIAS_EX_1.TIPO_INCIDENCIAS_EX_TXT
	 END AS TIPO_INCIDENCIAS_EX_TXT, 
    CASE WHEN EC_PERSONAS_DIARIO.INCIDENCIA_ID = 0 
	 THEN 
		EC_TIPO_INCIDENCIAS_EX.TIPO_FALTA_EX_ID
	 ELSE
		EC_TIPO_INCIDENCIAS_EX_1.TIPO_FALTA_EX_ID
	 END AS TIPO_FALTA_EX_ID, 
	CASE WHEN EC_PERSONAS_DIARIO.INCIDENCIA_ID = 0 
	 THEN 
		EC_TIPO_INCIDENCIAS_EX.TIPO_INCIDENCIAS_EX_PARAM
	 ELSE
		EC_TIPO_INCIDENCIAS_EX_1.TIPO_INCIDENCIAS_EX_PARAM
	 END AS TIPO_INCIDENCIAS_EX_PARAM,
	 EC_INCIDENCIAS.INCIDENCIA_COMENTARIO
FROM         EC_TIPO_INCIDENCIAS_EX EC_TIPO_INCIDENCIAS_EX_1 INNER JOIN
                      EC_TIPO_INCIDENCIAS_EX_INC ON 
                      EC_TIPO_INCIDENCIAS_EX_1.TIPO_INCIDENCIAS_EX_ID = EC_TIPO_INCIDENCIAS_EX_INC.TIPO_INCIDENCIAS_EX_ID INNER JOIN
                      EC_INCIDENCIAS ON EC_TIPO_INCIDENCIAS_EX_INC.TIPO_INCIDENCIA_ID = EC_INCIDENCIAS.TIPO_INCIDENCIA_ID RIGHT OUTER JOIN
                      EC_PERSONAS_DIARIO LEFT OUTER JOIN
                      EC_TIPO_INCIDENCIAS_EX INNER JOIN
                      EC_TIPO_INCIDENCIAS_EX_INC_SIS ON 
                      EC_TIPO_INCIDENCIAS_EX.TIPO_INCIDENCIAS_EX_ID = EC_TIPO_INCIDENCIAS_EX_INC_SIS.TIPO_INCIDENCIAS_EX_ID ON 
                      EC_PERSONAS_DIARIO.TIPO_INC_SIS_ID = EC_TIPO_INCIDENCIAS_EX_INC_SIS.TIPO_INC_SIS_ID ON 
                      EC_INCIDENCIAS.INCIDENCIA_ID = EC_PERSONAS_DIARIO.INCIDENCIA_ID
WHERE EC_TIPO_INCIDENCIAS_EX.TIPO_INCIDENCIAS_EX_ID > 0 OR EC_TIPO_INCIDENCIAS_EX_1.TIPO_INCIDENCIAS_EX_ID >0;

--Crea la vista para reportes de Comida y Monedero
DROP VIEW EC_V_MONEDERO_SALDO;
CREATE VIEW EC_V_MONEDERO_SALDO
AS 
SELECT     MONEDERO_ID, TIPO_COBRO_ID, PERSONA_ID, SESION_ID, MONEDERO_FECHA, MONEDERO_CONSUMO, MONEDERO_SALDO
FROM         EC_MONEDERO
WHERE     (MONEDERO_ID IN (SELECT     MAX(MONEDERO_ID) MONEDERO_ID
                            FROM          EC_MONEDERO  EC_MONEDERO
                            GROUP BY PERSONA_ID));

DROP VIEW EC_V_PERSONAS_COMIDA;
CREATE VIEW EC_V_PERSONAS_COMIDA
AS
SELECT     PERSONA_COMIDA_ID, PERSONA_ID, PERSONA_COMIDA_FECHA, 
		CASE WHEN TIPO_COMIDA_ID = 1 THEN TIPO_COMIDA_COSTOA ELSE 0 END AS PRIMERA_COMIDA_COSTO, 
		CASE WHEN TIPO_COMIDA_ID = 1 THEN 1 ELSE 0 END AS PRIMERA_COMIDA_ES, 
		CASE WHEN TIPO_COMIDA_ID = 2 THEN TIPO_COMIDA_COSTOA ELSE 0 END AS SEGUNDA_COMIDA_COSTO, 
		CASE WHEN TIPO_COMIDA_ID = 2 THEN 2 ELSE 0 END AS SEGUNDA_COMIDA_ES, TIPO_COMIDA_ID, TIPO_COMIDA_COSTOA, TIPO_COBRO_ID, SESION_ID
FROM        EC_PERSONAS_COMIDA;
--Fin de vistas para reporte de Comida y Monedero

DROP VIEW EC_V_TERMINAL_CID_PERSONA;
CREATE VIEW EC_V_TERMINAL_CID_PERSONA  
AS 
SELECT     EC_TERMINALES.TERMINAL_CAMPO_LLAVE, EC_PERSONAS_TERMINALES.PERSONA_ID
FROM EC_TERMINALES INNER JOIN
    EC_PERSONAS_TERMINALES ON EC_TERMINALES.TERMINAL_ID = EC_PERSONAS_TERMINALES.TERMINAL_ID
WHERE     (EC_PERSONAS_TERMINALES.PERSONA_TERMINAL_UPDATE IS NOT NULL)
GROUP BY EC_TERMINALES.TERMINAL_CAMPO_LLAVE, EC_PERSONAS_TERMINALES.PERSONA_ID;

DROP VIEW EC_V_TERMINALES_EDO;
CREATE VIEW EC_V_TERMINALES_EDO   
AS 
SELECT     EC_TERMINALES.TERMINAL_ID, EC_TERMINALES.TERMINAL_NOMBRE, EC_SITIOS.SITIO_NOMBRE, 
EC_MODELOS_TERMINALES.MODELO_TERMINAL_NOMBRE, EC_TIPO_TECNOLOGIAS.TIPO_TECNOLOGIA_NOMBRE, 
EC_TIPO_TECNOLOGIAS_1.TIPO_TECNOLOGIA_NOMBRE AS TIPO_TECNOLOGIA_NOMBRE_ADD, EC_TERMINALES.TERMINAL_SINCRONIZACION, 
EC_TERMINALES.TERMINAL_CAMPO_LLAVE, EC_TERMINALES.TERMINAL_CAMPO_ADICIONAL, EC_TERMINALES.TERMINAL_ENROLA, 
EC_TERMINALES.TERMINAL_DIR, EC_TERMINALES.TERMINAL_ASISTENCIA, EC_TERMINALES.TERMINAL_MINUTOS_DIF, 
EC_TERMINALES.TERMINAL_BORRADO,
	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS 
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 101) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Conexion_Correcta,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 102) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Error_Conexion,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 103) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS ComunicacionCorrecta,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 104) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Error_Comunicacion,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 105) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Log_Comunicacion,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 106) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS FechaHora_Enviada,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 107) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS FechaHora_Error,	

(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 108) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Checadas_Descargadas,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 109) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Checadas_Error,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 110) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Vectores_Descargados,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 111) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Vectores_Error_Desc,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 112) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Vectores_Enviados,

	(SELECT     TERMINALES_DEXTRAS_TEXTO1
	FROM          EC_TERMINALES_DEXTRAS
	WHERE      (TERMINALES_DEXTRAS_ID IN
		(SELECT     MAX(TERMINALES_DEXTRAS_ID) AS TERMINALES_DEXTRAS_ID
		 FROM          EC_TERMINALES_DEXTRAS
		 WHERE      (TIPO_TERM_DEXTRAS_ID = 113) AND (TERMINAL_ID = EC_TERMINALES.TERMINAL_ID)))) AS Vectores_Error_Env	,

		( SELECT     COUNT(*)
FROM         EC_PERSONAS_TERMINALES WHERE TERMINAL_ID = EC_TERMINALES.TERMINAL_ID AND PERSONA_ID NOT IN (SELECT PERSONA_ID FROM EC_PERSONAS WHERE PERSONA_BORRADO = 1)) AS NO_PERSONAS,
( SELECT     COUNT(*)
FROM         EC_PERSONAS_TERMINALES,EC_V_TERMINAL_CID_PERSONA WHERE EC_PERSONAS_TERMINALES.PERSONA_ID = EC_V_TERMINAL_CID_PERSONA.PERSONA_ID  
   AND TERMINAL_ID = EC_TERMINALES.TERMINAL_ID AND TERMINAL_CAMPO_LLAVE = EC_TERMINALES.TERMINAL_CAMPO_LLAVE AND EC_PERSONAS_TERMINALES.PERSONA_ID  NOT IN (SELECT PERSONA_ID FROM EC_PERSONAS WHERE PERSONA_BORRADO = 1)) AS NO_PERSONAS_POS,

( SELECT     COUNT(*)
FROM         EC_PERSONAS_TERMINALES WHERE TERMINAL_ID = EC_TERMINALES.TERMINAL_ID AND PERSONA_TERMINAL_UPDATE IS NOT NULL AND PERSONA_ID NOT IN (SELECT PERSONA_ID FROM EC_PERSONAS WHERE PERSONA_BORRADO = 1)) AS NO_PERSONAS_ENV,
( SELECT     COUNT(*)
FROM         EC_PERSONAS_TERMINALES, EC_PERSONAS_A_VEC WHERE EC_PERSONAS_TERMINALES.PERSONA_ID = EC_PERSONAS_A_VEC.PERSONA_ID AND TERMINAL_ID = EC_TERMINALES.TERMINAL_ID AND 
ALMACEN_VEC_ID = EC_TERMINALES.ALMACEN_VEC_ID AND EC_PERSONAS_TERMINALES.PERSONA_ID NOT IN (SELECT PERSONA_ID FROM EC_PERSONAS WHERE PERSONA_BORRADO = 1) AND PERSONAS_A_VEC_1 IS NOT NULL) AS NO_PERSONAS_HUELLA
FROM         EC_TERMINALES INNER JOIN
                      EC_SITIOS ON EC_TERMINALES.SITIO_ID = EC_SITIOS.SITIO_ID INNER JOIN
                      EC_MODELOS_TERMINALES ON EC_TERMINALES.MODELO_TERMINAL_ID = EC_MODELOS_TERMINALES.MODELO_TERMINAL_ID INNER JOIN
                      EC_TIPO_TECNOLOGIAS ON EC_TERMINALES.TIPO_TECNOLOGIA_ID = EC_TIPO_TECNOLOGIAS.TIPO_TECNOLOGIA_ID INNER JOIN
                      EC_TIPO_TECNOLOGIAS EC_TIPO_TECNOLOGIAS_1 ON 
                      EC_TERMINALES.TIPO_TECNOLOGIA_ADD_ID = EC_TIPO_TECNOLOGIAS_1.TIPO_TECNOLOGIA_ID;

DROP VIEW EC_V_ACCESOS_X_DIA;
CREATE VIEW EC_V_ACCESOS_X_DIA   
AS 
SELECT TERMINAL_ID, TO_DATE(TO_CHAR(ACCESO_FECHAHORA, 'DD/MM/YYYY'), 'DD/MM/YYYY') AS ACCESO_FECHA, COUNT(*) AS ACCESOS_NO
FROM EC_ACCESOS
GROUP BY TERMINAL_ID, TO_CHAR(ACCESO_FECHAHORA, 'DD/MM/YYYY');